In [1]:
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib as mpl
import seaborn as sns
df =pd.read_csv("/content/bank_marketing_test.csv")

In [2]:
df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,41,blue-collar,married,unknown,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,25,services,single,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,35,blue-collar,married,basic.6y,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,46,blue-collar,married,basic.6y,unknown,yes,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [3]:
df.head(10)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,41,blue-collar,married,unknown,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,25,services,single,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,35,blue-collar,married,basic.6y,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,46,blue-collar,married,basic.6y,unknown,yes,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
5,55,unknown,married,basic.4y,unknown,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
6,56,technician,married,basic.4y,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
7,40,blue-collar,married,basic.9y,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
8,45,blue-collar,married,basic.9y,no,yes,no,telephone,may,mon,...,2,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
9,53,admin.,single,professional.course,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [4]:
df.head(20)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,41,blue-collar,married,unknown,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,25,services,single,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,35,blue-collar,married,basic.6y,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,46,blue-collar,married,basic.6y,unknown,yes,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
5,55,unknown,married,basic.4y,unknown,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
6,56,technician,married,basic.4y,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
7,40,blue-collar,married,basic.9y,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
8,45,blue-collar,married,basic.9y,no,yes,no,telephone,may,mon,...,2,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
9,53,admin.,single,professional.course,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
10,55,technician,married,professional.course,unknown,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
11,25,technician,single,university.degree,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
12,42,blue-collar,married,basic.9y,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
13,51,blue-collar,married,basic.4y,unknown,unknown,unknown,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
14,38,admin.,married,high.school,unknown,no,no,telephone,may,mon,...,2,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
15,60,admin.,married,unknown,unknown,no,yes,telephone,may,mon,...,2,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
16,33,unemployed,married,basic.9y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
17,44,blue-collar,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
18,35,admin.,married,high.school,no,yes,no,telephone,may,mon,...,2,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
19,37,management,married,university.degree,no,no,no,telephone,may,mon,...,2,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [5]:
df.tail()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
8232,41,blue-collar,married,basic.9y,no,yes,no,cellular,nov,mon,...,2,999,1,failure,-1.1,94.767,-50.8,1.039,4963.6,no
8233,60,blue-collar,married,basic.4y,no,yes,no,cellular,nov,tue,...,2,4,1,success,-1.1,94.767,-50.8,1.035,4963.6,no
8234,32,admin.,married,university.degree,no,no,no,telephone,nov,wed,...,1,999,1,failure,-1.1,94.767,-50.8,1.030,4963.6,yes
8235,32,admin.,married,university.degree,no,yes,no,cellular,nov,wed,...,3,999,0,nonexistent,-1.1,94.767,-50.8,1.030,4963.6,no
8236,36,admin.,married,university.degree,no,no,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no

In [6]:
df.tail(5)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
8232,41,blue-collar,married,basic.9y,no,yes,no,cellular,nov,mon,...,2,999,1,failure,-1.1,94.767,-50.8,1.039,4963.6,no
8233,60,blue-collar,married,basic.4y,no,yes,no,cellular,nov,tue,...,2,4,1,success,-1.1,94.767,-50.8,1.035,4963.6,no
8234,32,admin.,married,university.degree,no,no,no,telephone,nov,wed,...,1,999,1,failure,-1.1,94.767,-50.8,1.030,4963.6,yes
8235,32,admin.,married,university.degree,no,yes,no,cellular,nov,wed,...,3,999,0,nonexistent,-1.1,94.767,-50.8,1.030,4963.6,no
8236,36,admin.,married,university.degree,no,no,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no

In [7]:
df.tail(10)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
8227,58,unemployed,married,university.degree,no,yes,no,cellular,nov,thu,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.041,4963.6,yes
8228,33,management,married,university.degree,no,yes,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.040,4963.6,yes
8229,43,admin.,divorced,university.degree,no,yes,no,cellular,nov,fri,...,4,999,2,failure,-1.1,94.767,-50.8,1.040,4963.6,yes
8230,35,admin.,single,professional.course,no,yes,no,cellular,nov,fri,...,3,999,4,failure,-1.1,94.767,-50.8,1.040,4963.6,no
8231,35,admin.,single,professional.course,no,yes,no,cellular,nov,fri,...,3,999,0,nonexistent,-1.1,94.767,-50.8,1.040,4963.6,yes
8232,41,blue-collar,married,basic.9y,no,yes,no,cellular,nov,mon,...,2,999,1,failure,-1.1,94.767,-50.8,1.039,4963.6,no
8233,60,blue-collar,married,basic.4y,no,yes,no,cellular,nov,tue,...,2,4,1,success,-1.1,94.767,-50.8,1.035,4963.6,no
8234,32,admin.,married,university.degree,no,no,no,telephone,nov,wed,...,1,999,1,failure,-1.1,94.767,-50.8,1.030,4963.6,yes
8235,32,admin.,married,university.degree,no,yes,no,cellular,nov,wed,...,3,999,0,nonexistent,-1.1,94.767,-50.8,1.030,4963.6,no
8236,36,admin.,married,university.degree,no,no,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no

In [8]:
df.min(numeric_only=True)

age                 17.000
duration             4.000
campaign             1.000
pdays                0.000
previous             0.000
emp.var.rate        -3.400
cons.price.idx      92.201
cons.conf.idx      -50.800
euribor3m            0.634
nr.employed       4963.600
dtype: float64

In [11]:
df.max(numeric_only=True)

age                 89.000
duration          4918.000
campaign            43.000
pdays              999.000
previous             6.000
emp.var.rate         1.400
cons.price.idx      94.767
cons.conf.idx      -26.900
euribor3m            5.000
nr.employed       5228.100
dtype: float64

In [10]:
df.dtypes

age                 int64
job                object
marital            object
education          object
default            object
housing            object
loan               object
contact            object
month              object
day_of_week        object
duration            int64
campaign            int64
pdays               int64
previous            int64
poutcome           object
emp.var.rate      float64
cons.price.idx    float64
cons.conf.idx     float64
euribor3m         float64
nr.employed       float64
y                  object
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8237 entries, 0 to 8236
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             8237 non-null   int64
 1   job             8237 non-null   object
 2   marital         8237 non-null   object
 3   education       8237 non-null   object
 4   default         8237 non-null   object
 5   housing         8237 non-null   object
 6   loan            8237 non-null   object
 7   contact         8237 non-null   object
 8   month           8237 non-null   object
 9   day_of_week     8237 non-null   object
 10  duration        8237 non-null   int64
 11  campaign        8237 non-null   int64
 12  pdays           8237 non-null   int64
 13  previous        8237 non-null   int64
 14  poutcome        8237 non-null   object
 15  emp.var.rate    8237 non-null   float64
 16  cons.price.idx  8237 non-null   float64
 17  cons.conf.idx   8237 non-null   float64
 18  euribor3m       8237 non-null   float64
 19  nr.employed     8237 non-null   float64
 20  y               8237 non-null   object
dtypes: float64(5), int64(5), object(11)
memory usage: 1.3+ MB

In [12]:
df['job'].dtypes

dtype('O')

In [13]:
print(df.axes)

[RangeIndex(start=0, stop=8237, step=1), Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y'],
      dtype='object')]

In [14]:
print(df.ndim)

2

In [15]:
print(df.size)

172977

In [16]:
print(df.shape)

(8237, 21)

In [17]:
print(df.values)

[[56 'services' 'married' ... 4.857 5191.0 'no']
 [41 'blue-collar' 'married' ... 4.857 5191.0 'no']
 [25 'services' 'single' ... 4.857 5191.0 'no']
 ...
 [32 'admin.' 'married' ... 1.03 4963.6 'yes']
 [32 'admin.' 'married' ... 1.03 4963.6 'no']
 [36 'admin.' 'married' ... 1.028 4963.6 'no']]

In [18]:
print("Number of records:", len(df))

Number of records: 8237

In [19]:
print("Number of records:", df.shape[0])

Number of records: 8237

In [20]:
print("Number of elements:", df.size)

Number of elements: 172977

In [21]:
print("Column Names:")
print(df.columns)

Column Names:
Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y'],
      dtype='object')

In [22]:
print("Column Data Types:")
print(df.dtypes)

Column Data Types:
age                 int64
job                object
marital            object
education          object
default            object
housing            object
loan               object
contact            object
month              object
day_of_week        object
duration            int64
campaign            int64
pdays               int64
previous            int64
poutcome           object
emp.var.rate      float64
cons.price.idx    float64
cons.conf.idx     float64
euribor3m         float64
nr.employed       float64
y                  object
dtype: object

In [23]:
df.describe()

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed
count,8237.000000,8237.000000,8237.00000,8237.000000,8237.000000,8237.000000,8237.000000,8237.000000,8237.000000,8237.000000
mean,40.116547,256.007648,2.60471,962.228724,0.174335,0.070147,93.577806,-40.545320,3.608206,5166.589790
std,10.465328,259.728737,2.91562,187.533881,0.500565,1.574685,0.582138,4.623626,1.735931,72.470977
min,17.000000,4.000000,1.00000,0.000000,0.000000,-3.400000,92.201000,-50.800000,0.634000,4963.600000
25%,32.000000,101.000000,1.00000,999.000000,0.000000,-1.800000,93.075000,-42.700000,1.344000,5099.100000
50%,38.000000,179.000000,2.00000,999.000000,0.000000,1.100000,93.444000,-41.800000,4.857000,5191.000000
75%,47.000000,316.000000,3.00000,999.000000,0.000000,1.400000,93.994000,-36.400000,4.961000,5228.100000
max,89.000000,4918.000000,43.00000,999.000000,6.000000,1.400000,94.767000,-26.900000,5.000000,5228.100000

In [24]:
df.median(numeric_only=True)

age                 38.000
duration           179.000
campaign             2.000
pdays              999.000
previous             0.000
emp.var.rate         1.100
cons.price.idx      93.444
cons.conf.idx      -41.800
euribor3m            4.857
nr.employed       5191.000
dtype: float64

In [25]:
df.mode(numeric_only=True)

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed
0,32,71,1,999,0,1.4,93.994,-36.4,4.857,5228.1

In [26]:
df.mean(numeric_only=True)

age                 40.116547
duration           256.007648
campaign             2.604710
pdays              962.228724
previous             0.174335
emp.var.rate         0.070147
cons.price.idx      93.577806
cons.conf.idx      -40.545320
euribor3m            3.608206
nr.employed       5166.589790
dtype: float64

In [27]:
df.std(numeric_only=True)

age                10.465328
duration          259.728737
campaign            2.915620
pdays             187.533881
previous            0.500565
emp.var.rate        1.574685
cons.price.idx      0.582138
cons.conf.idx       4.623626
euribor3m           1.735931
nr.employed        72.470977
dtype: float64

In [28]:
# Display a random sample of 5 rows
df.sample(5)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
6938,45,entrepreneur,divorced,university.degree,no,yes,yes,telephone,may,thu,...,2,999,0,nonexistent,-1.8,92.893,-46.2,1.266,5099.1,no
819,52,services,divorced,high.school,no,no,no,telephone,may,mon,...,5,999,0,nonexistent,1.1,93.994,-36.4,4.858,5191.0,yes
3749,27,admin.,single,high.school,no,yes,no,cellular,jul,thu,...,3,999,0,nonexistent,1.4,93.918,-42.7,4.968,5228.1,no
7999,46,admin.,married,high.school,no,yes,yes,cellular,jul,tue,...,1,13,2,success,-1.7,94.215,-40.3,0.797,4991.6,yes
1593,30,technician,married,professional.course,no,yes,no,telephone,jun,mon,...,1,999,0,nonexistent,1.4,94.465,-41.8,4.865,5228.1,no

In [29]:
df.sample(20)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
1631,36,management,married,university.degree,unknown,no,no,telephone,jun,tue,...,13,999,0,nonexistent,1.4,94.465,-41.8,4.864,5228.1,no
6988,35,management,single,university.degree,no,yes,no,cellular,may,fri,...,1,999,1,failure,-1.8,92.893,-46.2,1.250,5099.1,no
4981,35,admin.,divorced,high.school,no,yes,no,cellular,nov,tue,...,2,999,0,nonexistent,-0.1,93.200,-42.0,4.153,5195.8,no
2003,30,self-employed,single,university.degree,no,no,no,telephone,jun,wed,...,3,999,0,nonexistent,1.4,94.465,-41.8,4.959,5228.1,no
4820,48,admin.,divorced,high.school,no,yes,no,cellular,nov,mon,...,2,999,0,nonexistent,-0.1,93.200,-42.0,4.191,5195.8,no
4310,35,technician,married,professional.course,no,no,no,cellular,aug,tue,...,2,999,0,nonexistent,1.4,93.444,-36.1,4.963,5228.1,no
4640,37,technician,married,university.degree,no,no,no,cellular,aug,wed,...,5,999,0,nonexistent,1.4,93.444,-36.1,4.964,5228.1,no
4473,30,technician,single,professional.course,no,yes,yes,cellular,aug,fri,...,13,999,0,nonexistent,1.4,93.444,-36.1,4.964,5228.1,no
284,35,unknown,married,basic.9y,no,no,no,telephone,may,thu,...,3,999,0,nonexistent,1.1,93.994,-36.4,4.855,5191.0,no
3309,31,blue-collar,single,basic.6y,no,no,no,cellular,jul,wed,...,2,999,0,nonexistent,1.4,93.918,-42.7,4.963,5228.1,no
148,36,services,single,unknown,no,yes,no,telephone,may,wed,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.856,5191.0,no
7164,32,technician,single,university.degree,no,no,no,cellular,may,fri,...,1,999,0,nonexistent,-1.8,92.893,-46.2,1.259,5099.1,no
7039,37,services,divorced,basic.4y,no,no,no,cellular,may,fri,...,8,999,0,nonexistent,-1.8,92.893,-46.2,1.250,5099.1,no
200,48,management,married,university.degree,no,yes,no,telephone,may,wed,...,3,999,0,nonexistent,1.1,93.994,-36.4,4.856,5191.0,no
7905,26,admin.,single,university.degree,no,yes,no,cellular,apr,thu,...,2,999,1,failure,-1.8,93.749,-34.6,0.659,5008.7,no
6330,34,blue-collar,married,basic.4y,no,no,no,cellular,may,thu,...,1,999,0,nonexistent,-1.8,92.893,-46.2,1.327,5099.1,no
3169,30,technician,single,university.degree,no,yes,yes,cellular,jul,mon,...,7,999,0,nonexistent,1.4,93.918,-42.7,4.960,5228.1,no
7214,25,admin.,single,university.degree,no,yes,yes,cellular,may,tue,...,1,999,0,nonexistent,-1.8,92.893,-46.2,1.266,5099.1,no
6518,32,housemaid,single,basic.9y,no,yes,no,cellular,may,mon,...,1,999,1,failure,-1.8,92.893,-46.2,1.299,5099.1,no
2420,55,blue-collar,married,basic.4y,unknown,unknown,unknown,telephone,jun,fri,...,4,999,0,nonexistent,1.4,94.465,-41.8,4.959,5228.1,no

In [30]:
df.sample(20)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
732,29,entrepreneur,married,basic.6y,no,no,no,telephone,may,fri,...,2,999,0,nonexistent,1.1,93.994,-36.4,4.859,5191.0,no
508,49,blue-collar,married,basic.4y,unknown,no,no,telephone,may,tue,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.856,5191.0,no
343,26,admin.,married,high.school,no,yes,yes,telephone,may,fri,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.855,5191.0,no
6614,40,services,divorced,high.school,no,no,no,cellular,may,tue,...,1,999,0,nonexistent,-1.8,92.893,-46.2,1.291,5099.1,no
1300,40,admin.,single,high.school,no,yes,no,telephone,may,wed,...,3,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
646,53,services,married,high.school,unknown,no,no,telephone,may,thu,...,4,999,0,nonexistent,1.1,93.994,-36.4,4.860,5191.0,no
1999,35,blue-collar,single,unknown,no,no,no,telephone,jun,wed,...,4,999,0,nonexistent,1.4,94.465,-41.8,4.959,5228.1,no
4305,33,technician,single,university.degree,no,yes,no,cellular,aug,tue,...,3,999,0,nonexistent,1.4,93.444,-36.1,4.963,5228.1,no
5196,39,services,married,professional.course,no,no,no,cellular,nov,thu,...,7,999,0,nonexistent,-0.1,93.200,-42.0,4.076,5195.8,no
6650,28,blue-collar,married,basic.4y,no,no,no,cellular,may,tue,...,1,999,0,nonexistent,-1.8,92.893,-46.2,1.291,5099.1,no
5827,36,blue-collar,married,basic.9y,no,yes,no,cellular,apr,fri,...,4,999,0,nonexistent,-1.8,93.075,-47.1,1.405,5099.1,no
4619,31,management,married,university.degree,no,no,no,cellular,aug,wed,...,4,999,0,nonexistent,1.4,93.444,-36.1,4.964,5228.1,no
8207,25,student,single,high.school,no,yes,no,cellular,oct,mon,...,2,6,3,success,-1.1,94.601,-49.5,1.032,4963.6,yes
1577,28,admin.,married,university.degree,no,no,no,telephone,jun,mon,...,2,999,0,nonexistent,1.4,94.465,-41.8,4.865,5228.1,no
3695,46,technician,divorced,professional.course,no,no,no,cellular,jul,thu,...,3,999,0,nonexistent,1.4,93.918,-42.7,4.968,5228.1,no
369,45,blue-collar,married,basic.9y,unknown,no,no,telephone,may,fri,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.855,5191.0,no
5149,49,admin.,divorced,high.school,no,yes,no,cellular,nov,wed,...,1,999,1,failure,-0.1,93.200,-42.0,4.120,5195.8,no
3732,33,blue-collar,married,basic.9y,no,yes,no,cellular,jul,thu,...,14,999,0,nonexistent,1.4,93.918,-42.7,4.968,5228.1,no
7164,32,technician,single,university.degree,no,no,no,cellular,may,fri,...,1,999,0,nonexistent,-1.8,92.893,-46.2,1.259,5099.1,no
1272,33,blue-collar,married,basic.9y,unknown,yes,no,telephone,may,wed,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [31]:
# Remove rows with missing values
df.dropna()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,41,blue-collar,married,unknown,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,25,services,single,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,35,blue-collar,married,basic.6y,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,46,blue-collar,married,basic.6y,unknown,yes,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8232,41,blue-collar,married,basic.9y,no,yes,no,cellular,nov,mon,...,2,999,1,failure,-1.1,94.767,-50.8,1.039,4963.6,no
8233,60,blue-collar,married,basic.4y,no,yes,no,cellular,nov,tue,...,2,4,1,success,-1.1,94.767,-50.8,1.035,4963.6,no
8234,32,admin.,married,university.degree,no,no,no,telephone,nov,wed,...,1,999,1,failure,-1.1,94.767,-50.8,1.030,4963.6,yes
8235,32,admin.,married,university.degree,no,yes,no,cellular,nov,wed,...,3,999,0,nonexistent,-1.1,94.767,-50.8,1.030,4963.6,no
8236,36,admin.,married,university.degree,no,no,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no

In [32]:
# List all attributes and methods of the DataFrame
dir(df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_arith_method_with_reindex',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_create_data_for_split_and_tight_to_dict',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_nocopy',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'age',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'campaign',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'contact',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'day_of_week',
 'default',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'duration',
 'education',
 'empty',
 'eq',
 'equals',
 'euribor3m',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'housing',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'job',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loan',
 'loc',
 'lt',
 'map',
 'marital',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'month',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pdays',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'poutcome',
 'pow',
 'previous',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs',
 'y']

In [33]:
print("Mean values of the first 50 records:")
print(df.head(50).mean(numeric_only=True))

Mean values of the first 50 records:
age                 43.180
duration           253.500
campaign             1.360
pdays              999.000
previous             0.000
emp.var.rate         1.100
cons.price.idx      93.994
cons.conf.idx      -36.400
euribor3m            4.857
nr.employed       5191.000
dtype: float64

In [34]:
print("Mean values of the last 50 records:")
print(df.tail(50).mean(numeric_only=True))

Mean values of the last 50 records:
age                 39.92000
duration           331.20000
campaign             1.90000
pdays              641.50000
previous             1.24000
emp.var.rate        -1.10000
cons.price.idx      94.68732
cons.conf.idx      -50.17600
euribor3m            1.02780
nr.employed       4963.60000
dtype: float64

In [35]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y'],
      dtype='object')

In [36]:
df['contact']

0       telephone
1       telephone
2       telephone
3       telephone
4       telephone
          ...
8232     cellular
8233     cellular
8234    telephone
8235     cellular
8236     cellular
Name: contact, Length: 8237, dtype: object

In [37]:
df['month'].describe()

count     8237
unique      10
top        may
freq      2751
Name: month, dtype: object

In [38]:
df['contact'].describe()

count         8237
unique           2
top       cellular
freq          5215
Name: contact, dtype: object

In [39]:
df['day_of_week'].count()

np.int64(8237)

In [40]:
df['pdays'].count()

np.int64(8237)

In [43]:
df['campaign'].mean()

np.float64(2.60471045283477)

In [44]:
df.loc[10:20,['job', 'marital', 'education', 'default']]

            job  marital            education  default
10   technician  married  professional.course  unknown
11   technician   single    university.degree       no
12  blue-collar  married             basic.9y  unknown
13  blue-collar  married             basic.4y  unknown
14       admin.  married          high.school  unknown
15       admin.  married              unknown  unknown
16   unemployed  married             basic.9y       no
17  blue-collar  married             basic.6y       no
18       admin.  married          high.school       no
19   management  married    university.degree       no
20       admin.  married              unknown       no

In [45]:
df.loc[10:29,['job', 'marital', 'education', 'default']]

             job   marital            education  default
10    technician   married  professional.course  unknown
11    technician    single    university.degree       no
12   blue-collar   married             basic.9y  unknown
13   blue-collar   married             basic.4y  unknown
14        admin.   married          high.school  unknown
15        admin.   married              unknown  unknown
16    unemployed   married             basic.9y       no
17   blue-collar   married             basic.6y       no
18        admin.   married          high.school       no
19    management   married    university.degree       no
20        admin.   married              unknown       no
21        admin.   married             basic.6y       no
22    technician   married  professional.course  unknown
23    management   married    university.degree       no
24       unknown  divorced          high.school  unknown
25   blue-collar   married             basic.4y       no
26  entrepreneur   married              unknown  unknown
27   blue-collar   married             basic.9y       no
28   blue-collar   married             basic.9y  unknown
29      services  divorced          high.school  unknown

In [46]:
df.dropna(axis=1, how='all')

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,41,blue-collar,married,unknown,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,25,services,single,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,35,blue-collar,married,basic.6y,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,46,blue-collar,married,basic.6y,unknown,yes,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8232,41,blue-collar,married,basic.9y,no,yes,no,cellular,nov,mon,...,2,999,1,failure,-1.1,94.767,-50.8,1.039,4963.6,no
8233,60,blue-collar,married,basic.4y,no,yes,no,cellular,nov,tue,...,2,4,1,success,-1.1,94.767,-50.8,1.035,4963.6,no
8234,32,admin.,married,university.degree,no,no,no,telephone,nov,wed,...,1,999,1,failure,-1.1,94.767,-50.8,1.030,4963.6,yes
8235,32,admin.,married,university.degree,no,yes,no,cellular,nov,wed,...,3,999,0,nonexistent,-1.1,94.767,-50.8,1.030,4963.6,no
8236,36,admin.,married,university.degree,no,no,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no

In [47]:
#MISSING VALUE
df.dropna(how='all')

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,41,blue-collar,married,unknown,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,25,services,single,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,35,blue-collar,married,basic.6y,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,46,blue-collar,married,basic.6y,unknown,yes,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8232,41,blue-collar,married,basic.9y,no,yes,no,cellular,nov,mon,...,2,999,1,failure,-1.1,94.767,-50.8,1.039,4963.6,no
8233,60,blue-collar,married,basic.4y,no,yes,no,cellular,nov,tue,...,2,4,1,success,-1.1,94.767,-50.8,1.035,4963.6,no
8234,32,admin.,married,university.degree,no,no,no,telephone,nov,wed,...,1,999,1,failure,-1.1,94.767,-50.8,1.030,4963.6,yes
8235,32,admin.,married,university.degree,no,yes,no,cellular,nov,wed,...,3,999,0,nonexistent,-1.1,94.767,-50.8,1.030,4963.6,no
8236,36,admin.,married,university.degree,no,no,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no

In [48]:
df.min()

age                     17
job                 admin.
marital           divorced
education         basic.4y
default                 no
housing                 no
loan                    no
contact           cellular
month                  apr
day_of_week            fri
duration                 4
campaign                 1
pdays                    0
previous                 0
poutcome           failure
emp.var.rate          -3.4
cons.price.idx      92.201
cons.conf.idx        -50.8
euribor3m            0.634
nr.employed         4963.6
y                       no
dtype: object

In [49]:
df.max()

age                      89
job                 unknown
marital             unknown
education           unknown
default             unknown
housing                 yes
loan                    yes
contact           telephone
month                   sep
day_of_week             wed
duration               4918
campaign                 43
pdays                   999
previous                  6
poutcome            success
emp.var.rate            1.4
cons.price.idx       94.767
cons.conf.idx         -26.9
euribor3m               5.0
nr.employed          5228.1
y                       yes
dtype: object

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8237 entries, 0 to 8236
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             8237 non-null   int64
 1   job             8237 non-null   object
 2   marital         8237 non-null   object
 3   education       8237 non-null   object
 4   default         8237 non-null   object
 5   housing         8237 non-null   object
 6   loan            8237 non-null   object
 7   contact         8237 non-null   object
 8   month           8237 non-null   object
 9   day_of_week     8237 non-null   object
 10  duration        8237 non-null   int64
 11  campaign        8237 non-null   int64
 12  pdays           8237 non-null   int64
 13  previous        8237 non-null   int64
 14  poutcome        8237 non-null   object
 15  emp.var.rate    8237 non-null   float64
 16  cons.price.idx  8237 non-null   float64
 17  cons.conf.idx   8237 non-null   float64
 18  euribor3m       8237 non-null   float64
 19  nr.employed     8237 non-null   float64
 20  y               8237 non-null   object
dtypes: float64(5), int64(5), object(11)
memory usage: 1.3+ MB