In [1]:
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib as mpl
import seaborn as sns
df =pd.read_csv("/content/Benefits.csv")

In [2]:
df.head()

,rownames,stateur,statemb,state,age,tenure,joblost,nwhite,school12,sex,bluecol,smsa,married,dkids,dykids,yrdispl,rr,head,ui
0,1,4.5,167,42,49,21,other,no,no,male,yes,yes,no,no,no,7,0.290631,yes,yes
1,2,10.5,251,55,26,2,slack_work,no,no,male,yes,yes,no,yes,yes,10,0.520202,yes,no
2,3,7.2,260,21,40,19,other,no,yes,female,yes,yes,yes,no,no,10,0.432490,yes,yes
3,4,5.8,245,56,51,17,slack_work,yes,no,female,yes,yes,yes,no,no,10,0.500000,no,yes
4,5,6.5,125,58,33,1,slack_work,no,yes,male,yes,yes,yes,yes,yes,4,0.390625,yes,no

In [3]:
df.head(10)

,rownames,stateur,statemb,state,age,tenure,joblost,nwhite,school12,sex,bluecol,smsa,married,dkids,dykids,yrdispl,rr,head,ui
0,1,4.5,167,42,49,21,other,no,no,male,yes,yes,no,no,no,7,0.290631,yes,yes
1,2,10.5,251,55,26,2,slack_work,no,no,male,yes,yes,no,yes,yes,10,0.520202,yes,no
2,3,7.2,260,21,40,19,other,no,yes,female,yes,yes,yes,no,no,10,0.432490,yes,yes
3,4,5.8,245,56,51,17,slack_work,yes,no,female,yes,yes,yes,no,no,10,0.500000,no,yes
4,5,6.5,125,58,33,1,slack_work,no,yes,male,yes,yes,yes,yes,yes,4,0.390625,yes,no
5,6,7.5,188,11,51,3,other,no,no,male,yes,yes,yes,no,no,10,0.482201,yes,yes
6,7,5.8,166,93,30,5,position_abolished,no,no,male,yes,yes,yes,yes,yes,6,0.334043,yes,yes
7,8,5.8,214,84,26,3,slack_work,no,no,male,yes,yes,yes,yes,yes,8,0.510989,yes,yes
8,9,7.7,213,84,54,20,other,no,no,male,yes,yes,yes,no,no,6,0.355634,yes,no
9,10,6.0,187,33,31,1,slack_work,no,no,male,yes,yes,yes,no,no,8,0.373272,yes,yes

In [4]:
df.head(20)

,rownames,stateur,statemb,state,age,tenure,joblost,nwhite,school12,sex,bluecol,smsa,married,dkids,dykids,yrdispl,rr,head,ui
0,1,4.5,167,42,49,21,other,no,no,male,yes,yes,no,no,no,7,0.290631,yes,yes
1,2,10.5,251,55,26,2,slack_work,no,no,male,yes,yes,no,yes,yes,10,0.520202,yes,no
2,3,7.2,260,21,40,19,other,no,yes,female,yes,yes,yes,no,no,10,0.432490,yes,yes
3,4,5.8,245,56,51,17,slack_work,yes,no,female,yes,yes,yes,no,no,10,0.500000,no,yes
4,5,6.5,125,58,33,1,slack_work,no,yes,male,yes,yes,yes,yes,yes,4,0.390625,yes,no
5,6,7.5,188,11,51,3,other,no,no,male,yes,yes,yes,no,no,10,0.482201,yes,yes
6,7,5.8,166,93,30,5,position_abolished,no,no,male,yes,yes,yes,yes,yes,6,0.334043,yes,yes
7,8,5.8,214,84,26,3,slack_work,no,no,male,yes,yes,yes,yes,yes,8,0.510989,yes,yes
8,9,7.7,213,84,54,20,other,no,no,male,yes,yes,yes,no,no,6,0.355634,yes,no
9,10,6.0,187,33,31,1,slack_work,no,no,male,yes,yes,yes,no,no,8,0.373272,yes,yes
10,11,7.1,206,33,56,20,slack_work,no,no,male,yes,no,yes,no,no,10,0.404467,yes,yes
11,12,10.1,132,12,54,26,other,no,no,male,yes,no,yes,yes,no,2,0.413295,yes,no
12,13,5.0,279,22,21,1,slack_work,no,no,male,yes,yes,no,no,no,9,0.598485,no,no
13,14,6.6,291,22,35,1,slack_work,yes,no,male,yes,yes,no,yes,yes,10,0.599156,no,no
14,15,7.2,166,93,23,1,slack_work,no,yes,male,yes,yes,no,no,no,4,0.393750,no,yes
15,16,7.2,260,21,41,3,other,no,no,male,yes,yes,yes,yes,no,10,0.502304,no,yes
16,17,6.4,213,84,49,12,other,no,no,male,yes,yes,yes,no,no,7,0.426374,no,yes
17,18,8.9,166,56,35,1,other,yes,no,male,yes,no,yes,no,no,2,0.473545,yes,no
18,19,5.8,245,56,40,12,other,no,no,female,yes,yes,yes,yes,no,10,0.498195,no,yes
19,20,6.1,138,54,60,30,slack_work,no,no,male,yes,yes,yes,no,no,2,0.518518,yes,no

In [5]:
df.tail()

,rownames,stateur,statemb,state,age,tenure,joblost,nwhite,school12,sex,bluecol,smsa,married,dkids,dykids,yrdispl,rr,head,ui
4872,4873,7.4,168,33,35,12,slack_work,yes,yes,female,yes,yes,no,yes,no,6,0.463557,yes,yes
4873,4874,7.0,189,74,39,5,slack_work,no,no,male,yes,yes,yes,no,no,4,0.393750,yes,yes
4874,4875,8.0,168,74,59,13,slack_work,no,no,male,yes,yes,yes,yes,no,2,0.372428,yes,yes
4875,4876,6.3,191,41,33,11,slack_work,no,no,male,yes,yes,yes,yes,yes,3,0.500000,yes,no
4876,4877,9.3,188,94,27,2,other,no,no,male,yes,yes,yes,yes,yes,7,0.495413,yes,yes

In [6]:
df.tail(6)

,rownames,stateur,statemb,state,age,tenure,joblost,nwhite,school12,sex,bluecol,smsa,married,dkids,dykids,yrdispl,rr,head,ui
4871,4872,8.6,125,59,21,2,slack_work,no,no,male,yes,yes,no,no,no,2,0.312500,yes,no
4872,4873,7.4,168,33,35,12,slack_work,yes,yes,female,yes,yes,no,yes,no,6,0.463557,yes,yes
4873,4874,7.0,189,74,39,5,slack_work,no,no,male,yes,yes,yes,no,no,4,0.393750,yes,yes
4874,4875,8.0,168,74,59,13,slack_work,no,no,male,yes,yes,yes,yes,no,2,0.372428,yes,yes
4875,4876,6.3,191,41,33,11,slack_work,no,no,male,yes,yes,yes,yes,yes,3,0.500000,yes,no
4876,4877,9.3,188,94,27,2,other,no,no,male,yes,yes,yes,yes,yes,7,0.495413,yes,yes

In [7]:
df.min(numeric_only=True)

rownames     1.00000
stateur      2.20000
statemb     84.00000
state       11.00000
age         20.00000
tenure       1.00000
yrdispl      1.00000
rr           0.03861
dtype: float64

In [8]:
df.max(numeric_only=True)

rownames    4877.000000
stateur       18.000000
statemb      293.000000
state         95.000000
age           61.000000
tenure        41.000000
yrdispl       10.000000
rr             0.691176
dtype: float64

In [9]:
df.dtypes

rownames      int64
stateur     float64
statemb       int64
state         int64
age           int64
tenure        int64
joblost      object
nwhite       object
school12     object
sex          object
bluecol      object
smsa         object
married      object
dkids        object
dykids       object
yrdispl       int64
rr          float64
head         object
ui           object
dtype: object

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4877 entries, 0 to 4876
Data columns (total 19 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   rownames  4877 non-null   int64
 1   stateur   4877 non-null   float64
 2   statemb   4877 non-null   int64
 3   state     4877 non-null   int64
 4   age       4877 non-null   int64
 5   tenure    4877 non-null   int64
 6   joblost   4877 non-null   object
 7   nwhite    4877 non-null   object
 8   school12  4877 non-null   object
 9   sex       4877 non-null   object
 10  bluecol   4877 non-null   object
 11  smsa      4877 non-null   object
 12  married   4877 non-null   object
 13  dkids     4877 non-null   object
 14  dykids    4877 non-null   object
 15  yrdispl   4877 non-null   int64
 16  rr        4877 non-null   float64
 17  head      4877 non-null   object
 18  ui        4877 non-null   object
dtypes: float64(2), int64(6), object(11)
memory usage: 724.1+ KB

In [11]:
df['age'].dtypes

dtype('int64')

In [12]:
df['yrdispl'].dtypes

dtype('int64')

In [13]:
print(df.axes)

[RangeIndex(start=0, stop=4877, step=1), Index(['rownames', 'stateur', 'statemb', 'state', 'age', 'tenure', 'joblost',
       'nwhite', 'school12', 'sex', 'bluecol', 'smsa', 'married', 'dkids',
       'dykids', 'yrdispl', 'rr', 'head', 'ui'],
      dtype='object')]

In [14]:
print(df.ndim)

2

In [15]:
print(df.size)

92663

In [16]:
print(df.values)

[[1 4.5 167 ... 0.290631 'yes' 'yes']
 [2 10.5 251 ... 0.520202 'yes' 'no']
 [3 7.2 260 ... 0.4324895 'yes' 'yes']
 ...
 [4875 8.0 168 ... 0.372428 'yes' 'yes']
 [4876 6.3 191 ... 0.5 'yes' 'no']
 [4877 9.3 188 ... 0.4954129 'yes' 'yes']]

In [17]:
print(df.shape)

(4877, 19)

In [18]:
print("Number of records:", len(df))

Number of records: 4877

In [19]:
print("Number of records:", df.shape[0])

Number of records: 4877

In [20]:
print("Number of elements:", df.size)

Number of elements: 92663

In [21]:
print("Column Names:")
print(df.columns)

Column Names:
Index(['rownames', 'stateur', 'statemb', 'state', 'age', 'tenure', 'joblost',
       'nwhite', 'school12', 'sex', 'bluecol', 'smsa', 'married', 'dkids',
       'dykids', 'yrdispl', 'rr', 'head', 'ui'],
      dtype='object')

In [22]:
print("Column Data Types:")
print(df.dtypes)

Column Data Types:
rownames      int64
stateur     float64
statemb       int64
state         int64
age           int64
tenure        int64
joblost      object
nwhite       object
school12     object
sex          object
bluecol      object
smsa         object
married      object
dkids        object
dykids       object
yrdispl       int64
rr          float64
head         object
ui           object
dtype: object

In [23]:
df.describe()

,rownames,stateur,statemb,state,age,tenure,yrdispl,rr
count,4877.000000,4877.000000,4877.000000,4877.000000,4877.000000,4877.000000,4877.000000,4877.000000
mean,2439.000000,7.511031,180.660242,52.808079,36.129998,5.664138,5.203609,0.438366
std,1408.012962,2.500579,43.241595,25.834967,10.600737,6.279938,3.095116,0.106194
min,1.000000,2.200000,84.000000,11.000000,20.000000,1.000000,1.000000,0.038610
25%,1220.000000,5.700000,150.000000,31.000000,28.000000,2.000000,2.000000,0.375212
50%,2439.000000,7.200000,177.000000,55.000000,34.000000,3.000000,5.000000,0.490446
75%,3658.000000,9.000000,205.000000,74.000000,43.000000,7.000000,8.000000,0.511574
max,4877.000000,18.000000,293.000000,95.000000,61.000000,41.000000,10.000000,0.691176

In [24]:
df.median(numeric_only=True)

rownames    2439.000000
stateur        7.200000
statemb      177.000000
state         55.000000
age           34.000000
tenure         3.000000
yrdispl        5.000000
rr             0.490446
dtype: float64

In [25]:
df.mean(numeric_only=True)

rownames    2439.000000
stateur        7.511031
statemb      180.660242
state         52.808079
age           36.129998
tenure         5.664138
yrdispl        5.203609
rr             0.438366
dtype: float64

In [26]:
df.mode(numeric_only=True)

      rownames  stateur  statemb  state   age  tenure  yrdispl   rr
0            1      7.2    166.0   93.0  30.0     1.0      1.0  0.5
1            2      NaN      NaN    NaN   NaN     NaN      NaN  NaN
2            3      NaN      NaN    NaN   NaN     NaN      NaN  NaN
3            4      NaN      NaN    NaN   NaN     NaN      NaN  NaN
4            5      NaN      NaN    NaN   NaN     NaN      NaN  NaN
...        ...      ...      ...    ...   ...     ...      ...  ...
4872      4873      NaN      NaN    NaN   NaN     NaN      NaN  NaN
4873      4874      NaN      NaN    NaN   NaN     NaN      NaN  NaN
4874      4875      NaN      NaN    NaN   NaN     NaN      NaN  NaN
4875      4876      NaN      NaN    NaN   NaN     NaN      NaN  NaN
4876      4877      NaN      NaN    NaN   NaN     NaN      NaN  NaN

[4877 rows x 8 columns]

In [27]:
df.std(numeric_only=True)

rownames    1408.012962
stateur        2.500579
statemb       43.241595
state         25.834967
age           10.600737
tenure         6.279938
yrdispl        3.095116
rr             0.106194
dtype: float64

In [28]:
df.sample(5)

,rownames,stateur,statemb,state,age,tenure,joblost,nwhite,school12,sex,bluecol,smsa,married,dkids,dykids,yrdispl,rr,head,ui
1140,1141,6.3,157,83,45,5,slack_work,no,no,male,yes,no,yes,yes,no,3,0.450276,yes,no
2139,2140,6.8,181,81,41,2,slack_work,no,yes,male,yes,yes,no,no,no,7,0.302198,yes,yes
2976,2977,10.8,175,92,36,1,slack_work,no,no,male,yes,no,yes,yes,no,2,0.514986,yes,yes
3413,3414,11.5,205,72,56,5,slack_work,no,no,male,yes,no,yes,no,no,4,0.520000,yes,no
1471,1472,9.7,166,93,36,4,other,no,no,male,yes,yes,yes,yes,yes,2,0.394444,yes,yes

In [29]:
df.sample(20)

,rownames,stateur,statemb,state,age,tenure,joblost,nwhite,school12,sex,bluecol,smsa,married,dkids,dykids,yrdispl,rr,head,ui
493,494,8.9,147,31,43,20,slack_work,no,no,male,yes,no,no,no,no,4,0.245000,yes,no
518,519,7.2,166,93,20,1,slack_work,no,no,male,yes,yes,no,yes,yes,4,0.393333,no,no
2812,2813,11.8,205,23,33,14,other,no,no,male,yes,yes,yes,yes,yes,2,0.444668,yes,no
3296,3297,10.0,205,72,35,3,slack_work,yes,no,male,yes,yes,yes,no,no,3,0.518732,yes,yes
4861,4862,5.7,106,46,30,10,other,no,yes,male,yes,no,yes,yes,yes,1,0.235060,yes,yes
1988,1989,4.6,168,16,41,18,other,no,no,male,yes,yes,yes,no,no,3,0.498392,yes,no
789,790,5.0,279,22,41,1,slack_work,no,yes,male,yes,yes,no,no,no,9,0.600000,no,yes
4650,4651,8.1,147,31,30,1,other,no,no,male,yes,yes,yes,yes,yes,5,0.418605,yes,yes
3516,3517,9.0,282,14,40,3,slack_work,no,no,male,yes,yes,no,yes,no,10,0.500000,yes,no
1866,1867,8.5,211,92,35,12,slack_work,no,yes,male,yes,no,yes,yes,yes,5,0.391304,yes,yes
2349,2350,5.3,96,32,36,1,slack_work,no,yes,male,yes,yes,no,no,no,9,0.300380,yes,no
2906,2907,5.1,166,93,48,8,other,no,no,female,yes,yes,yes,no,no,8,0.397436,no,yes
2227,2228,8.0,168,74,46,28,other,no,no,female,yes,yes,yes,no,no,2,0.519824,no,yes
448,449,6.9,291,23,36,1,slack_work,no,no,male,yes,yes,no,no,no,10,0.518987,yes,no
4741,4742,8.0,143,42,24,2,slack_work,no,no,male,yes,yes,no,no,no,4,0.510714,no,no
943,944,12.4,90,63,60,25,other,no,no,female,yes,yes,yes,no,no,1,0.276243,no,yes
3689,3690,9.4,147,31,52,17,other,no,no,female,yes,yes,yes,no,no,3,0.367150,no,yes
4251,4252,7.5,210,93,21,3,slack_work,no,no,male,yes,yes,yes,yes,yes,10,0.394737,yes,no
4578,4579,5.0,200,59,31,2,other,no,no,male,yes,yes,no,no,no,7,0.500000,yes,no
4796,4797,3.3,236,14,39,7,other,no,no,female,yes,yes,yes,yes,no,7,0.500000,no,yes

In [30]:
# Remove rows with missing values
df.dropna()

,rownames,stateur,statemb,state,age,tenure,joblost,nwhite,school12,sex,bluecol,smsa,married,dkids,dykids,yrdispl,rr,head,ui
0,1,4.5,167,42,49,21,other,no,no,male,yes,yes,no,no,no,7,0.290631,yes,yes
1,2,10.5,251,55,26,2,slack_work,no,no,male,yes,yes,no,yes,yes,10,0.520202,yes,no
2,3,7.2,260,21,40,19,other,no,yes,female,yes,yes,yes,no,no,10,0.432490,yes,yes
3,4,5.8,245,56,51,17,slack_work,yes,no,female,yes,yes,yes,no,no,10,0.500000,no,yes
4,5,6.5,125,58,33,1,slack_work,no,yes,male,yes,yes,yes,yes,yes,4,0.390625,yes,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4872,4873,7.4,168,33,35,12,slack_work,yes,yes,female,yes,yes,no,yes,no,6,0.463557,yes,yes
4873,4874,7.0,189,74,39,5,slack_work,no,no,male,yes,yes,yes,no,no,4,0.393750,yes,yes
4874,4875,8.0,168,74,59,13,slack_work,no,no,male,yes,yes,yes,yes,no,2,0.372428,yes,yes
4875,4876,6.3,191,41,33,11,slack_work,no,no,male,yes,yes,yes,yes,yes,3,0.500000,yes,no
4876,4877,9.3,188,94,27,2,other,no,no,male,yes,yes,yes,yes,yes,7,0.495413,yes,yes

In [31]:
# List all attributes and methods of the DataFrame
dir(df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_arith_method_with_reindex',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_create_data_for_split_and_tight_to_dict',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_nocopy',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'age',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bluecol',
 'bool',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dkids',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'dykids',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'joblost',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'married',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'nwhite',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rownames',
 'rpow',
 'rr',
 'rsub',
 'rtruediv',
 'sample',
 'school12',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'sex',
 'shape',
 'shift',
 'size',
 'skew',
 'smsa',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'state',
 'statemb',
 'stateur',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'tenure',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'ui',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs',
 'yrdispl']

In [32]:
print("Mean values of the first 50 records:")
print(df.head(50).mean(numeric_only=True))

Mean values of the first 50 records:
rownames     25.500000
stateur       7.474000
statemb     191.880000
state        52.440000
age          36.940000
tenure        6.900000
yrdispl       6.300000
rr            0.452947
dtype: float64

In [33]:
print("Mean values of the last 50 records:")
print(df.tail(50).mean(numeric_only=True))

Mean values of the last 50 records:
rownames    4852.500000
stateur        7.756000
statemb      189.100000
state         54.840000
age           34.140000
tenure         5.400000
yrdispl        5.300000
rr             0.451454
dtype: float64

In [34]:
df.columns

Index(['rownames', 'stateur', 'statemb', 'state', 'age', 'tenure', 'joblost',
       'nwhite', 'school12', 'sex', 'bluecol', 'smsa', 'married', 'dkids',
       'dykids', 'yrdispl', 'rr', 'head', 'ui'],
      dtype='object')

In [35]:
df['age']

0       49
1       26
2       40
3       51
4       33
        ..
4872    35
4873    39
4874    59
4875    33
4876    27
Name: age, Length: 4877, dtype: int64

In [39]:
df['rownames'].describe()

count    4877.000000
mean     2439.000000
std      1408.012962
min         1.000000
25%      1220.000000
50%      2439.000000
75%      3658.000000
max      4877.000000
Name: rownames, dtype: float64

In [43]:
df['nwhite'].describe()

count     4877
unique       2
top         no
freq      4159
Name: nwhite, dtype: object

In [42]:
df['rownames'].count()

np.int64(4877)

In [41]:
df['nwhite'].count()

np.int64(4877)

In [38]:
df['rownames'].mean()

np.float64(2439.0)

In [36]:
df.columns

Index(['rownames', 'stateur', 'statemb', 'state', 'age', 'tenure', 'joblost',
       'nwhite', 'school12', 'sex', 'bluecol', 'smsa', 'married', 'dkids',
       'dykids', 'yrdispl', 'rr', 'head', 'ui'],
      dtype='object')

In [44]:
df[10:20]

,rownames,stateur,statemb,state,age,tenure,joblost,nwhite,school12,sex,bluecol,smsa,married,dkids,dykids,yrdispl,rr,head,ui
10,11,7.1,206,33,56,20,slack_work,no,no,male,yes,no,yes,no,no,10,0.404467,yes,yes
11,12,10.1,132,12,54,26,other,no,no,male,yes,no,yes,yes,no,2,0.413295,yes,no
12,13,5.0,279,22,21,1,slack_work,no,no,male,yes,yes,no,no,no,9,0.598485,no,no
13,14,6.6,291,22,35,1,slack_work,yes,no,male,yes,yes,no,yes,yes,10,0.599156,no,no
14,15,7.2,166,93,23,1,slack_work,no,yes,male,yes,yes,no,no,no,4,0.393750,no,yes
15,16,7.2,260,21,41,3,other,no,no,male,yes,yes,yes,yes,no,10,0.502304,no,yes
16,17,6.4,213,84,49,12,other,no,no,male,yes,yes,yes,no,no,7,0.426374,no,yes
17,18,8.9,166,56,35,1,other,yes,no,male,yes,no,yes,no,no,2,0.473545,yes,no
18,19,5.8,245,56,40,12,other,no,no,female,yes,yes,yes,yes,no,10,0.498195,no,yes
19,20,6.1,138,54,60,30,slack_work,no,no,male,yes,yes,yes,no,no,2,0.518518,yes,no

In [45]:
df[10:30]

,rownames,stateur,statemb,state,age,tenure,joblost,nwhite,school12,sex,bluecol,smsa,married,dkids,dykids,yrdispl,rr,head,ui
10,11,7.1,206,33,56,20,slack_work,no,no,male,yes,no,yes,no,no,10,0.404467,yes,yes
11,12,10.1,132,12,54,26,other,no,no,male,yes,no,yes,yes,no,2,0.413295,yes,no
12,13,5.0,279,22,21,1,slack_work,no,no,male,yes,yes,no,no,no,9,0.598485,no,no
13,14,6.6,291,22,35,1,slack_work,yes,no,male,yes,yes,no,yes,yes,10,0.599156,no,no
14,15,7.2,166,93,23,1,slack_work,no,yes,male,yes,yes,no,no,no,4,0.393750,no,yes
15,16,7.2,260,21,41,3,other,no,no,male,yes,yes,yes,yes,no,10,0.502304,no,yes
16,17,6.4,213,84,49,12,other,no,no,male,yes,yes,yes,no,no,7,0.426374,no,yes
17,18,8.9,166,56,35,1,other,yes,no,male,yes,no,yes,no,no,2,0.473545,yes,no
18,19,5.8,245,56,40,12,other,no,no,female,yes,yes,yes,yes,no,10,0.498195,no,yes
19,20,6.1,138,54,60,30,slack_work,no,no,male,yes,yes,yes,no,no,2,0.518518,yes,no
20,21,7.2,260,21,42,4,slack_work,yes,no,female,yes,yes,yes,no,no,10,0.500000,no,yes
21,22,18.0,211,55,48,3,other,no,no,male,yes,no,yes,no,no,2,0.255892,yes,yes
22,23,4.6,168,16,41,3,other,no,no,male,yes,yes,yes,no,no,3,0.335907,yes,yes
23,24,9.0,192,83,29,5,position_abolished,no,no,male,yes,no,yes,yes,yes,5,0.262204,yes,no
24,25,5.9,185,44,59,5,slack_work,no,no,male,yes,no,yes,no,no,4,0.500000,yes,yes
25,26,7.4,197,73,32,3,slack_work,no,no,male,yes,no,yes,yes,yes,6,0.438967,yes,yes
26,27,11.4,168,33,22,3,slack_work,no,no,male,yes,yes,no,yes,no,2,0.504065,no,no
27,28,5.5,150,43,25,3,slack_work,yes,no,male,yes,yes,yes,yes,yes,8,0.575221,no,no
28,29,4.8,179,44,36,3,other,no,yes,male,yes,no,yes,yes,yes,7,0.401099,yes,yes
29,30,6.3,150,59,41,20,other,no,no,male,yes,yes,no,yes,no,3,0.399485,no,yes

In [46]:
df.loc[10:20,['rownames', 'stateur', 'statemb']]

    rownames  stateur  statemb
10        11      7.1      206
11        12     10.1      132
12        13      5.0      279
13        14      6.6      291
14        15      7.2      166
15        16      7.2      260
16        17      6.4      213
17        18      8.9      166
18        19      5.8      245
19        20      6.1      138
20        21      7.2      260

In [48]:
df.loc[10:20,['nwhite', 'school12', 'sex']]

   nwhite school12     sex
10     no       no    male
11     no       no    male
12     no       no    male
13    yes       no    male
14     no      yes    male
15     no       no    male
16     no       no    male
17    yes       no    male
18     no       no  female
19     no       no    male
20    yes       no  female

In [49]:
#MISSING VALUE
df.dropna(how='all')

,rownames,stateur,statemb,state,age,tenure,joblost,nwhite,school12,sex,bluecol,smsa,married,dkids,dykids,yrdispl,rr,head,ui
0,1,4.5,167,42,49,21,other,no,no,male,yes,yes,no,no,no,7,0.290631,yes,yes
1,2,10.5,251,55,26,2,slack_work,no,no,male,yes,yes,no,yes,yes,10,0.520202,yes,no
2,3,7.2,260,21,40,19,other,no,yes,female,yes,yes,yes,no,no,10,0.432490,yes,yes
3,4,5.8,245,56,51,17,slack_work,yes,no,female,yes,yes,yes,no,no,10,0.500000,no,yes
4,5,6.5,125,58,33,1,slack_work,no,yes,male,yes,yes,yes,yes,yes,4,0.390625,yes,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4872,4873,7.4,168,33,35,12,slack_work,yes,yes,female,yes,yes,no,yes,no,6,0.463557,yes,yes
4873,4874,7.0,189,74,39,5,slack_work,no,no,male,yes,yes,yes,no,no,4,0.393750,yes,yes
4874,4875,8.0,168,74,59,13,slack_work,no,no,male,yes,yes,yes,yes,no,2,0.372428,yes,yes
4875,4876,6.3,191,41,33,11,slack_work,no,no,male,yes,yes,yes,yes,yes,3,0.500000,yes,no
4876,4877,9.3,188,94,27,2,other,no,no,male,yes,yes,yes,yes,yes,7,0.495413,yes,yes

In [50]:
df.dropna(axis=1, how='all')

,rownames,stateur,statemb,state,age,tenure,joblost,nwhite,school12,sex,bluecol,smsa,married,dkids,dykids,yrdispl,rr,head,ui
0,1,4.5,167,42,49,21,other,no,no,male,yes,yes,no,no,no,7,0.290631,yes,yes
1,2,10.5,251,55,26,2,slack_work,no,no,male,yes,yes,no,yes,yes,10,0.520202,yes,no
2,3,7.2,260,21,40,19,other,no,yes,female,yes,yes,yes,no,no,10,0.432490,yes,yes
3,4,5.8,245,56,51,17,slack_work,yes,no,female,yes,yes,yes,no,no,10,0.500000,no,yes
4,5,6.5,125,58,33,1,slack_work,no,yes,male,yes,yes,yes,yes,yes,4,0.390625,yes,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4872,4873,7.4,168,33,35,12,slack_work,yes,yes,female,yes,yes,no,yes,no,6,0.463557,yes,yes
4873,4874,7.0,189,74,39,5,slack_work,no,no,male,yes,yes,yes,no,no,4,0.393750,yes,yes
4874,4875,8.0,168,74,59,13,slack_work,no,no,male,yes,yes,yes,yes,no,2,0.372428,yes,yes
4875,4876,6.3,191,41,33,11,slack_work,no,no,male,yes,yes,yes,yes,yes,3,0.500000,yes,no
4876,4877,9.3,188,94,27,2,other,no,no,male,yes,yes,yes,yes,yes,7,0.495413,yes,yes

In [51]:
df.min()

rownames          1
stateur         2.2
statemb          84
state            11
age              20
tenure            1
joblost       other
nwhite           no
school12         no
sex          female
bluecol         yes
smsa             no
married          no
dkids            no
dykids           no
yrdispl           1
rr          0.03861
head             no
ui               no
dtype: object

In [52]:
df.max()

rownames          4877
stateur           18.0
statemb            293
state               95
age                 61
tenure              41
joblost     slack_work
nwhite             yes
school12           yes
sex               male
bluecol            yes
smsa               yes
married            yes
dkids              yes
dykids             yes
yrdispl             10
rr            0.691176
head               yes
ui                 yes
dtype: object

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4877 entries, 0 to 4876
Data columns (total 19 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   rownames  4877 non-null   int64
 1   stateur   4877 non-null   float64
 2   statemb   4877 non-null   int64
 3   state     4877 non-null   int64
 4   age       4877 non-null   int64
 5   tenure    4877 non-null   int64
 6   joblost   4877 non-null   object
 7   nwhite    4877 non-null   object
 8   school12  4877 non-null   object
 9   sex       4877 non-null   object
 10  bluecol   4877 non-null   object
 11  smsa      4877 non-null   object
 12  married   4877 non-null   object
 13  dkids     4877 non-null   object
 14  dykids    4877 non-null   object
 15  yrdispl   4877 non-null   int64
 16  rr        4877 non-null   float64
 17  head      4877 non-null   object
 18  ui        4877 non-null   object
dtypes: float64(2), int64(6), object(11)
memory usage: 724.1+ KB