In [1]:
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib as mpl
import seaborn as sns
df =pd.read_csv("/content/BEPS.csv")

In [2]:
df.head()

,rownames,vote,age,economic.cond.national,economic.cond.household,Blair,Hague,Kennedy,Europe,political.knowledge,gender
0,1,Liberal Democrat,43,3,3,4,1,4,2,2,female
1,2,Labour,36,4,4,4,4,4,5,2,male
2,3,Labour,35,4,4,5,2,3,3,2,male
3,4,Labour,24,4,2,2,1,3,4,0,female
4,5,Labour,41,2,2,1,1,4,6,2,male

In [3]:
df.head(10)

,rownames,vote,age,economic.cond.national,economic.cond.household,Blair,Hague,Kennedy,Europe,political.knowledge,gender
0,1,Liberal Democrat,43,3,3,4,1,4,2,2,female
1,2,Labour,36,4,4,4,4,4,5,2,male
2,3,Labour,35,4,4,5,2,3,3,2,male
3,4,Labour,24,4,2,2,1,3,4,0,female
4,5,Labour,41,2,2,1,1,4,6,2,male
5,6,Labour,47,3,4,4,4,2,4,2,male
6,7,Liberal Democrat,57,2,2,4,4,2,11,2,male
7,8,Labour,77,3,4,4,1,4,1,0,male
8,9,Labour,39,3,3,4,4,4,11,0,female
9,10,Labour,70,3,2,5,1,1,11,2,male

In [4]:
df.head(20)

,rownames,vote,age,economic.cond.national,economic.cond.household,Blair,Hague,Kennedy,Europe,political.knowledge,gender
0,1,Liberal Democrat,43,3,3,4,1,4,2,2,female
1,2,Labour,36,4,4,4,4,4,5,2,male
2,3,Labour,35,4,4,5,2,3,3,2,male
3,4,Labour,24,4,2,2,1,3,4,0,female
4,5,Labour,41,2,2,1,1,4,6,2,male
5,6,Labour,47,3,4,4,4,2,4,2,male
6,7,Liberal Democrat,57,2,2,4,4,2,11,2,male
7,8,Labour,77,3,4,4,1,4,1,0,male
8,9,Labour,39,3,3,4,4,4,11,0,female
9,10,Labour,70,3,2,5,1,1,11,2,male
10,11,Labour,39,3,3,1,2,1,7,0,female
11,12,Labour,66,4,3,4,4,4,9,2,male
12,13,Labour,59,4,4,4,1,4,10,2,female
13,14,Labour,66,3,3,2,5,4,8,0,female
14,15,Labour,77,2,3,2,1,4,11,2,female
15,16,Labour,51,4,4,4,4,4,5,0,male
16,17,Labour,43,2,4,1,4,3,8,0,female
17,18,Labour,41,4,4,5,4,2,7,2,female
18,19,Labour,79,3,3,4,2,4,1,0,male
19,20,Labour,37,3,1,1,1,4,5,2,female

In [5]:
df.tail()

,rownames,vote,age,economic.cond.national,economic.cond.household,Blair,Hague,Kennedy,Europe,political.knowledge,gender
1520,1521,Conservative,67,5,3,2,4,4,11,3,male
1521,1522,Conservative,73,2,2,4,4,4,8,2,male
1522,1523,Labour,37,3,3,5,4,4,2,2,male
1523,1524,Conservative,61,3,3,1,4,1,11,2,male
1524,1525,Conservative,74,2,3,2,4,4,11,0,female

In [6]:
df.tail(6)

,rownames,vote,age,economic.cond.national,economic.cond.household,Blair,Hague,Kennedy,Europe,political.knowledge,gender
1519,1520,Conservative,35,3,4,4,2,4,8,2,male
1520,1521,Conservative,67,5,3,2,4,4,11,3,male
1521,1522,Conservative,73,2,2,4,4,4,8,2,male
1522,1523,Labour,37,3,3,5,4,4,2,2,male
1523,1524,Conservative,61,3,3,1,4,1,11,2,male
1524,1525,Conservative,74,2,3,2,4,4,11,0,female

In [7]:
df.min(numeric_only=True)

rownames                    1
age                        24
economic.cond.national      1
economic.cond.household     1
Blair                       1
Hague                       1
Kennedy                     1
Europe                      1
political.knowledge         0
dtype: int64

In [8]:
df.max(numeric_only=True)

rownames                   1525
age                          93
economic.cond.national        5
economic.cond.household       5
Blair                         5
Hague                         5
Kennedy                       5
Europe                       11
political.knowledge           3
dtype: int64

In [9]:
df.dtypes

rownames                    int64
vote                       object
age                         int64
economic.cond.national      int64
economic.cond.household     int64
Blair                       int64
Hague                       int64
Kennedy                     int64
Europe                      int64
political.knowledge         int64
gender                     object
dtype: object

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1525 entries, 0 to 1524
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   rownames                 1525 non-null   int64
 1   vote                     1525 non-null   object
 2   age                      1525 non-null   int64
 3   economic.cond.national   1525 non-null   int64
 4   economic.cond.household  1525 non-null   int64
 5   Blair                    1525 non-null   int64
 6   Hague                    1525 non-null   int64
 7   Kennedy                  1525 non-null   int64
 8   Europe                   1525 non-null   int64
 9   political.knowledge      1525 non-null   int64
 10  gender                   1525 non-null   object
dtypes: int64(9), object(2)
memory usage: 131.2+ KB

In [11]:
df['age'].dtypes

dtype('int64')

In [12]:
df['economic.cond.national'].dtypes

dtype('int64')

In [13]:
print(df.axes)

[RangeIndex(start=0, stop=1525, step=1), Index(['rownames', 'vote', 'age', 'economic.cond.national',
       'economic.cond.household', 'Blair', 'Hague', 'Kennedy', 'Europe',
       'political.knowledge', 'gender'],
      dtype='object')]

In [14]:
print(df.size)

16775

In [15]:
print(df.ndim)

2

In [16]:
print(df.shape)

(1525, 11)

In [17]:
print(df.values)

[[1 'Liberal Democrat' 43 ... 2 2 'female']
 [2 'Labour' 36 ... 5 2 'male']
 [3 'Labour' 35 ... 3 2 'male']
 ...
 [1523 'Labour' 37 ... 2 2 'male']
 [1524 'Conservative' 61 ... 11 2 'male']
 [1525 'Conservative' 74 ... 11 0 'female']]

In [18]:
print("Number of records:", len(df))

Number of records: 1525

In [19]:
print("Number of records:", df.shape[0])

Number of records: 1525

In [20]:
print("Number of elements:", df.size)

Number of elements: 16775

In [21]:
print("Column Names:")
print(df.columns)

Column Names:
Index(['rownames', 'vote', 'age', 'economic.cond.national',
       'economic.cond.household', 'Blair', 'Hague', 'Kennedy', 'Europe',
       'political.knowledge', 'gender'],
      dtype='object')

In [22]:
print("Column Data Types:")
print(df.dtypes)

Column Data Types:
rownames                    int64
vote                       object
age                         int64
economic.cond.national      int64
economic.cond.household     int64
Blair                       int64
Hague                       int64
Kennedy                     int64
Europe                      int64
political.knowledge         int64
gender                     object
dtype: object

In [23]:
df.describe()

,rownames,age,economic.cond.national,economic.cond.household,Blair,Hague,Kennedy,Europe,political.knowledge
count,1525.000000,1525.000000,1525.000000,1525.000000,1525.000000,1525.000000,1525.000000,1525.000000,1525.000000
mean,763.000000,54.182295,3.245902,3.140328,3.334426,2.746885,3.135082,6.728525,1.542295
std,440.373894,15.711209,0.880969,0.929951,1.174824,1.230703,1.081997,3.297538,1.083315
min,1.000000,24.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,382.000000,41.000000,3.000000,3.000000,2.000000,2.000000,2.000000,4.000000,0.000000
50%,763.000000,53.000000,3.000000,3.000000,4.000000,2.000000,3.000000,6.000000,2.000000
75%,1144.000000,67.000000,4.000000,4.000000,4.000000,4.000000,4.000000,10.000000,2.000000
max,1525.000000,93.000000,5.000000,5.000000,5.000000,5.000000,5.000000,11.000000,3.000000

In [24]:
df.median(numeric_only=True)

rownames                   763.0
age                         53.0
economic.cond.national       3.0
economic.cond.household      3.0
Blair                        4.0
Hague                        2.0
Kennedy                      3.0
Europe                       6.0
political.knowledge          2.0
dtype: float64

In [25]:
df.mean(numeric_only=True)

rownames                   763.000000
age                         54.182295
economic.cond.national       3.245902
economic.cond.household      3.140328
Blair                        3.334426
Hague                        2.746885
Kennedy                      3.135082
Europe                       6.728525
political.knowledge          1.542295
dtype: float64

In [26]:
df.mode(numeric_only=True)

,rownames,age,economic.cond.national,economic.cond.household,Blair,Hague,Kennedy,Europe,political.knowledge
0,1,37.0,3.0,3.0,4.0,2.0,4.0,11.0,2.0
1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
1520,1521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1521,1522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1522,1523,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1523,1524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1524,1525,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
df.std(numeric_only=True)

rownames                   440.373894
age                         15.711209
economic.cond.national       0.880969
economic.cond.household      0.929951
Blair                        1.174824
Hague                        1.230703
Kennedy                      1.081997
Europe                       3.297538
political.knowledge          1.083315
dtype: float64

In [28]:
df.sample(5)

,rownames,vote,age,economic.cond.national,economic.cond.household,Blair,Hague,Kennedy,Europe,political.knowledge,gender
688,689,Conservative,50,2,4,2,5,4,11,2,female
277,278,Conservative,63,2,4,2,4,2,10,3,female
1095,1096,Labour,40,4,4,4,2,2,2,2,female
432,433,Labour,65,4,3,4,4,4,1,3,female
455,456,Labour,70,5,4,4,2,4,6,3,female

In [29]:
df.sample(20)

,rownames,vote,age,economic.cond.national,economic.cond.household,Blair,Hague,Kennedy,Europe,political.knowledge,gender
1167,1168,Conservative,24,4,4,2,1,3,4,2,female
1375,1376,Labour,50,4,3,4,1,3,11,0,female
306,307,Conservative,70,2,2,4,2,2,10,3,male
777,778,Labour,60,5,4,4,2,4,2,2,male
696,697,Labour,78,5,4,4,2,4,1,2,female
1131,1132,Labour,36,3,3,1,5,4,7,3,female
377,378,Conservative,29,4,5,4,4,1,8,2,male
40,41,Labour,42,4,4,4,2,2,6,0,female
807,808,Labour,77,4,4,5,2,4,5,2,male
1473,1474,Labour,54,3,3,4,1,2,5,0,female
1498,1499,Labour,65,3,3,2,2,3,1,3,female
1449,1450,Liberal Democrat,47,4,4,4,2,4,5,0,female
103,104,Conservative,70,2,3,2,4,4,8,2,female
525,526,Labour,32,4,4,4,4,4,2,2,female
1097,1098,Labour,54,3,3,4,2,2,1,2,female
433,434,Conservative,48,3,3,2,4,3,11,2,female
483,484,Liberal Democrat,43,2,3,4,2,4,2,3,male
1053,1054,Conservative,69,4,4,1,5,1,11,1,male
181,182,Conservative,90,4,4,2,4,4,11,3,female
1023,1024,Liberal Democrat,72,3,3,2,2,4,11,2,male

In [30]:
# Remove rows with missing values
df.dropna()

,rownames,vote,age,economic.cond.national,economic.cond.household,Blair,Hague,Kennedy,Europe,political.knowledge,gender
0,1,Liberal Democrat,43,3,3,4,1,4,2,2,female
1,2,Labour,36,4,4,4,4,4,5,2,male
2,3,Labour,35,4,4,5,2,3,3,2,male
3,4,Labour,24,4,2,2,1,3,4,0,female
4,5,Labour,41,2,2,1,1,4,6,2,male
...,...,...,...,...,...,...,...,...,...,...,...
1520,1521,Conservative,67,5,3,2,4,4,11,3,male
1521,1522,Conservative,73,2,2,4,4,4,8,2,male
1522,1523,Labour,37,3,3,5,4,4,2,2,male
1523,1524,Conservative,61,3,3,1,4,1,11,2,male
1524,1525,Conservative,74,2,3,2,4,4,11,0,female

In [31]:
# List all attributes and methods of the DataFrame
dir(df)

['Blair',
 'Europe',
 'Hague',
 'Kennedy',
 'T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_arith_method_with_reindex',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_create_data_for_split_and_tight_to_dict',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_nocopy',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'age',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'gender',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rownames',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'vote',
 'where',
 'xs']

In [32]:
print("Mean values of the first 50 records:")
print(df.head(50).mean(numeric_only=True))

Mean values of the first 50 records:
rownames                   25.50
age                        52.22
economic.cond.national      3.00
economic.cond.household     2.82
Blair                       3.44
Hague                       2.70
Kennedy                     3.04
Europe                      5.56
political.knowledge         1.42
dtype: float64

In [33]:
print("Mean values of the last 50 records:")
print(df.tail(50).mean(numeric_only=True))

Mean values of the last 50 records:
rownames                   1500.50
age                          58.40
economic.cond.national        3.10
economic.cond.household       2.72
Blair                         3.36
Hague                         2.82
Kennedy                       3.20
Europe                        6.56
political.knowledge           1.80
dtype: float64

In [34]:
df.columns

Index(['rownames', 'vote', 'age', 'economic.cond.national',
       'economic.cond.household', 'Blair', 'Hague', 'Kennedy', 'Europe',
       'political.knowledge', 'gender'],
      dtype='object')

In [35]:
df['age']

0       43
1       36
2       35
3       24
4       41
        ..
1520    67
1521    73
1522    37
1523    61
1524    74
Name: age, Length: 1525, dtype: int64

In [36]:
df['vote'].describe()

count       1525
unique         3
top       Labour
freq         720
Name: vote, dtype: object

In [37]:
df['economic.cond.household'].describe()

count    1525.000000
mean        3.140328
std         0.929951
min         1.000000
25%         3.000000
50%         3.000000
75%         4.000000
max         5.000000
Name: economic.cond.household, dtype: float64

In [38]:
df['Blair'].count()

np.int64(1525)

In [39]:
df['Europe'].count()

np.int64(1525)

In [40]:
df['rownames'].mean()

np.float64(763.0)

In [41]:
df['age'].mean()

np.float64(54.18229508196721)

In [42]:
df[10:30]

,rownames,vote,age,economic.cond.national,economic.cond.household,Blair,Hague,Kennedy,Europe,political.knowledge,gender
10,11,Labour,39,3,3,1,2,1,7,0,female
11,12,Labour,66,4,3,4,4,4,9,2,male
12,13,Labour,59,4,4,4,1,4,10,2,female
13,14,Labour,66,3,3,2,5,4,8,0,female
14,15,Labour,77,2,3,2,1,4,11,2,female
15,16,Labour,51,4,4,4,4,4,5,0,male
16,17,Labour,43,2,4,1,4,3,8,0,female
17,18,Labour,41,4,4,5,4,2,7,2,female
18,19,Labour,79,3,3,4,2,4,1,0,male
19,20,Labour,37,3,1,1,1,4,5,2,female
20,21,Labour,38,3,3,4,4,2,7,0,male
21,22,Liberal Democrat,53,2,1,2,4,4,5,2,male
22,23,Labour,59,3,3,4,2,2,1,2,male
23,24,Conservative,44,2,4,4,4,4,9,2,male
24,25,Conservative,60,3,2,4,4,4,2,2,female
25,26,Labour,51,3,3,4,3,3,6,0,female
26,27,Conservative,56,2,2,2,4,4,9,2,female
27,28,Labour,51,3,2,4,2,4,2,2,female
28,29,Labour,44,3,3,4,2,4,1,2,male
29,30,Labour,61,4,3,5,1,2,1,2,male

In [43]:
df[10:20]

,rownames,vote,age,economic.cond.national,economic.cond.household,Blair,Hague,Kennedy,Europe,political.knowledge,gender
10,11,Labour,39,3,3,1,2,1,7,0,female
11,12,Labour,66,4,3,4,4,4,9,2,male
12,13,Labour,59,4,4,4,1,4,10,2,female
13,14,Labour,66,3,3,2,5,4,8,0,female
14,15,Labour,77,2,3,2,1,4,11,2,female
15,16,Labour,51,4,4,4,4,4,5,0,male
16,17,Labour,43,2,4,1,4,3,8,0,female
17,18,Labour,41,4,4,5,4,2,7,2,female
18,19,Labour,79,3,3,4,2,4,1,0,male
19,20,Labour,37,3,1,1,1,4,5,2,female

In [44]:
df.loc[10:20,['rownames', 'vote', 'age', 'economic.cond.national']]

    rownames    vote  age  economic.cond.national
10        11  Labour   39                       3
11        12  Labour   66                       4
12        13  Labour   59                       4
13        14  Labour   66                       3
14        15  Labour   77                       2
15        16  Labour   51                       4
16        17  Labour   43                       2
17        18  Labour   41                       4
18        19  Labour   79                       3
19        20  Labour   37                       3
20        21  Labour   38                       3

In [45]:
df.loc[10:20,['political.knowledge', 'gender']]

    political.knowledge  gender
10                    0  female
11                    2    male
12                    2  female
13                    0  female
14                    2  female
15                    0    male
16                    0  female
17                    2  female
18                    0    male
19                    2  female
20                    0    male

In [46]:
#MISSING VALUE
df.dropna(how='all')

,rownames,vote,age,economic.cond.national,economic.cond.household,Blair,Hague,Kennedy,Europe,political.knowledge,gender
0,1,Liberal Democrat,43,3,3,4,1,4,2,2,female
1,2,Labour,36,4,4,4,4,4,5,2,male
2,3,Labour,35,4,4,5,2,3,3,2,male
3,4,Labour,24,4,2,2,1,3,4,0,female
4,5,Labour,41,2,2,1,1,4,6,2,male
...,...,...,...,...,...,...,...,...,...,...,...
1520,1521,Conservative,67,5,3,2,4,4,11,3,male
1521,1522,Conservative,73,2,2,4,4,4,8,2,male
1522,1523,Labour,37,3,3,5,4,4,2,2,male
1523,1524,Conservative,61,3,3,1,4,1,11,2,male
1524,1525,Conservative,74,2,3,2,4,4,11,0,female

In [47]:
df.dropna(axis=1, how='all')

,rownames,vote,age,economic.cond.national,economic.cond.household,Blair,Hague,Kennedy,Europe,political.knowledge,gender
0,1,Liberal Democrat,43,3,3,4,1,4,2,2,female
1,2,Labour,36,4,4,4,4,4,5,2,male
2,3,Labour,35,4,4,5,2,3,3,2,male
3,4,Labour,24,4,2,2,1,3,4,0,female
4,5,Labour,41,2,2,1,1,4,6,2,male
...,...,...,...,...,...,...,...,...,...,...,...
1520,1521,Conservative,67,5,3,2,4,4,11,3,male
1521,1522,Conservative,73,2,2,4,4,4,8,2,male
1522,1523,Labour,37,3,3,5,4,4,2,2,male
1523,1524,Conservative,61,3,3,1,4,1,11,2,male
1524,1525,Conservative,74,2,3,2,4,4,11,0,female

In [48]:
df.min()

rownames                              1
vote                       Conservative
age                                  24
economic.cond.national                1
economic.cond.household               1
Blair                                 1
Hague                                 1
Kennedy                               1
Europe                                1
political.knowledge                   0
gender                           female
dtype: object

In [49]:
df.max()

rownames                               1525
vote                       Liberal Democrat
age                                      93
economic.cond.national                    5
economic.cond.household                   5
Blair                                     5
Hague                                     5
Kennedy                                   5
Europe                                   11
political.knowledge                       3
gender                                 male
dtype: object

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1525 entries, 0 to 1524
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   rownames                 1525 non-null   int64
 1   vote                     1525 non-null   object
 2   age                      1525 non-null   int64
 3   economic.cond.national   1525 non-null   int64
 4   economic.cond.household  1525 non-null   int64
 5   Blair                    1525 non-null   int64
 6   Hague                    1525 non-null   int64
 7   Kennedy                  1525 non-null   int64
 8   Europe                   1525 non-null   int64
 9   political.knowledge      1525 non-null   int64
 10  gender                   1525 non-null   object
dtypes: int64(9), object(2)
memory usage: 131.2+ KB