In [1]:
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib as mpl
import seaborn as sns
df =pd.read_csv("/content/bodyPerformance.csv")

In [2]:
df.head()

,age,gender,height_cm,weight_kg,body fat_%,diastolic,systolic,gripForce,sit and bend forward_cm,sit-ups counts,broad jump_cm,class
0,27,M,172.3,75.24,21.3,80.0,130.0,54.9,18.4,60.0,217.0,C
1,25,M,165.0,55.80,15.7,77.0,126.0,36.4,16.3,53.0,229.0,A
2,31,M,179.6,78.00,20.1,92.0,152.0,44.8,12.0,49.0,181.0,C
3,32,M,174.5,71.10,18.4,76.0,147.0,41.4,15.2,53.0,219.0,B
4,28,M,173.8,67.70,17.1,70.0,127.0,43.5,27.1,45.0,217.0,B

In [3]:
df.head(10)

,age,gender,height_cm,weight_kg,body fat_%,diastolic,systolic,gripForce,sit and bend forward_cm,sit-ups counts,broad jump_cm,class
0,27,M,172.3,75.24,21.3,80.0,130.0,54.9,18.4,60.0,217.0,C
1,25,M,165.0,55.80,15.7,77.0,126.0,36.4,16.3,53.0,229.0,A
2,31,M,179.6,78.00,20.1,92.0,152.0,44.8,12.0,49.0,181.0,C
3,32,M,174.5,71.10,18.4,76.0,147.0,41.4,15.2,53.0,219.0,B
4,28,M,173.8,67.70,17.1,70.0,127.0,43.5,27.1,45.0,217.0,B
5,36,F,165.4,55.40,22.0,64.0,119.0,23.8,21.0,27.0,153.0,B
6,42,F,164.5,63.70,32.2,72.0,135.0,22.7,0.8,18.0,146.0,D
7,33,M,174.9,77.20,36.9,84.0,137.0,45.9,12.3,42.0,234.0,B
8,54,M,166.8,67.50,27.6,85.0,165.0,40.4,18.6,34.0,148.0,C
9,28,M,185.0,84.60,14.4,81.0,156.0,57.9,12.1,55.0,213.0,B

In [4]:
df.head(20)

,age,gender,height_cm,weight_kg,body fat_%,diastolic,systolic,gripForce,sit and bend forward_cm,sit-ups counts,broad jump_cm,class
0,27,M,172.3,75.24,21.3,80.0,130.0,54.9,18.4,60.0,217.0,C
1,25,M,165.0,55.80,15.7,77.0,126.0,36.4,16.3,53.0,229.0,A
2,31,M,179.6,78.00,20.1,92.0,152.0,44.8,12.0,49.0,181.0,C
3,32,M,174.5,71.10,18.4,76.0,147.0,41.4,15.2,53.0,219.0,B
4,28,M,173.8,67.70,17.1,70.0,127.0,43.5,27.1,45.0,217.0,B
5,36,F,165.4,55.40,22.0,64.0,119.0,23.8,21.0,27.0,153.0,B
6,42,F,164.5,63.70,32.2,72.0,135.0,22.7,0.8,18.0,146.0,D
7,33,M,174.9,77.20,36.9,84.0,137.0,45.9,12.3,42.0,234.0,B
8,54,M,166.8,67.50,27.6,85.0,165.0,40.4,18.6,34.0,148.0,C
9,28,M,185.0,84.60,14.4,81.0,156.0,57.9,12.1,55.0,213.0,B
10,42,M,169.2,65.40,19.3,63.0,110.0,43.5,16.0,68.0,211.0,A
11,57,F,153.0,49.00,20.9,69.0,106.0,21.5,30.0,0.0,90.0,D
12,27,F,156.0,53.90,35.5,69.0,116.0,23.1,13.1,28.0,144.0,C
13,22,M,175.7,67.90,11.3,71.0,103.0,52.5,19.2,55.0,232.0,?
14,24,M,181.0,84.40,20.4,80.0,120.0,48.9,7.2,54.0,213.0,C
15,45,F,159.0,63.10,30.9,93.0,144.0,34.1,19.0,30.0,155.0,A
16,25,F,164.2,66.60,30.2,82.0,120.0,25.7,22.9,39.0,178.0,C
17,26,M,179.9,71.50,9.7,64.0,135.0,59.6,17.8,61.0,239.0,A
18,26,M,169.2,70.60,21.0,63.0,129.0,41.3,15.1,53.0,225.0,B
19,21,F,162.7,47.20,18.9,78.0,133.0,25.4,20.5,36.0,137.0,B

In [5]:
df.tail()

,age,gender,height_cm,weight_kg,body fat_%,diastolic,systolic,gripForce,sit and bend forward_cm,sit-ups counts,broad jump_cm,class
13388,25,M,172.1,71.8,16.2,74.0,141.0,35.8,17.4,47.0,198.0,C
13389,21,M,179.7,63.9,12.1,74.0,128.0,33.0,1.1,48.0,167.0,D
13390,39,M,177.2,80.5,20.1,78.0,132.0,63.5,16.4,45.0,229.0,A
13391,64,F,146.1,57.7,40.4,68.0,121.0,19.3,9.2,0.0,75.0,D
13392,34,M,164.0,66.1,19.5,82.0,150.0,35.9,7.1,51.0,180.0,C

In [6]:
df.tail(6)

,age,gender,height_cm,weight_kg,body fat_%,diastolic,systolic,gripForce,sit and bend forward_cm,sit-ups counts,broad jump_cm,class
13387,39,M,174.4,70.8,24.3,78.0,132.0,41.6,12.0,44.0,168.0,B
13388,25,M,172.1,71.8,16.2,74.0,141.0,35.8,17.4,47.0,198.0,C
13389,21,M,179.7,63.9,12.1,74.0,128.0,33.0,1.1,48.0,167.0,D
13390,39,M,177.2,80.5,20.1,78.0,132.0,63.5,16.4,45.0,229.0,A
13391,64,F,146.1,57.7,40.4,68.0,121.0,19.3,9.2,0.0,75.0,D
13392,34,M,164.0,66.1,19.5,82.0,150.0,35.9,7.1,51.0,180.0,C

In [7]:
df.min(numeric_only=True)

age                         21.0
height_cm                  125.0
weight_kg                   26.3
body fat_%                   3.0
diastolic                    0.0
systolic                     0.0
gripForce                    0.0
sit and bend forward_cm    -25.0
sit-ups counts               0.0
broad jump_cm                0.0
dtype: float64

In [8]:
df.max(numeric_only=True)

age                         64.0
height_cm                  193.8
weight_kg                  138.1
body fat_%                  78.4
diastolic                  156.2
systolic                   201.0
gripForce                   70.5
sit and bend forward_cm    213.0
sit-ups counts              80.0
broad jump_cm              303.0
dtype: float64

In [9]:
df.dtypes

age                          int64
gender                      object
height_cm                  float64
weight_kg                  float64
body fat_%                 float64
diastolic                  float64
systolic                   float64
gripForce                  float64
sit and bend forward_cm    float64
sit-ups counts             float64
broad jump_cm              float64
class                       object
dtype: object

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13393 entries, 0 to 13392
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      13393 non-null  int64
 1   gender                   13392 non-null  object
 2   height_cm                13393 non-null  float64
 3   weight_kg                13393 non-null  float64
 4   body fat_%               13392 non-null  float64
 5   diastolic                13393 non-null  float64
 6   systolic                 13392 non-null  float64
 7   gripForce                13393 non-null  float64
 8   sit and bend forward_cm  13393 non-null  float64
 9   sit-ups counts           13393 non-null  float64
 10  broad jump_cm            13393 non-null  float64
 11  class                    13393 non-null  object
dtypes: float64(9), int64(1), object(2)
memory usage: 1.2+ MB

In [11]:
df['age'].dtypes

dtype('int64')

In [12]:
df['gender'].dtypes

dtype('O')

In [13]:
print(df.axes)

[RangeIndex(start=0, stop=13393, step=1), Index(['age', 'gender', 'height_cm', 'weight_kg', 'body fat_%', 'diastolic',
       'systolic', 'gripForce', 'sit and bend forward_cm', 'sit-ups counts',
       'broad jump_cm', 'class'],
      dtype='object')]

In [14]:
print(df.ndim)

2

In [15]:
print(df.shape)

(13393, 12)

In [16]:
print(df.values)

[[27 'M' 172.3 ... 60.0 217.0 'C']
 [25 'M' 165.0 ... 53.0 229.0 'A']
 [31 'M' 179.6 ... 49.0 181.0 'C']
 ...
 [39 'M' 177.2 ... 45.0 229.0 'A']
 [64 'F' 146.1 ... 0.0 75.0 'D']
 [34 'M' 164.0 ... 51.0 180.0 'C']]

In [17]:
print("Number of records:", len(df))

Number of records: 13393

In [18]:
print("Number of records:", df.shape[0])

Number of records: 13393

In [19]:
print("Number of elements:", df.size)

Number of elements: 160716

In [20]:
print("Column Names:")
print(df.columns)

Column Names:
Index(['age', 'gender', 'height_cm', 'weight_kg', 'body fat_%', 'diastolic',
       'systolic', 'gripForce', 'sit and bend forward_cm', 'sit-ups counts',
       'broad jump_cm', 'class'],
      dtype='object')

In [21]:
print("Column Data Types:")
print(df.dtypes)

Column Data Types:
age                          int64
gender                      object
height_cm                  float64
weight_kg                  float64
body fat_%                 float64
diastolic                  float64
systolic                   float64
gripForce                  float64
sit and bend forward_cm    float64
sit-ups counts             float64
broad jump_cm              float64
class                       object
dtype: object

In [22]:
df.describe()

,age,height_cm,weight_kg,body fat_%,diastolic,systolic,gripForce,sit and bend forward_cm,sit-ups counts,broad jump_cm
count,13393.000000,13393.000000,13393.000000,13392.000000,13393.000000,13392.000000,13393.000000,13393.000000,13393.000000,13393.000000
mean,36.775106,168.559807,67.447316,23.240258,78.796842,130.233938,36.963877,15.209268,39.771224,190.129627
std,13.625639,8.426583,11.949666,7.257107,10.742033,14.714152,10.624864,8.456677,14.276698,39.868000
min,21.000000,125.000000,26.300000,3.000000,0.000000,0.000000,0.000000,-25.000000,0.000000,0.000000
25%,25.000000,162.400000,58.200000,18.000000,71.000000,120.000000,27.500000,10.900000,30.000000,162.000000
50%,32.000000,169.200000,67.400000,22.800000,79.000000,130.000000,37.900000,16.200000,41.000000,193.000000
75%,48.000000,174.800000,75.300000,28.000000,86.000000,141.000000,45.200000,20.700000,50.000000,221.000000
max,64.000000,193.800000,138.100000,78.400000,156.200000,201.000000,70.500000,213.000000,80.000000,303.000000

In [23]:
df.median(numeric_only=True)

age                         32.0
height_cm                  169.2
weight_kg                   67.4
body fat_%                  22.8
diastolic                   79.0
systolic                   130.0
gripForce                   37.9
sit and bend forward_cm     16.2
sit-ups counts              41.0
broad jump_cm              193.0
dtype: float64

In [24]:
df.mean(numeric_only=True)

age                         36.775106
height_cm                  168.559807
weight_kg                   67.447316
body fat_%                  23.240258
diastolic                   78.796842
systolic                   130.233938
gripForce                   36.963877
sit and bend forward_cm     15.209268
sit-ups counts              39.771224
broad jump_cm              190.129627
dtype: float64

In [25]:
df.mode(numeric_only=True)

,age,height_cm,weight_kg,body fat_%,diastolic,systolic,gripForce,sit and bend forward_cm,sit-ups counts,broad jump_cm
0,21,170.0,70.5,23.1,80.0,120.0,43.1,20.0,45.0,211.0

In [26]:
df.std(numeric_only=True)

age                        13.625639
height_cm                   8.426583
weight_kg                  11.949666
body fat_%                  7.257107
diastolic                  10.742033
systolic                   14.714152
gripForce                  10.624864
sit and bend forward_cm     8.456677
sit-ups counts             14.276698
broad jump_cm              39.868000
dtype: float64

In [27]:
df.sample(5)

,age,gender,height_cm,weight_kg,body fat_%,diastolic,systolic,gripForce,sit and bend forward_cm,sit-ups counts,broad jump_cm,class
399,59,M,165.7,57.6,13.6,60.0,124.0,33.0,13.5,41.0,186.0,A
5080,45,F,157.4,56.4,27.4,79.0,128.0,28.8,19.4,36.0,158.0,A
1254,47,M,174.9,76.3,23.2,95.0,133.0,42.7,11.9,31.0,211.0,C
17,26,M,179.9,71.5,9.7,64.0,135.0,59.6,17.8,61.0,239.0,A
4343,22,F,167.3,55.3,21.3,89.0,134.0,35.1,24.7,40.0,176.0,A

In [28]:
df.sample(20)

,age,gender,height_cm,weight_kg,body fat_%,diastolic,systolic,gripForce,sit and bend forward_cm,sit-ups counts,broad jump_cm,class
233,56,F,149.0,46.70,23.2,95.0,157.0,25.0,28.0,41.0,186.0,A
9551,24,M,187.9,80.80,9.5,72.0,141.0,56.2,24.9,58.0,230.0,A
4160,47,F,155.6,66.80,36.1,97.0,142.0,26.6,-1.3,18.0,143.0,D
2454,21,F,158.5,48.80,22.5,61.0,102.0,29.1,21.7,36.0,169.0,A
7298,43,F,157.0,54.00,23.2,70.0,114.0,21.6,14.5,39.0,140.0,C
2385,36,M,177.6,88.50,24.7,91.0,139.0,43.4,6.3,32.0,178.0,D
7526,56,M,164.0,73.80,24.3,95.0,129.0,48.7,18.6,40.0,188.0,B
733,26,F,170.4,66.80,24.3,85.0,126.0,24.3,16.2,48.0,153.0,C
13300,22,M,167.6,72.70,18.6,75.0,123.0,53.5,22.1,67.0,260.0,A
4619,64,M,155.7,61.40,22.1,98.0,137.0,31.4,14.8,32.0,180.0,B
6179,21,F,170.7,61.10,30.9,80.0,131.0,22.1,22.6,27.0,160.0,C
252,24,M,167.5,65.66,19.1,98.0,154.0,45.3,18.3,44.0,241.0,C
8784,25,M,174.7,77.50,10.6,79.0,146.0,59.4,19.3,56.0,231.0,B
10263,57,M,165.7,63.90,25.0,82.0,134.0,37.8,13.6,40.0,183.0,C
1704,48,M,176.9,78.10,17.8,88.0,141.0,48.7,14.2,46.0,237.0,A
7250,32,M,173.2,71.00,14.7,71.0,103.0,54.2,18.4,55.0,244.0,A
12024,61,M,169.2,86.30,24.4,88.0,159.0,43.8,13.6,27.0,158.0,D
9177,62,F,161.2,74.00,37.3,83.0,124.0,22.0,16.4,19.0,113.0,D
8614,26,F,161.8,73.40,37.4,65.0,126.0,23.9,11.2,10.0,135.0,D
1810,24,M,177.5,76.40,24.1,86.0,159.0,39.7,11.6,48.0,181.0,D

In [29]:
# Remove rows with missing values
df.dropna()

,age,gender,height_cm,weight_kg,body fat_%,diastolic,systolic,gripForce,sit and bend forward_cm,sit-ups counts,broad jump_cm,class
0,27,M,172.3,75.24,21.3,80.0,130.0,54.9,18.4,60.0,217.0,C
1,25,M,165.0,55.80,15.7,77.0,126.0,36.4,16.3,53.0,229.0,A
2,31,M,179.6,78.00,20.1,92.0,152.0,44.8,12.0,49.0,181.0,C
3,32,M,174.5,71.10,18.4,76.0,147.0,41.4,15.2,53.0,219.0,B
4,28,M,173.8,67.70,17.1,70.0,127.0,43.5,27.1,45.0,217.0,B
...,...,...,...,...,...,...,...,...,...,...,...,...
13388,25,M,172.1,71.80,16.2,74.0,141.0,35.8,17.4,47.0,198.0,C
13389,21,M,179.7,63.90,12.1,74.0,128.0,33.0,1.1,48.0,167.0,D
13390,39,M,177.2,80.50,20.1,78.0,132.0,63.5,16.4,45.0,229.0,A
13391,64,F,146.1,57.70,40.4,68.0,121.0,19.3,9.2,0.0,75.0,D
13392,34,M,164.0,66.10,19.5,82.0,150.0,35.9,7.1,51.0,180.0,C

In [30]:
print("Mean values of the first 50 records:")
print(df.head(50).mean(numeric_only=True))

Mean values of the first 50 records:
age                         35.2000
height_cm                  169.3820
weight_kg                   68.4932
body fat_%                  22.7920
diastolic                   77.9800
systolic                   130.1000
gripForce                   38.3860
sit and bend forward_cm     14.9400
sit-ups counts              43.0800
broad jump_cm              191.4600
dtype: float64

In [31]:
print("Mean values of the last 50 records:")
print(df.tail(50).mean(numeric_only=True))

Mean values of the last 50 records:
age                         39.4200
height_cm                  168.4580
weight_kg                   66.6988
body fat_%                  22.2180
diastolic                   77.6200
systolic                   130.0200
gripForce                   37.5920
sit and bend forward_cm     13.0360
sit-ups counts              38.9200
broad jump_cm              185.4400
dtype: float64

In [32]:
df.columns

Index(['age', 'gender', 'height_cm', 'weight_kg', 'body fat_%', 'diastolic',
       'systolic', 'gripForce', 'sit and bend forward_cm', 'sit-ups counts',
       'broad jump_cm', 'class'],
      dtype='object')

In [33]:
df['age']

0        27
1        25
2        31
3        32
4        28
         ..
13388    25
13389    21
13390    39
13391    64
13392    34
Name: age, Length: 13393, dtype: int64

In [34]:
df['diastolic'].describe()

count    13393.000000
mean        78.796842
std         10.742033
min          0.000000
25%         71.000000
50%         79.000000
75%         86.000000
max        156.200000
Name: diastolic, dtype: float64

In [35]:
df['gender'].describe()

count     13392
unique        2
top           M
freq       8466
Name: gender, dtype: object

In [36]:
df['sit-ups counts'].count()

np.int64(13393)

In [37]:
df['weight_kg'].count()

np.int64(13393)

In [38]:
df['age'].mean()

np.float64(36.77510639886508)

In [39]:
df['body fat_%'].mean()

np.float64(23.24025755577957)

In [40]:
df[10:30]

,age,gender,height_cm,weight_kg,body fat_%,diastolic,systolic,gripForce,sit and bend forward_cm,sit-ups counts,broad jump_cm,class
10,42,M,169.2,65.40,19.3,63.0,110.0,43.5,16.0,68.0,211.0,A
11,57,F,153.0,49.00,20.9,69.0,106.0,21.5,30.0,0.0,90.0,D
12,27,F,156.0,53.90,35.5,69.0,116.0,23.1,13.1,28.0,144.0,C
13,22,M,175.7,67.90,11.3,71.0,103.0,52.5,19.2,55.0,232.0,?
14,24,M,181.0,84.40,20.4,80.0,120.0,48.9,7.2,54.0,213.0,C
15,45,F,159.0,63.10,30.9,93.0,144.0,34.1,19.0,30.0,155.0,A
16,25,F,164.2,66.60,30.2,82.0,120.0,25.7,22.9,39.0,178.0,C
17,26,M,179.9,71.50,9.7,64.0,135.0,59.6,17.8,61.0,239.0,A
18,26,M,169.2,70.60,21.0,63.0,129.0,41.3,15.1,53.0,225.0,B
19,21,F,162.7,47.20,18.9,78.0,133.0,25.4,20.5,36.0,137.0,B
20,25,F,161.7,63.36,31.3,89.0,128.0,25.0,10.7,39.0,160.0,C
21,59,F,155.9,62.70,30.2,76.0,143.0,36.8,29.1,25.0,122.0,A
22,38,M,166.7,67.30,23.2,70.0,111.0,26.1,19.7,62.0,215.0,D
23,44,M,170.0,63.30,12.9,65.0,115.0,44.5,11.6,49.0,196.0,B
24,23,F,164.1,59.40,29.6,91.0,126.0,24.6,27.5,32.0,169.0,C
25,62,M,169.0,70.70,30.5,96.0,146.0,39.3,4.0,43.0,131.0,C
26,47,F,158.3,53.50,29.2,70.0,117.0,25.9,8.1,32.0,151.0,D
27,48,M,175.8,84.50,31.4,83.0,125.0,33.8,3.7,24.0,211.0,D
28,36,M,176.0,81.30,24.5,81.0,139.0,46.2,8.1,54.0,232.0,C
29,50,F,159.8,57.10,24.4,63.0,103.0,30.8,24.4,30.0,143.0,A

In [41]:
df[10:20]

,age,gender,height_cm,weight_kg,body fat_%,diastolic,systolic,gripForce,sit and bend forward_cm,sit-ups counts,broad jump_cm,class
10,42,M,169.2,65.4,19.3,63.0,110.0,43.5,16.0,68.0,211.0,A
11,57,F,153.0,49.0,20.9,69.0,106.0,21.5,30.0,0.0,90.0,D
12,27,F,156.0,53.9,35.5,69.0,116.0,23.1,13.1,28.0,144.0,C
13,22,M,175.7,67.9,11.3,71.0,103.0,52.5,19.2,55.0,232.0,?
14,24,M,181.0,84.4,20.4,80.0,120.0,48.9,7.2,54.0,213.0,C
15,45,F,159.0,63.1,30.9,93.0,144.0,34.1,19.0,30.0,155.0,A
16,25,F,164.2,66.6,30.2,82.0,120.0,25.7,22.9,39.0,178.0,C
17,26,M,179.9,71.5,9.7,64.0,135.0,59.6,17.8,61.0,239.0,A
18,26,M,169.2,70.6,21.0,63.0,129.0,41.3,15.1,53.0,225.0,B
19,21,F,162.7,47.2,18.9,78.0,133.0,25.4,20.5,36.0,137.0,B

In [42]:

df.loc[10:20,['age', 'gender', 'height_cm', 'weight_kg']]

    age gender  height_cm  weight_kg
10   42      M      169.2      65.40
11   57      F      153.0      49.00
12   27      F      156.0      53.90
13   22      M      175.7      67.90
14   24      M      181.0      84.40
15   45      F      159.0      63.10
16   25      F      164.2      66.60
17   26      M      179.9      71.50
18   26      M      169.2      70.60
19   21      F      162.7      47.20
20   25      F      161.7      63.36

In [43]:
df.loc[10:20,['systolic', 'gripForce', 'sit and bend forward_cm']]

    systolic  gripForce  sit and bend forward_cm
10     110.0       43.5                     16.0
11     106.0       21.5                     30.0
12     116.0       23.1                     13.1
13     103.0       52.5                     19.2
14     120.0       48.9                      7.2
15     144.0       34.1                     19.0
16     120.0       25.7                     22.9
17     135.0       59.6                     17.8
18     129.0       41.3                     15.1
19     133.0       25.4                     20.5
20     128.0       25.0                     10.7

In [44]:
#MISSING VALUE
df.dropna(how='all')

,age,gender,height_cm,weight_kg,body fat_%,diastolic,systolic,gripForce,sit and bend forward_cm,sit-ups counts,broad jump_cm,class
0,27,M,172.3,75.24,21.3,80.0,130.0,54.9,18.4,60.0,217.0,C
1,25,M,165.0,55.80,15.7,77.0,126.0,36.4,16.3,53.0,229.0,A
2,31,M,179.6,78.00,20.1,92.0,152.0,44.8,12.0,49.0,181.0,C
3,32,M,174.5,71.10,18.4,76.0,147.0,41.4,15.2,53.0,219.0,B
4,28,M,173.8,67.70,17.1,70.0,127.0,43.5,27.1,45.0,217.0,B
...,...,...,...,...,...,...,...,...,...,...,...,...
13388,25,M,172.1,71.80,16.2,74.0,141.0,35.8,17.4,47.0,198.0,C
13389,21,M,179.7,63.90,12.1,74.0,128.0,33.0,1.1,48.0,167.0,D
13390,39,M,177.2,80.50,20.1,78.0,132.0,63.5,16.4,45.0,229.0,A
13391,64,F,146.1,57.70,40.4,68.0,121.0,19.3,9.2,0.0,75.0,D
13392,34,M,164.0,66.10,19.5,82.0,150.0,35.9,7.1,51.0,180.0,C

In [45]:
df.dropna(axis=1, how='all')

,age,gender,height_cm,weight_kg,body fat_%,diastolic,systolic,gripForce,sit and bend forward_cm,sit-ups counts,broad jump_cm,class
0,27,M,172.3,75.24,21.3,80.0,130.0,54.9,18.4,60.0,217.0,C
1,25,M,165.0,55.80,15.7,77.0,126.0,36.4,16.3,53.0,229.0,A
2,31,M,179.6,78.00,20.1,92.0,152.0,44.8,12.0,49.0,181.0,C
3,32,M,174.5,71.10,18.4,76.0,147.0,41.4,15.2,53.0,219.0,B
4,28,M,173.8,67.70,17.1,70.0,127.0,43.5,27.1,45.0,217.0,B
...,...,...,...,...,...,...,...,...,...,...,...,...
13388,25,M,172.1,71.80,16.2,74.0,141.0,35.8,17.4,47.0,198.0,C
13389,21,M,179.7,63.90,12.1,74.0,128.0,33.0,1.1,48.0,167.0,D
13390,39,M,177.2,80.50,20.1,78.0,132.0,63.5,16.4,45.0,229.0,A
13391,64,F,146.1,57.70,40.4,68.0,121.0,19.3,9.2,0.0,75.0,D
13392,34,M,164.0,66.10,19.5,82.0,150.0,35.9,7.1,51.0,180.0,C

In [48]:
df.max(numeric_only=True)

age                         64.0
height_cm                  193.8
weight_kg                  138.1
body fat_%                  78.4
diastolic                  156.2
systolic                   201.0
gripForce                   70.5
sit and bend forward_cm    213.0
sit-ups counts              80.0
broad jump_cm              303.0
dtype: float64

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13393 entries, 0 to 13392
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      13393 non-null  int64
 1   gender                   13392 non-null  object
 2   height_cm                13393 non-null  float64
 3   weight_kg                13393 non-null  float64
 4   body fat_%               13392 non-null  float64
 5   diastolic                13393 non-null  float64
 6   systolic                 13392 non-null  float64
 7   gripForce                13393 non-null  float64
 8   sit and bend forward_cm  13393 non-null  float64
 9   sit-ups counts           13393 non-null  float64
 10  broad jump_cm            13393 non-null  float64
 11  class                    13393 non-null  object
dtypes: float64(9), int64(1), object(2)
memory usage: 1.2+ MB