In [3]:
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib as mpl
import seaborn as sns
df =pd.read_csv("/content/Caravan.csv")

In [6]:
df.head()

,rownames,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,...,APERSONG,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,Purchase
0,1,33,1,3,2,8,0,5,1,3,...,0,0,0,1,0,0,0,0,0,No
1,2,37,1,2,2,8,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
2,3,37,1,2,2,8,0,4,2,4,...,0,0,0,1,0,0,0,0,0,No
3,4,9,1,3,3,3,2,3,2,4,...,0,0,0,1,0,0,0,0,0,No
4,5,40,1,4,2,10,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No

In [7]:
df.head(10)

,rownames,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,...,APERSONG,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,Purchase
0,1,33,1,3,2,8,0,5,1,3,...,0,0,0,1,0,0,0,0,0,No
1,2,37,1,2,2,8,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
2,3,37,1,2,2,8,0,4,2,4,...,0,0,0,1,0,0,0,0,0,No
3,4,9,1,3,3,3,2,3,2,4,...,0,0,0,1,0,0,0,0,0,No
4,5,40,1,4,2,10,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
5,6,23,1,2,1,5,0,5,0,5,...,0,0,0,0,0,0,0,0,0,No
6,7,39,2,3,2,9,2,2,0,5,...,0,0,0,0,0,0,0,0,0,No
7,8,33,1,2,3,8,0,7,0,2,...,0,0,0,0,0,0,0,0,0,No
8,9,33,1,2,4,8,0,1,3,6,...,0,0,0,0,0,0,0,0,0,No
9,10,11,2,3,3,3,3,5,0,2,...,0,0,0,1,0,0,0,0,0,No

In [8]:
df.head(20)

,rownames,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,...,APERSONG,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,Purchase
0,1,33,1,3,2,8,0,5,1,3,...,0,0,0,1,0,0,0,0,0,No
1,2,37,1,2,2,8,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
2,3,37,1,2,2,8,0,4,2,4,...,0,0,0,1,0,0,0,0,0,No
3,4,9,1,3,3,3,2,3,2,4,...,0,0,0,1,0,0,0,0,0,No
4,5,40,1,4,2,10,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
5,6,23,1,2,1,5,0,5,0,5,...,0,0,0,0,0,0,0,0,0,No
6,7,39,2,3,2,9,2,2,0,5,...,0,0,0,0,0,0,0,0,0,No
7,8,33,1,2,3,8,0,7,0,2,...,0,0,0,0,0,0,0,0,0,No
8,9,33,1,2,4,8,0,1,3,6,...,0,0,0,0,0,0,0,0,0,No
9,10,11,2,3,3,3,3,5,0,2,...,0,0,0,1,0,0,0,0,0,No
10,11,10,1,4,3,3,1,4,1,4,...,0,0,0,0,0,0,0,0,0,No
11,12,9,1,3,3,3,1,3,2,4,...,0,0,0,1,0,0,0,0,0,No
12,13,33,1,2,3,8,1,4,1,4,...,0,0,0,0,0,0,0,0,0,No
13,14,41,1,3,3,10,0,5,0,4,...,0,0,0,0,0,0,0,0,0,No
14,15,23,1,1,2,5,0,6,1,2,...,0,0,0,1,0,0,0,0,0,No
15,16,33,1,2,3,8,0,7,0,2,...,0,0,0,1,0,0,0,0,0,No
16,17,38,1,2,3,9,0,6,0,3,...,0,0,0,0,0,0,0,0,0,No
17,18,22,2,3,3,5,0,5,0,4,...,0,0,0,1,0,0,0,0,0,No
18,19,13,1,4,2,3,2,4,0,3,...,0,0,0,1,0,0,0,0,0,No
19,20,31,1,2,4,7,0,2,0,7,...,0,0,0,0,0,0,0,0,0,No

In [9]:
df.tail()

,rownames,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,...,APERSONG,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,Purchase
5817,5818,36,1,1,2,8,0,6,1,2,...,0,0,0,1,0,0,0,0,0,No
5818,5819,35,1,4,4,8,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
5819,5820,33,1,3,4,8,0,6,0,3,...,0,0,0,1,0,0,0,0,0,Yes
5820,5821,34,1,3,2,8,0,7,0,2,...,0,0,0,0,0,0,0,0,0,No
5821,5822,33,1,3,3,8,0,6,1,2,...,0,0,0,0,0,0,0,0,0,No

In [10]:

df.tail(6)

,rownames,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,...,APERSONG,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,Purchase
5816,5817,3,1,2,3,1,0,6,0,3,...,0,0,0,0,0,0,0,0,0,No
5817,5818,36,1,1,2,8,0,6,1,2,...,0,0,0,1,0,0,0,0,0,No
5818,5819,35,1,4,4,8,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
5819,5820,33,1,3,4,8,0,6,0,3,...,0,0,0,1,0,0,0,0,0,Yes
5820,5821,34,1,3,2,8,0,7,0,2,...,0,0,0,0,0,0,0,0,0,No
5821,5822,33,1,3,3,8,0,6,1,2,...,0,0,0,0,0,0,0,0,0,No

In [11]:
df.min(numeric_only=True)

rownames    1
MOSTYPE     1
MAANTHUI    1
MGEMOMV     1
MGEMLEEF    1
           ..
AZEILPL     0
APLEZIER    0
AFIETS      0
AINBOED     0
ABYSTAND    0
Length: 86, dtype: int64

In [12]:
df.max(numeric_only=True)

rownames    5822
MOSTYPE       41
MAANTHUI      10
MGEMOMV        5
MGEMLEEF       6
            ...
AZEILPL        1
APLEZIER       2
AFIETS         3
AINBOED        2
ABYSTAND       2
Length: 86, dtype: int64

In [13]:
df.dtypes

rownames     int64
MOSTYPE      int64
MAANTHUI     int64
MGEMOMV      int64
MGEMLEEF     int64
             ...
APLEZIER     int64
AFIETS       int64
AINBOED      int64
ABYSTAND     int64
Purchase    object
Length: 87, dtype: object

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5822 entries, 0 to 5821
Data columns (total 87 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   rownames  5822 non-null   int64
 1   MOSTYPE   5822 non-null   int64
 2   MAANTHUI  5822 non-null   int64
 3   MGEMOMV   5822 non-null   int64
 4   MGEMLEEF  5822 non-null   int64
 5   MOSHOOFD  5822 non-null   int64
 6   MGODRK    5822 non-null   int64
 7   MGODPR    5822 non-null   int64
 8   MGODOV    5822 non-null   int64
 9   MGODGE    5822 non-null   int64
 10  MRELGE    5822 non-null   int64
 11  MRELSA    5822 non-null   int64
 12  MRELOV    5822 non-null   int64
 13  MFALLEEN  5822 non-null   int64
 14  MFGEKIND  5822 non-null   int64
 15  MFWEKIND  5822 non-null   int64
 16  MOPLHOOG  5822 non-null   int64
 17  MOPLMIDD  5822 non-null   int64
 18  MOPLLAAG  5822 non-null   int64
 19  MBERHOOG  5822 non-null   int64
 20  MBERZELF  5822 non-null   int64
 21  MBERBOER  5822 non-null   int64
 22  MBERMIDD  5822 non-null   int64
 23  MBERARBG  5822 non-null   int64
 24  MBERARBO  5822 non-null   int64
 25  MSKA      5822 non-null   int64
 26  MSKB1     5822 non-null   int64
 27  MSKB2     5822 non-null   int64
 28  MSKC      5822 non-null   int64
 29  MSKD      5822 non-null   int64
 30  MHHUUR    5822 non-null   int64
 31  MHKOOP    5822 non-null   int64
 32  MAUT1     5822 non-null   int64
 33  MAUT2     5822 non-null   int64
 34  MAUT0     5822 non-null   int64
 35  MZFONDS   5822 non-null   int64
 36  MZPART    5822 non-null   int64
 37  MINKM30   5822 non-null   int64
 38  MINK3045  5822 non-null   int64
 39  MINK4575  5822 non-null   int64
 40  MINK7512  5822 non-null   int64
 41  MINK123M  5822 non-null   int64
 42  MINKGEM   5822 non-null   int64
 43  MKOOPKLA  5822 non-null   int64
 44  PWAPART   5822 non-null   int64
 45  PWABEDR   5822 non-null   int64
 46  PWALAND   5822 non-null   int64
 47  PPERSAUT  5822 non-null   int64
 48  PBESAUT   5822 non-null   int64
 49  PMOTSCO   5822 non-null   int64
 50  PVRAAUT   5822 non-null   int64
 51  PAANHANG  5822 non-null   int64
 52  PTRACTOR  5822 non-null   int64
 53  PWERKT    5822 non-null   int64
 54  PBROM     5822 non-null   int64
 55  PLEVEN    5822 non-null   int64
 56  PPERSONG  5822 non-null   int64
 57  PGEZONG   5822 non-null   int64
 58  PWAOREG   5822 non-null   int64
 59  PBRAND    5822 non-null   int64
 60  PZEILPL   5822 non-null   int64
 61  PPLEZIER  5822 non-null   int64
 62  PFIETS    5822 non-null   int64
 63  PINBOED   5822 non-null   int64
 64  PBYSTAND  5822 non-null   int64
 65  AWAPART   5822 non-null   int64
 66  AWABEDR   5822 non-null   int64
 67  AWALAND   5822 non-null   int64
 68  APERSAUT  5822 non-null   int64
 69  ABESAUT   5822 non-null   int64
 70  AMOTSCO   5822 non-null   int64
 71  AVRAAUT   5822 non-null   int64
 72  AAANHANG  5822 non-null   int64
 73  ATRACTOR  5822 non-null   int64
 74  AWERKT    5822 non-null   int64
 75  ABROM     5822 non-null   int64
 76  ALEVEN    5822 non-null   int64
 77  APERSONG  5822 non-null   int64
 78  AGEZONG   5822 non-null   int64
 79  AWAOREG   5822 non-null   int64
 80  ABRAND    5822 non-null   int64
 81  AZEILPL   5822 non-null   int64
 82  APLEZIER  5822 non-null   int64
 83  AFIETS    5822 non-null   int64
 84  AINBOED   5822 non-null   int64
 85  ABYSTAND  5822 non-null   int64
 86  Purchase  5822 non-null   object
dtypes: int64(86), object(1)
memory usage: 3.9+ MB

In [15]:
df['AAANHANG'].dtypes

dtype('int64')

In [16]:
df['MINK7512'].dtypes

dtype('int64')

In [17]:
print(df.axes)

[RangeIndex(start=0, stop=5822, step=1), Index(['rownames', 'MOSTYPE', 'MAANTHUI', 'MGEMOMV', 'MGEMLEEF', 'MOSHOOFD',
       'MGODRK', 'MGODPR', 'MGODOV', 'MGODGE', 'MRELGE', 'MRELSA', 'MRELOV',
       'MFALLEEN', 'MFGEKIND', 'MFWEKIND', 'MOPLHOOG', 'MOPLMIDD', 'MOPLLAAG',
       'MBERHOOG', 'MBERZELF', 'MBERBOER', 'MBERMIDD', 'MBERARBG', 'MBERARBO',
       'MSKA', 'MSKB1', 'MSKB2', 'MSKC', 'MSKD', 'MHHUUR', 'MHKOOP', 'MAUT1',
       'MAUT2', 'MAUT0', 'MZFONDS', 'MZPART', 'MINKM30', 'MINK3045',
       'MINK4575', 'MINK7512', 'MINK123M', 'MINKGEM', 'MKOOPKLA', 'PWAPART',
       'PWABEDR', 'PWALAND', 'PPERSAUT', 'PBESAUT', 'PMOTSCO', 'PVRAAUT',
       'PAANHANG', 'PTRACTOR', 'PWERKT', 'PBROM', 'PLEVEN', 'PPERSONG',
       'PGEZONG', 'PWAOREG', 'PBRAND', 'PZEILPL', 'PPLEZIER', 'PFIETS',
       'PINBOED', 'PBYSTAND', 'AWAPART', 'AWABEDR', 'AWALAND', 'APERSAUT',
       'ABESAUT', 'AMOTSCO', 'AVRAAUT', 'AAANHANG', 'ATRACTOR', 'AWERKT',
       'ABROM', 'ALEVEN', 'APERSONG', 'AGEZONG', 'AWAOREG', 'ABRAND',
       'AZEILPL', 'APLEZIER', 'AFIETS', 'AINBOED', 'ABYSTAND', 'Purchase'],
      dtype='object')]

In [18]:
print(df.ndim)

2

In [19]:
print(df.size)

506514

In [20]:
print(df.shape)

(5822, 87)

In [21]:
print(df.values)

[[1 33 1 ... 0 0 'No']
 [2 37 1 ... 0 0 'No']
 [3 37 1 ... 0 0 'No']
 ...
 [5820 33 1 ... 0 0 'Yes']
 [5821 34 1 ... 0 0 'No']
 [5822 33 1 ... 0 0 'No']]

In [22]:
print("Number of records:", len(df))

Number of records: 5822

In [23]:
print("Number of records:", df.shape[0])

Number of records: 5822

In [24]:
print("Number of elements:", df.size)

Number of elements: 506514

In [25]:
print("Column Data Types:")
print(df.dtypes)

Column Data Types:
rownames     int64
MOSTYPE      int64
MAANTHUI     int64
MGEMOMV      int64
MGEMLEEF     int64
             ...
APLEZIER     int64
AFIETS       int64
AINBOED      int64
ABYSTAND     int64
Purchase    object
Length: 87, dtype: object

In [26]:
print("Column Names:")
print(df.columns)

Column Names:
Index(['rownames', 'MOSTYPE', 'MAANTHUI', 'MGEMOMV', 'MGEMLEEF', 'MOSHOOFD',
       'MGODRK', 'MGODPR', 'MGODOV', 'MGODGE', 'MRELGE', 'MRELSA', 'MRELOV',
       'MFALLEEN', 'MFGEKIND', 'MFWEKIND', 'MOPLHOOG', 'MOPLMIDD', 'MOPLLAAG',
       'MBERHOOG', 'MBERZELF', 'MBERBOER', 'MBERMIDD', 'MBERARBG', 'MBERARBO',
       'MSKA', 'MSKB1', 'MSKB2', 'MSKC', 'MSKD', 'MHHUUR', 'MHKOOP', 'MAUT1',
       'MAUT2', 'MAUT0', 'MZFONDS', 'MZPART', 'MINKM30', 'MINK3045',
       'MINK4575', 'MINK7512', 'MINK123M', 'MINKGEM', 'MKOOPKLA', 'PWAPART',
       'PWABEDR', 'PWALAND', 'PPERSAUT', 'PBESAUT', 'PMOTSCO', 'PVRAAUT',
       'PAANHANG', 'PTRACTOR', 'PWERKT', 'PBROM', 'PLEVEN', 'PPERSONG',
       'PGEZONG', 'PWAOREG', 'PBRAND', 'PZEILPL', 'PPLEZIER', 'PFIETS',
       'PINBOED', 'PBYSTAND', 'AWAPART', 'AWABEDR', 'AWALAND', 'APERSAUT',
       'ABESAUT', 'AMOTSCO', 'AVRAAUT', 'AAANHANG', 'ATRACTOR', 'AWERKT',
       'ABROM', 'ALEVEN', 'APERSONG', 'AGEZONG', 'AWAOREG', 'ABRAND',
       'AZEILPL', 'APLEZIER', 'AFIETS', 'AINBOED', 'ABYSTAND', 'Purchase'],
      dtype='object')

In [27]:
df.describe()

,rownames,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,...,ALEVEN,APERSONG,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND
count,5822.000000,5822.000000,5822.000000,5822.000000,5822.000000,5822.000000,5822.000000,5822.000000,5822.000000,5822.000000,...,5822.000000,5822.000000,5822.000000,5822.000000,5822.000000,5822.000000,5822.000000,5822.000000,5822.000000,5822.000000
mean,2911.500000,24.253349,1.110615,2.678805,2.991240,5.773617,0.696496,4.626932,1.069907,3.258502,...,0.076606,0.005325,0.006527,0.004638,0.570079,0.000515,0.006012,0.031776,0.007901,0.014256
std,1680.810965,12.846706,0.405842,0.789835,0.814589,2.856760,1.003234,1.715843,1.017503,1.597647,...,0.377569,0.072782,0.080532,0.077403,0.562058,0.022696,0.081632,0.210986,0.090463,0.119996
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1456.250000,10.000000,1.000000,2.000000,2.000000,3.000000,0.000000,4.000000,0.000000,2.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2911.500000,30.000000,1.000000,3.000000,3.000000,7.000000,0.000000,5.000000,1.000000,3.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,4366.750000,35.000000,1.000000,3.000000,3.000000,8.000000,1.000000,6.000000,2.000000,4.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,5822.000000,41.000000,10.000000,5.000000,6.000000,10.000000,9.000000,9.000000,5.000000,9.000000,...,8.000000,1.000000,1.000000,2.000000,7.000000,1.000000,2.000000,3.000000,2.000000,2.000000

In [28]:
df.median(numeric_only=True)

rownames    2911.5
MOSTYPE       30.0
MAANTHUI       1.0
MGEMOMV        3.0
MGEMLEEF       3.0
             ...
AZEILPL        0.0
APLEZIER       0.0
AFIETS         0.0
AINBOED        0.0
ABYSTAND       0.0
Length: 86, dtype: float64

In [29]:
df.mean(numeric_only=True)

rownames    2911.500000
MOSTYPE       24.253349
MAANTHUI       1.110615
MGEMOMV        2.678805
MGEMLEEF       2.991240
               ...
AZEILPL        0.000515
APLEZIER       0.006012
AFIETS         0.031776
AINBOED        0.007901
ABYSTAND       0.014256
Length: 86, dtype: float64

In [30]:
df.mode(numeric_only=True)

,rownames,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,...,ALEVEN,APERSONG,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND
0,1,33.0,1.0,3.0,3.0,8.0,0.0,4.0,1.0,3.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5817,5818,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5818,5819,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5819,5820,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5820,5821,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5821,5822,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
df.std(numeric_only=True)

rownames    1680.810965
MOSTYPE       12.846706
MAANTHUI       0.405842
MGEMOMV        0.789835
MGEMLEEF       0.814589
               ...
AZEILPL        0.022696
APLEZIER       0.081632
AFIETS         0.210986
AINBOED        0.090463
ABYSTAND       0.119996
Length: 86, dtype: float64

In [32]:
df.sample(5)

,rownames,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,...,APERSONG,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,Purchase
2319,2320,35,1,2,4,8,0,5,1,3,...,0,0,0,1,0,0,0,0,0,No
4438,4439,7,1,3,3,2,1,5,0,4,...,0,0,0,1,0,0,0,0,0,No
2499,2500,24,1,2,3,5,1,5,1,3,...,0,0,0,0,0,0,1,0,0,No
4709,4710,9,1,2,4,3,2,0,2,6,...,0,0,0,0,0,0,0,0,0,No
5488,5489,27,1,2,5,6,1,5,2,3,...,0,0,0,1,0,0,0,0,0,No

In [33]:
df.sample(20)

,rownames,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,...,APERSONG,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,Purchase
5689,5690,6,1,3,3,2,0,7,2,0,...,0,0,0,0,0,0,0,0,0,No
2335,2336,35,1,2,3,8,0,4,0,5,...,0,0,0,2,0,0,0,0,0,No
5091,5092,33,1,2,3,8,3,4,0,3,...,0,0,0,0,0,0,0,0,0,No
4673,4674,38,1,2,2,9,2,0,3,5,...,0,0,0,0,0,0,0,0,0,No
5589,5590,35,1,2,3,8,1,5,1,3,...,0,0,0,1,0,0,0,0,0,No
5719,5720,23,1,2,3,5,0,5,1,4,...,0,0,0,0,0,0,0,0,0,No
4219,4220,9,1,2,3,3,1,1,1,6,...,0,0,0,1,0,0,0,0,0,No
4179,4180,33,1,1,3,8,0,9,0,0,...,0,0,0,1,0,0,0,0,0,No
5130,5131,39,1,2,3,9,2,4,2,3,...,0,0,0,1,0,0,0,0,0,No
5753,5754,33,2,3,3,8,0,4,0,5,...,0,0,0,1,0,0,0,0,0,No
771,772,33,1,3,3,8,0,6,2,1,...,0,0,0,1,0,0,0,0,0,No
506,507,38,1,3,2,9,0,6,3,0,...,0,0,0,1,0,0,0,0,0,No
5597,5598,31,1,3,4,7,0,8,0,1,...,0,0,0,0,0,0,0,0,0,No
3176,3177,2,1,4,2,1,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
1748,1749,35,1,2,3,8,1,5,1,3,...,0,0,1,0,0,0,0,0,0,No
1602,1603,38,1,3,3,9,0,3,0,6,...,0,0,0,0,0,0,0,0,0,No
3020,3021,11,1,3,2,3,6,1,2,2,...,0,0,0,0,0,0,0,0,0,No
2736,2737,35,1,3,3,8,0,7,1,1,...,0,0,0,1,0,0,0,0,0,No
1324,1325,9,1,4,2,3,0,2,3,5,...,0,0,0,1,0,0,0,0,0,No
5632,5633,8,1,3,4,2,3,3,1,4,...,0,0,0,1,0,0,0,0,0,No

In [34]:
# Remove rows with missing values
df.dropna()

,rownames,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,...,APERSONG,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,Purchase
0,1,33,1,3,2,8,0,5,1,3,...,0,0,0,1,0,0,0,0,0,No
1,2,37,1,2,2,8,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
2,3,37,1,2,2,8,0,4,2,4,...,0,0,0,1,0,0,0,0,0,No
3,4,9,1,3,3,3,2,3,2,4,...,0,0,0,1,0,0,0,0,0,No
4,5,40,1,4,2,10,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5817,5818,36,1,1,2,8,0,6,1,2,...,0,0,0,1,0,0,0,0,0,No
5818,5819,35,1,4,4,8,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
5819,5820,33,1,3,4,8,0,6,0,3,...,0,0,0,1,0,0,0,0,0,Yes
5820,5821,34,1,3,2,8,0,7,0,2,...,0,0,0,0,0,0,0,0,0,No
5821,5822,33,1,3,3,8,0,6,1,2,...,0,0,0,0,0,0,0,0,0,No

In [35]:
# List all attributes and methods of the DataFrame
dir(df)

['AAANHANG',
 'ABESAUT',
 'ABRAND',
 'ABROM',
 'ABYSTAND',
 'AFIETS',
 'AGEZONG',
 'AINBOED',
 'ALEVEN',
 'AMOTSCO',
 'APERSAUT',
 'APERSONG',
 'APLEZIER',
 'ATRACTOR',
 'AVRAAUT',
 'AWABEDR',
 'AWALAND',
 'AWAOREG',
 'AWAPART',
 'AWERKT',
 'AZEILPL',
 'MAANTHUI',
 'MAUT0',
 'MAUT1',
 'MAUT2',
 'MBERARBG',
 'MBERARBO',
 'MBERBOER',
 'MBERHOOG',
 'MBERMIDD',
 'MBERZELF',
 'MFALLEEN',
 'MFGEKIND',
 'MFWEKIND',
 'MGEMLEEF',
 'MGEMOMV',
 'MGODGE',
 'MGODOV',
 'MGODPR',
 'MGODRK',
 'MHHUUR',
 'MHKOOP',
 'MINK123M',
 'MINK3045',
 'MINK4575',
 'MINK7512',
 'MINKGEM',
 'MINKM30',
 'MKOOPKLA',
 'MOPLHOOG',
 'MOPLLAAG',
 'MOPLMIDD',
 'MOSHOOFD',
 'MOSTYPE',
 'MRELGE',
 'MRELOV',
 'MRELSA',
 'MSKA',
 'MSKB1',
 'MSKB2',
 'MSKC',
 'MSKD',
 'MZFONDS',
 'MZPART',
 'PAANHANG',
 'PBESAUT',
 'PBRAND',
 'PBROM',
 'PBYSTAND',
 'PFIETS',
 'PGEZONG',
 'PINBOED',
 'PLEVEN',
 'PMOTSCO',
 'PPERSAUT',
 'PPERSONG',
 'PPLEZIER',
 'PTRACTOR',
 'PVRAAUT',
 'PWABEDR',
 'PWALAND',
 'PWAOREG',
 'PWAPART',
 'PWERKT',
 'PZEILPL',
 'Purchase',
 'T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_arith_method_with_reindex',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_create_data_for_split_and_tight_to_dict',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_nocopy',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rownames',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [36]:
print("Mean values of the first 50 records:")
print(df.head(50).mean(numeric_only=True))

Mean values of the first 50 records:
rownames    25.50
MOSTYPE     27.40
MAANTHUI     1.22
MGEMOMV      2.84
MGEMLEEF     2.72
            ...
AZEILPL      0.00
APLEZIER     0.00
AFIETS       0.04
AINBOED      0.02
ABYSTAND     0.02
Length: 86, dtype: float64

In [37]:
print("Mean values of the last 50 records:")
print(df.tail(50).mean(numeric_only=True))

Mean values of the last 50 records:
rownames    5797.50
MOSTYPE       25.40
MAANTHUI       1.04
MGEMOMV        2.70
MGEMLEEF       2.96
             ...
AZEILPL        0.00
APLEZIER       0.00
AFIETS         0.00
AINBOED        0.00
ABYSTAND       0.00
Length: 86, dtype: float64

In [38]:
df.columns

Index(['rownames', 'MOSTYPE', 'MAANTHUI', 'MGEMOMV', 'MGEMLEEF', 'MOSHOOFD',
       'MGODRK', 'MGODPR', 'MGODOV', 'MGODGE', 'MRELGE', 'MRELSA', 'MRELOV',
       'MFALLEEN', 'MFGEKIND', 'MFWEKIND', 'MOPLHOOG', 'MOPLMIDD', 'MOPLLAAG',
       'MBERHOOG', 'MBERZELF', 'MBERBOER', 'MBERMIDD', 'MBERARBG', 'MBERARBO',
       'MSKA', 'MSKB1', 'MSKB2', 'MSKC', 'MSKD', 'MHHUUR', 'MHKOOP', 'MAUT1',
       'MAUT2', 'MAUT0', 'MZFONDS', 'MZPART', 'MINKM30', 'MINK3045',
       'MINK4575', 'MINK7512', 'MINK123M', 'MINKGEM', 'MKOOPKLA', 'PWAPART',
       'PWABEDR', 'PWALAND', 'PPERSAUT', 'PBESAUT', 'PMOTSCO', 'PVRAAUT',
       'PAANHANG', 'PTRACTOR', 'PWERKT', 'PBROM', 'PLEVEN', 'PPERSONG',
       'PGEZONG', 'PWAOREG', 'PBRAND', 'PZEILPL', 'PPLEZIER', 'PFIETS',
       'PINBOED', 'PBYSTAND', 'AWAPART', 'AWABEDR', 'AWALAND', 'APERSAUT',
       'ABESAUT', 'AMOTSCO', 'AVRAAUT', 'AAANHANG', 'ATRACTOR', 'AWERKT',
       'ABROM', 'ALEVEN', 'APERSONG', 'AGEZONG', 'AWAOREG', 'ABRAND',
       'AZEILPL', 'APLEZIER', 'AFIETS', 'AINBOED', 'ABYSTAND', 'Purchase'],
      dtype='object')

In [39]:
df['rownames']

0          1
1          2
2          3
3          4
4          5
        ...
5817    5818
5818    5819
5819    5820
5820    5821
5821    5822
Name: rownames, Length: 5822, dtype: int64

In [40]:
df['MBERBOER'].describe()

count    5822.000000
mean        0.522329
std         1.056926
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         9.000000
Name: MBERBOER, dtype: float64

In [41]:
df['PBRAND'].describe()

count    5822.000000
mean        1.827722
std         1.879290
min         0.000000
25%         0.000000
50%         2.000000
75%         4.000000
max         8.000000
Name: PBRAND, dtype: float64

In [42]:
df['AINBOED'].count()

np.int64(5822)

In [43]:
df['AZEILPL'].count()

np.int64(5822)

In [44]:
df['MGODGE'].mean()

np.float64(3.258502232909653)

In [45]:
df['AWABEDR'].mean()

np.float64(0.014771556166265888)

In [46]:
df[10:20]

,rownames,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,...,APERSONG,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,Purchase
10,11,10,1,4,3,3,1,4,1,4,...,0,0,0,0,0,0,0,0,0,No
11,12,9,1,3,3,3,1,3,2,4,...,0,0,0,1,0,0,0,0,0,No
12,13,33,1,2,3,8,1,4,1,4,...,0,0,0,0,0,0,0,0,0,No
13,14,41,1,3,3,10,0,5,0,4,...,0,0,0,0,0,0,0,0,0,No
14,15,23,1,1,2,5,0,6,1,2,...,0,0,0,1,0,0,0,0,0,No
15,16,33,1,2,3,8,0,7,0,2,...,0,0,0,1,0,0,0,0,0,No
16,17,38,1,2,3,9,0,6,0,3,...,0,0,0,0,0,0,0,0,0,No
17,18,22,2,3,3,5,0,5,0,4,...,0,0,0,1,0,0,0,0,0,No
18,19,13,1,4,2,3,2,4,0,3,...,0,0,0,1,0,0,0,0,0,No
19,20,31,1,2,4,7,0,2,0,7,...,0,0,0,0,0,0,0,0,0,No

In [47]:
df[10:30]

,rownames,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,...,APERSONG,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,Purchase
10,11,10,1,4,3,3,1,4,1,4,...,0,0,0,0,0,0,0,0,0,No
11,12,9,1,3,3,3,1,3,2,4,...,0,0,0,1,0,0,0,0,0,No
12,13,33,1,2,3,8,1,4,1,4,...,0,0,0,0,0,0,0,0,0,No
13,14,41,1,3,3,10,0,5,0,4,...,0,0,0,0,0,0,0,0,0,No
14,15,23,1,1,2,5,0,6,1,2,...,0,0,0,1,0,0,0,0,0,No
15,16,33,1,2,3,8,0,7,0,2,...,0,0,0,1,0,0,0,0,0,No
16,17,38,1,2,3,9,0,6,0,3,...,0,0,0,0,0,0,0,0,0,No
17,18,22,2,3,3,5,0,5,0,4,...,0,0,0,1,0,0,0,0,0,No
18,19,13,1,4,2,3,2,4,0,3,...,0,0,0,1,0,0,0,0,0,No
19,20,31,1,2,4,7,0,2,0,7,...,0,0,0,0,0,0,0,0,0,No
20,21,33,1,4,3,8,0,6,0,3,...,0,0,0,0,0,0,0,0,0,No
21,22,33,2,3,3,8,0,4,2,3,...,0,0,0,1,0,0,0,0,0,No
22,23,13,1,3,2,3,1,7,0,2,...,0,0,0,1,0,0,0,0,0,No
23,24,34,2,3,2,8,0,7,0,2,...,0,0,0,0,0,0,0,0,0,No
24,25,13,2,4,3,3,0,4,2,4,...,0,0,0,0,0,0,1,0,0,No
25,26,33,1,3,3,8,0,6,1,2,...,0,0,0,1,0,0,0,0,0,No
26,27,37,1,3,3,8,0,5,0,4,...,0,0,0,0,0,0,0,0,0,No
27,28,40,1,3,3,10,0,3,0,6,...,0,0,0,1,0,0,0,0,0,No
28,29,31,1,4,2,7,0,9,0,0,...,0,0,0,0,0,0,0,0,0,No
29,30,33,2,2,3,8,0,7,1,2,...,0,0,0,1,0,0,0,0,0,No

In [48]:
df.loc[10:20,['rownames', 'MOSTYPE', 'MAANTHUI']]

    rownames  MOSTYPE  MAANTHUI
10        11       10         1
11        12        9         1
12        13       33         1
13        14       41         1
14        15       23         1
15        16       33         1
16        17       38         1
17        18       22         2
18        19       13         1
19        20       31         1
20        21       33         1

In [49]:
df.loc[10:20,['PPERSAUT', 'PBESAUT', 'PMOTSCO', 'PVRAAUT']]

    PPERSAUT  PBESAUT  PMOTSCO  PVRAAUT
10         6        0        0        0
11         5        0        0        0
12         6        0        0        0
13         0        0        0        0
14         5        0        0        0
15         0        0        0        0
16         0        0        0        0
17         6        0        0        0
18         5        0        0        0
19         0        0        0        0
20         6        0        0        0

In [50]:
#MISSING VALUE
df.dropna(how='all')

,rownames,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,...,APERSONG,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,Purchase
0,1,33,1,3,2,8,0,5,1,3,...,0,0,0,1,0,0,0,0,0,No
1,2,37,1,2,2,8,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
2,3,37,1,2,2,8,0,4,2,4,...,0,0,0,1,0,0,0,0,0,No
3,4,9,1,3,3,3,2,3,2,4,...,0,0,0,1,0,0,0,0,0,No
4,5,40,1,4,2,10,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5817,5818,36,1,1,2,8,0,6,1,2,...,0,0,0,1,0,0,0,0,0,No
5818,5819,35,1,4,4,8,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
5819,5820,33,1,3,4,8,0,6,0,3,...,0,0,0,1,0,0,0,0,0,Yes
5820,5821,34,1,3,2,8,0,7,0,2,...,0,0,0,0,0,0,0,0,0,No
5821,5822,33,1,3,3,8,0,6,1,2,...,0,0,0,0,0,0,0,0,0,No

In [51]:
df.dropna(axis=1, how='all')

,rownames,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,...,APERSONG,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,Purchase
0,1,33,1,3,2,8,0,5,1,3,...,0,0,0,1,0,0,0,0,0,No
1,2,37,1,2,2,8,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
2,3,37,1,2,2,8,0,4,2,4,...,0,0,0,1,0,0,0,0,0,No
3,4,9,1,3,3,3,2,3,2,4,...,0,0,0,1,0,0,0,0,0,No
4,5,40,1,4,2,10,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5817,5818,36,1,1,2,8,0,6,1,2,...,0,0,0,1,0,0,0,0,0,No
5818,5819,35,1,4,4,8,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
5819,5820,33,1,3,4,8,0,6,0,3,...,0,0,0,1,0,0,0,0,0,Yes
5820,5821,34,1,3,2,8,0,7,0,2,...,0,0,0,0,0,0,0,0,0,No
5821,5822,33,1,3,3,8,0,6,1,2,...,0,0,0,0,0,0,0,0,0,No

In [52]:
df.min()

rownames     1
MOSTYPE      1
MAANTHUI     1
MGEMOMV      1
MGEMLEEF     1
            ..
APLEZIER     0
AFIETS       0
AINBOED      0
ABYSTAND     0
Purchase    No
Length: 87, dtype: object

In [53]:
df.max()

rownames    5822
MOSTYPE       41
MAANTHUI      10
MGEMOMV        5
MGEMLEEF       6
            ...
APLEZIER       2
AFIETS         3
AINBOED        2
ABYSTAND       2
Purchase     Yes
Length: 87, dtype: object

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5822 entries, 0 to 5821
Data columns (total 87 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   rownames  5822 non-null   int64
 1   MOSTYPE   5822 non-null   int64
 2   MAANTHUI  5822 non-null   int64
 3   MGEMOMV   5822 non-null   int64
 4   MGEMLEEF  5822 non-null   int64
 5   MOSHOOFD  5822 non-null   int64
 6   MGODRK    5822 non-null   int64
 7   MGODPR    5822 non-null   int64
 8   MGODOV    5822 non-null   int64
 9   MGODGE    5822 non-null   int64
 10  MRELGE    5822 non-null   int64
 11  MRELSA    5822 non-null   int64
 12  MRELOV    5822 non-null   int64
 13  MFALLEEN  5822 non-null   int64
 14  MFGEKIND  5822 non-null   int64
 15  MFWEKIND  5822 non-null   int64
 16  MOPLHOOG  5822 non-null   int64
 17  MOPLMIDD  5822 non-null   int64
 18  MOPLLAAG  5822 non-null   int64
 19  MBERHOOG  5822 non-null   int64
 20  MBERZELF  5822 non-null   int64
 21  MBERBOER  5822 non-null   int64
 22  MBERMIDD  5822 non-null   int64
 23  MBERARBG  5822 non-null   int64
 24  MBERARBO  5822 non-null   int64
 25  MSKA      5822 non-null   int64
 26  MSKB1     5822 non-null   int64
 27  MSKB2     5822 non-null   int64
 28  MSKC      5822 non-null   int64
 29  MSKD      5822 non-null   int64
 30  MHHUUR    5822 non-null   int64
 31  MHKOOP    5822 non-null   int64
 32  MAUT1     5822 non-null   int64
 33  MAUT2     5822 non-null   int64
 34  MAUT0     5822 non-null   int64
 35  MZFONDS   5822 non-null   int64
 36  MZPART    5822 non-null   int64
 37  MINKM30   5822 non-null   int64
 38  MINK3045  5822 non-null   int64
 39  MINK4575  5822 non-null   int64
 40  MINK7512  5822 non-null   int64
 41  MINK123M  5822 non-null   int64
 42  MINKGEM   5822 non-null   int64
 43  MKOOPKLA  5822 non-null   int64
 44  PWAPART   5822 non-null   int64
 45  PWABEDR   5822 non-null   int64
 46  PWALAND   5822 non-null   int64
 47  PPERSAUT  5822 non-null   int64
 48  PBESAUT   5822 non-null   int64
 49  PMOTSCO   5822 non-null   int64
 50  PVRAAUT   5822 non-null   int64
 51  PAANHANG  5822 non-null   int64
 52  PTRACTOR  5822 non-null   int64
 53  PWERKT    5822 non-null   int64
 54  PBROM     5822 non-null   int64
 55  PLEVEN    5822 non-null   int64
 56  PPERSONG  5822 non-null   int64
 57  PGEZONG   5822 non-null   int64
 58  PWAOREG   5822 non-null   int64
 59  PBRAND    5822 non-null   int64
 60  PZEILPL   5822 non-null   int64
 61  PPLEZIER  5822 non-null   int64
 62  PFIETS    5822 non-null   int64
 63  PINBOED   5822 non-null   int64
 64  PBYSTAND  5822 non-null   int64
 65  AWAPART   5822 non-null   int64
 66  AWABEDR   5822 non-null   int64
 67  AWALAND   5822 non-null   int64
 68  APERSAUT  5822 non-null   int64
 69  ABESAUT   5822 non-null   int64
 70  AMOTSCO   5822 non-null   int64
 71  AVRAAUT   5822 non-null   int64
 72  AAANHANG  5822 non-null   int64
 73  ATRACTOR  5822 non-null   int64
 74  AWERKT    5822 non-null   int64
 75  ABROM     5822 non-null   int64
 76  ALEVEN    5822 non-null   int64
 77  APERSONG  5822 non-null   int64
 78  AGEZONG   5822 non-null   int64
 79  AWAOREG   5822 non-null   int64
 80  ABRAND    5822 non-null   int64
 81  AZEILPL   5822 non-null   int64
 82  APLEZIER  5822 non-null   int64
 83  AFIETS    5822 non-null   int64
 84  AINBOED   5822 non-null   int64
 85  ABYSTAND  5822 non-null   int64
 86  Purchase  5822 non-null   object
dtypes: int64(86), object(1)
memory usage: 3.9+ MB