In [1]:
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib as mpl
import seaborn as sns
df =pd.read_csv("/content/CASchools.csv")

In [4]:
df.head()

,rownames,district,school,county,grades,students,teachers,calworks,lunch,computer,expenditure,income,english,read,math
0,1,75119,Sunol Glen Unified,Alameda,KK-08,195,10.900000,0.510200,2.040800,67,6384.911133,22.690001,0.000000,691.599976,690.000000
1,2,61499,Manzanita Elementary,Butte,KK-08,240,11.150000,15.416700,47.916698,101,5099.380859,9.824000,4.583333,660.500000,661.900024
2,3,61549,Thermalito Union Elementary,Butte,KK-08,1550,82.900002,55.032299,76.322601,169,5501.954590,8.978000,30.000002,636.299988,650.900024
3,4,61457,Golden Feather Union Elementary,Butte,KK-08,243,14.000000,36.475399,77.049202,85,7101.831055,8.978000,0.000000,651.900024,643.500000
4,5,61523,Palermo Union Elementary,Butte,KK-08,1335,71.500000,33.108601,78.427002,171,5235.987793,9.080333,13.857677,641.799988,639.900024

In [5]:
df.head(10)

,rownames,district,school,county,grades,students,teachers,calworks,lunch,computer,expenditure,income,english,read,math
0,1,75119,Sunol Glen Unified,Alameda,KK-08,195,10.900000,0.510200,2.040800,67,6384.911133,22.690001,0.000000,691.599976,690.000000
1,2,61499,Manzanita Elementary,Butte,KK-08,240,11.150000,15.416700,47.916698,101,5099.380859,9.824000,4.583333,660.500000,661.900024
2,3,61549,Thermalito Union Elementary,Butte,KK-08,1550,82.900002,55.032299,76.322601,169,5501.954590,8.978000,30.000002,636.299988,650.900024
3,4,61457,Golden Feather Union Elementary,Butte,KK-08,243,14.000000,36.475399,77.049202,85,7101.831055,8.978000,0.000000,651.900024,643.500000
4,5,61523,Palermo Union Elementary,Butte,KK-08,1335,71.500000,33.108601,78.427002,171,5235.987793,9.080333,13.857677,641.799988,639.900024
5,6,62042,Burrel Union Elementary,Fresno,KK-08,137,6.400000,12.318800,86.956497,25,5580.146973,10.415000,12.408759,605.700012,605.400024
6,7,68536,Holt Union Elementary,San Joaquin,KK-08,195,10.000000,12.903200,94.623703,28,5253.331055,6.577000,68.717949,604.500000,609.000000
7,8,63834,Vineland Elementary,Kern,KK-08,888,42.500000,18.806299,100.000000,66,4565.746094,8.174000,46.959461,605.500000,612.500000
8,9,62331,Orange Center Elementary,Fresno,KK-08,379,19.000000,32.189999,93.139801,35,5355.548340,7.385000,30.079157,608.900024,616.099976
9,10,67306,Del Paso Heights Elementary,Sacramento,KK-06,2247,108.000000,78.994202,87.316399,0,5036.211426,11.613333,40.275921,611.900024,613.400024

In [6]:
df.head(20)

,rownames,district,school,county,grades,students,teachers,calworks,lunch,computer,expenditure,income,english,read,math
0,1,75119,Sunol Glen Unified,Alameda,KK-08,195,10.900000,0.510200,2.040800,67,6384.911133,22.690001,0.000000,691.599976,690.000000
1,2,61499,Manzanita Elementary,Butte,KK-08,240,11.150000,15.416700,47.916698,101,5099.380859,9.824000,4.583333,660.500000,661.900024
2,3,61549,Thermalito Union Elementary,Butte,KK-08,1550,82.900002,55.032299,76.322601,169,5501.954590,8.978000,30.000002,636.299988,650.900024
3,4,61457,Golden Feather Union Elementary,Butte,KK-08,243,14.000000,36.475399,77.049202,85,7101.831055,8.978000,0.000000,651.900024,643.500000
4,5,61523,Palermo Union Elementary,Butte,KK-08,1335,71.500000,33.108601,78.427002,171,5235.987793,9.080333,13.857677,641.799988,639.900024
5,6,62042,Burrel Union Elementary,Fresno,KK-08,137,6.400000,12.318800,86.956497,25,5580.146973,10.415000,12.408759,605.700012,605.400024
6,7,68536,Holt Union Elementary,San Joaquin,KK-08,195,10.000000,12.903200,94.623703,28,5253.331055,6.577000,68.717949,604.500000,609.000000
7,8,63834,Vineland Elementary,Kern,KK-08,888,42.500000,18.806299,100.000000,66,4565.746094,8.174000,46.959461,605.500000,612.500000
8,9,62331,Orange Center Elementary,Fresno,KK-08,379,19.000000,32.189999,93.139801,35,5355.548340,7.385000,30.079157,608.900024,616.099976
9,10,67306,Del Paso Heights Elementary,Sacramento,KK-06,2247,108.000000,78.994202,87.316399,0,5036.211426,11.613333,40.275921,611.900024,613.400024
10,11,65722,Le Grand Union Elementary,Merced,KK-08,446,21.000000,18.609900,85.874397,86,4547.692383,8.931000,52.914799,612.799988,618.700012
11,12,62174,West Fresno Elementary,Fresno,KK-08,987,47.000000,71.713097,98.605598,56,5447.345215,7.385000,54.609932,616.599976,616.000000
12,13,71795,Allensworth Elementary,Tulare,KK-08,103,5.000000,22.429899,98.130798,25,6567.149414,5.335000,42.718445,612.799988,619.799988
13,14,72181,Sunnyside Union Elementary,Tulare,KK-08,487,24.340000,24.609400,77.148399,0,4818.612793,8.279000,20.533880,610.000000,622.599976
14,15,72298,Woodville Elementary,Tulare,KK-08,649,36.000000,14.637900,76.271202,31,5621.456055,9.630000,80.123260,611.900024,621.000000
15,16,72041,Pixley Union Elementary,Tulare,KK-08,852,42.070000,24.214199,94.295700,80,6026.359863,7.454000,49.413143,614.799988,619.900024
16,17,63594,Lost Hills Union Elementary,Kern,KK-08,491,28.920000,11.201600,97.759697,100,6723.237793,6.216000,85.539719,611.700012,624.400024
17,18,63370,Buttonwillow Union Elementary,Kern,KK-08,421,25.500000,8.551100,77.909698,50,5589.885254,7.764000,58.907364,614.900024,621.700012
18,19,64709,Lennox Elementary,Los Angeles,KK-08,6880,303.029999,21.282400,94.971199,960,5064.615723,7.022000,77.005814,619.099976,620.500000
19,20,63560,Lamont Elementary,Kern,KK-08,2688,135.000000,23.437500,93.229202,139,5433.593262,5.699000,49.813988,621.299988,619.299988

In [7]:
df.tail()

,rownames,district,school,county,grades,students,teachers,calworks,lunch,computer,expenditure,income,english,read,math
415,416,68957,Las Lomitas Elementary,San Mateo,KK-08,984,59.730000,0.1016,3.556900,195,7290.338867,28.716999,5.995935,700.900024,707.700012
416,417,69518,Los Altos Elementary,Santa Clara,KK-08,3724,208.479996,1.0741,1.503800,721,5741.462891,41.734108,4.726101,704.000000,709.500000
417,418,72611,Somis Union Elementary,Ventura,KK-08,441,20.150000,3.5635,37.193802,45,4402.831543,23.733000,24.263039,648.299988,641.700012
418,419,72744,Plumas Elementary,Yuba,KK-08,101,5.000000,11.8812,59.405899,14,4776.336426,9.952000,2.970297,667.900024,676.500000
419,420,72751,Wheatland Elementary,Yuba,KK-08,1778,93.400002,6.9235,47.571201,313,5993.392578,12.502000,5.005624,660.500000,651.000000

In [8]:
df.tail(6)

,rownames,district,school,county,grades,students,teachers,calworks,lunch,computer,expenditure,income,english,read,math
414,415,69682,Saratoga Union Elementary,Santa Clara,KK-08,2341,124.089996,0.1709,0.598000,286,5392.638672,40.402000,2.050406,698.900024,701.700012
415,416,68957,Las Lomitas Elementary,San Mateo,KK-08,984,59.730000,0.1016,3.556900,195,7290.338867,28.716999,5.995935,700.900024,707.700012
416,417,69518,Los Altos Elementary,Santa Clara,KK-08,3724,208.479996,1.0741,1.503800,721,5741.462891,41.734108,4.726101,704.000000,709.500000
417,418,72611,Somis Union Elementary,Ventura,KK-08,441,20.150000,3.5635,37.193802,45,4402.831543,23.733000,24.263039,648.299988,641.700012
418,419,72744,Plumas Elementary,Yuba,KK-08,101,5.000000,11.8812,59.405899,14,4776.336426,9.952000,2.970297,667.900024,676.500000
419,420,72751,Wheatland Elementary,Yuba,KK-08,1778,93.400002,6.9235,47.571201,313,5993.392578,12.502000,5.005624,660.500000,651.000000

In [9]:
df.min(numeric_only=True)

rownames           1.000000
district       61382.000000
students          81.000000
teachers           4.850000
calworks           0.000000
lunch              0.000000
computer           0.000000
expenditure     3926.069580
income             5.335000
english            0.000000
read             604.500000
math             605.400024
dtype: float64

In [10]:
df.max(numeric_only=True)

rownames         420.000000
district       75440.000000
students       27176.000000
teachers        1429.000000
calworks          78.994202
lunch            100.000000
computer        3324.000000
expenditure     7711.506836
income            55.327999
english           85.539719
read             704.000000
math             709.500000
dtype: float64

In [11]:
df.dtypes

rownames         int64
district         int64
school          object
county          object
grades          object
students         int64
teachers       float64
calworks       float64
lunch          float64
computer         int64
expenditure    float64
income         float64
english        float64
read           float64
math           float64
dtype: object

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 420 entries, 0 to 419
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   rownames     420 non-null    int64
 1   district     420 non-null    int64
 2   school       420 non-null    object
 3   county       420 non-null    object
 4   grades       420 non-null    object
 5   students     420 non-null    int64
 6   teachers     420 non-null    float64
 7   calworks     420 non-null    float64
 8   lunch        420 non-null    float64
 9   computer     420 non-null    int64
 10  expenditure  420 non-null    float64
 11  income       420 non-null    float64
 12  english      420 non-null    float64
 13  read         420 non-null    float64
 14  math         420 non-null    float64
dtypes: float64(8), int64(4), object(3)
memory usage: 49.3+ KB

In [13]:
df['county'].dtypes

dtype('O')

In [16]:
df['lunch'].dtypes

dtype('float64')

In [17]:
print(df.axes)

[RangeIndex(start=0, stop=420, step=1), Index(['rownames', 'district', 'school', 'county', 'grades', 'students',
       'teachers', 'calworks', 'lunch', 'computer', 'expenditure', 'income',
       'english', 'read', 'math'],
      dtype='object')]

In [18]:
print(df.ndim)

2

In [19]:
print(df.size)

6300

In [20]:
print(df.shape)

(420, 15)

In [21]:
print(df.values)

[[1 75119 'Sunol Glen Unified' ... 0.0 691.5999755859375 690.0]
 [2 61499 'Manzanita Elementary' ... 4.583333492279053 660.5
  661.9000244140625]
 [3 61549 'Thermalito Union Elementary' ... 30.000001907348636
  636.2999877929688 650.9000244140625]
 ...
 [418 72611 'Somis Union Elementary' ... 24.263038635253903
  648.2999877929688 641.7000122070312]
 [419 72744 'Plumas Elementary' ... 2.97029709815979 667.9000244140625
  676.5]
 [420 72751 'Wheatland Elementary' ... 5.005624294281006 660.5 651.0]]

In [22]:
print("Number of records:", len(df))

Number of records: 420

In [23]:
print("Number of records:", df.shape[0])

Number of records: 420

In [24]:
print("Number of elements:", df.size)

Number of elements: 6300

In [25]:
print("Column Data Types:")
print(df.dtypes)

Column Data Types:
rownames         int64
district         int64
school          object
county          object
grades          object
students         int64
teachers       float64
calworks       float64
lunch          float64
computer         int64
expenditure    float64
income         float64
english        float64
read           float64
math           float64
dtype: object

In [26]:
print("Column Names:")
print(df.columns)

Column Names:
Index(['rownames', 'district', 'school', 'county', 'grades', 'students',
       'teachers', 'calworks', 'lunch', 'computer', 'expenditure', 'income',
       'english', 'read', 'math'],
      dtype='object')

In [27]:
df.describe()

,rownames,district,students,teachers,calworks,lunch,computer,expenditure,income,english,read,math
count,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000
mean,210.500000,67472.809524,2628.792857,129.067376,13.246042,44.705237,303.383333,5312.407541,15.316588,15.768155,654.970477,653.342619
std,121.387808,3466.994655,3913.104985,187.912679,11.454821,27.123381,441.341298,633.937053,7.225890,18.285927,20.107980,18.754202
min,1.000000,61382.000000,81.000000,4.850000,0.000000,0.000000,0.000000,3926.069580,5.335000,0.000000,604.500000,605.400024
25%,105.750000,64307.750000,379.000000,19.662499,4.395375,23.282200,46.000000,4906.180054,10.639000,1.940807,640.400024,639.375015
50%,210.500000,67760.500000,950.500000,48.564999,10.520450,41.750700,117.500000,5214.516602,13.727800,8.777634,655.750000,652.449982
75%,315.250000,70419.000000,3008.000000,146.350002,18.981350,66.864725,375.250000,5601.401367,17.629001,22.970003,668.725006,665.849991
max,420.000000,75440.000000,27176.000000,1429.000000,78.994202,100.000000,3324.000000,7711.506836,55.327999,85.539719,704.000000,709.500000

In [28]:
df.median(numeric_only=True)

rownames         210.500000
district       67760.500000
students         950.500000
teachers          48.564999
calworks          10.520450
lunch             41.750700
computer         117.500000
expenditure     5214.516602
income            13.727800
english            8.777634
read             655.750000
math             652.449982
dtype: float64

In [29]:
df.mean(numeric_only=True)

rownames         210.500000
district       67472.809524
students        2628.792857
teachers         129.067376
calworks          13.246042
lunch             44.705237
computer         303.383333
expenditure     5312.407541
income            15.316588
english           15.768155
read             654.970477
math             653.342619
dtype: float64

In [30]:
df.mode(numeric_only=True)

,rownames,district,students,teachers,calworks,lunch,computer,expenditure,income,english,read,math
0,1,61382,160.0,5.0,0.0,0.0,50.0,3926.069580,7.385,0.0,633.200012,636.700012
1,2,61457,474.0,NaN,NaN,NaN,NaN,4016.416260,9.630,NaN,651.599976,NaN
2,3,61499,NaN,NaN,NaN,NaN,NaN,4023.531738,10.098,NaN,655.099976,NaN
3,4,61507,NaN,NaN,NaN,NaN,NaN,4079.129150,11.116,NaN,662.000000,NaN
4,5,61523,NaN,NaN,NaN,NaN,NaN,4136.250977,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
415,416,75051,NaN,NaN,NaN,NaN,NaN,7542.038086,NaN,NaN,NaN,NaN
416,417,75085,NaN,NaN,NaN,NaN,NaN,7593.405762,NaN,NaN,NaN,NaN
417,418,75119,NaN,NaN,NaN,NaN,NaN,7614.379395,NaN,NaN,NaN,NaN
418,419,75135,NaN,NaN,NaN,NaN,NaN,7667.571777,NaN,NaN,NaN,NaN
419,420,75440,NaN,NaN,NaN,NaN,NaN,7711.506836,NaN,NaN,NaN,NaN

In [31]:
df.std(numeric_only=True)

rownames        121.387808
district       3466.994655
students       3913.104985
teachers        187.912679
calworks         11.454821
lunch            27.123381
computer        441.341298
expenditure     633.937053
income            7.225890
english          18.285927
read             20.107980
math             18.754202
dtype: float64

In [32]:
df.sample(5)

,rownames,district,school,county,grades,students,teachers,calworks,lunch,computer,expenditure,income,english,read,math
246,247,67785,Mountain View Elementary,San Bernardino,KK-08,3182,153.199997,3.530500,26.943300,328,4777.512695,12.900,8.956632,654.700012,662.500000
269,270,71084,Gratton Elementary,Stanislaus,KK-08,105,5.730000,0.000000,0.000000,16,4877.086426,13.586,10.476191,662.500000,661.299988
141,142,73726,Merced River Union Elementary,Merced,KK-08,227,11.600000,18.061701,59.030800,25,5519.677246,14.906,15.859030,649.700012,640.200012
206,207,70045,Junction Elementary,Shasta,KK-08,532,31.000000,10.506600,29.643499,81,5920.253418,13.906,0.000000,656.599976,651.299988
13,14,72181,Sunnyside Union Elementary,Tulare,KK-08,487,24.340000,24.609400,77.148399,0,4818.612793,8.279,20.533880,610.000000,622.599976

In [33]:
df.sample(20)

,rownames,district,school,county,grades,students,teachers,calworks,lunch,computer,expenditure,income,english,read,math
74,75,69203,Guadalupe Union Elementary,Santa Barbara,KK-08,1088,55.000000,14.154400,86.029404,107,4136.250977,6.983000,64.246323,631.099976,638.700012
67,68,63917,Hanford Elementary,Kings,KK-08,5079,224.500000,25.559299,63.803600,585,5228.650879,11.116000,16.617445,637.700012,630.500000
145,146,68205,Lemon Grove Elementary,San Diego,KK-08,4612,232.970001,17.476101,65.915001,601,5124.836426,12.827000,16.652212,647.700012,643.400024
341,342,61879,Gold Oak Union Elementary,El Dorado,KK-08,868,45.000000,4.723500,19.009199,122,5118.130371,15.167000,0.000000,674.599976,668.000000
336,337,68049,Dehesa Elementary,San Diego,KK-06,188,9.000000,6.383000,36.702099,41,6002.071777,18.799000,4.787234,673.200012,666.500000
131,132,63487,General Shafter Elementary,Kern,KK-08,224,10.000000,7.142900,58.035702,31,4741.957031,13.192000,7.589286,633.599976,653.799988
237,238,66324,Clear Creek Elementary,Nevada,KK-08,117,6.000000,8.403400,36.134499,42,6039.985840,16.356001,0.854701,664.900024,649.900024
371,372,70078,North Cow Creek Elementary,Shasta,KK-08,297,15.350000,2.356900,4.040400,70,4273.993164,13.906000,0.000000,679.000000,675.500000
124,125,71837,Burton Elementary,Tulare,KK-08,2208,114.500000,14.414000,53.210602,92,4960.515625,9.630000,9.873188,642.000000,644.099976
398,399,69419,Cupertino Union Elementary,Santa Clara,KK-08,15228,708.830017,1.715400,4.690900,2232,4962.736816,27.475216,8.648542,683.099976,690.299988
230,231,63883,Central Union Elementary,Kings,KK-08,1789,96.000000,2.962500,56.008900,435,7070.633301,10.556667,9.558413,655.400024,657.900024
405,406,65391,Mill Valley Elementary,Marin,KK-08,2340,132.199997,1.581200,2.435900,403,6415.354980,35.480999,2.478632,693.599976,694.900024
209,210,71829,Buena Vista Elementary,Tulare,KK-08,156,6.050000,10.429400,47.852798,7,3926.069580,10.098000,9.615385,659.799988,648.599976
344,345,61887,Gold Trail Union Elementary,El Dorado,KK-08,678,34.840000,2.507400,15.929200,47,5450.103516,15.167000,0.147493,677.599976,665.700012
91,92,64048,Lucerne Elementary,Lake,KK-08,300,15.000000,48.344398,72.185402,55,5869.389160,11.553000,0.666667,640.900024,633.799988
24,25,65748,Livingston Union Elementary,Merced,KK-08,2357,114.000000,16.801001,90.623703,216,4555.464355,8.019000,76.665253,619.500000,625.700012
268,269,66910,Roseville City Elementary,Placer,KK-08,5714,277.670013,10.534300,30.069099,489,4981.387695,18.029554,8.662933,664.299988,659.500000
228,229,66316,Chicago Park Elementary,Nevada,KK-08,145,10.210000,8.275900,20.000000,20,5635.786133,13.712000,0.000000,657.799988,655.200012
337,338,69955,Cottonwood Union Elementary,Shasta,KK-08,1212,65.900002,22.194700,46.122101,116,5090.587891,10.551000,3.960396,669.200012,670.700012
76,77,61705,Knightsen Elementary,Contra Costa,KK-08,353,19.980000,8.672100,33.062302,8,5238.392090,14.653000,5.382436,636.599976,633.500000

In [34]:
# Remove rows with missing values
df.dropna()

,rownames,district,school,county,grades,students,teachers,calworks,lunch,computer,expenditure,income,english,read,math
0,1,75119,Sunol Glen Unified,Alameda,KK-08,195,10.900000,0.510200,2.040800,67,6384.911133,22.690001,0.000000,691.599976,690.000000
1,2,61499,Manzanita Elementary,Butte,KK-08,240,11.150000,15.416700,47.916698,101,5099.380859,9.824000,4.583333,660.500000,661.900024
2,3,61549,Thermalito Union Elementary,Butte,KK-08,1550,82.900002,55.032299,76.322601,169,5501.954590,8.978000,30.000002,636.299988,650.900024
3,4,61457,Golden Feather Union Elementary,Butte,KK-08,243,14.000000,36.475399,77.049202,85,7101.831055,8.978000,0.000000,651.900024,643.500000
4,5,61523,Palermo Union Elementary,Butte,KK-08,1335,71.500000,33.108601,78.427002,171,5235.987793,9.080333,13.857677,641.799988,639.900024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415,416,68957,Las Lomitas Elementary,San Mateo,KK-08,984,59.730000,0.101600,3.556900,195,7290.338867,28.716999,5.995935,700.900024,707.700012
416,417,69518,Los Altos Elementary,Santa Clara,KK-08,3724,208.479996,1.074100,1.503800,721,5741.462891,41.734108,4.726101,704.000000,709.500000
417,418,72611,Somis Union Elementary,Ventura,KK-08,441,20.150000,3.563500,37.193802,45,4402.831543,23.733000,24.263039,648.299988,641.700012
418,419,72744,Plumas Elementary,Yuba,KK-08,101,5.000000,11.881200,59.405899,14,4776.336426,9.952000,2.970297,667.900024,676.500000
419,420,72751,Wheatland Elementary,Yuba,KK-08,1778,93.400002,6.923500,47.571201,313,5993.392578,12.502000,5.005624,660.500000,651.000000

In [35]:
# List all attributes and methods of the DataFrame
dir(df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_arith_method_with_reindex',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_create_data_for_split_and_tight_to_dict',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_nocopy',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'calworks',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'computer',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'county',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'district',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'english',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'expenditure',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'grades',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'income',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'lunch',
 'map',
 'mask',
 'math',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'read',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rownames',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'school',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'students',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'teachers',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [36]:
print("Mean values of the first 50 records:")
print(df.head(50).mean(numeric_only=True))

Mean values of the first 50 records:
rownames          25.500000
district       66606.320000
students        3597.320000
teachers         173.073599
calworks          23.921212
lunch             83.037800
computer         357.300000
expenditure     5300.675039
income             9.665667
english           44.631484
read             623.932002
math             627.574005
dtype: float64

In [37]:
print("Mean values of the last 50 records:")
print(df.tail(50).mean(numeric_only=True))

Mean values of the last 50 records:
rownames         395.500000
district       68518.300000
students        1557.580000
teachers          81.678840
calworks           2.964096
lunch              9.993326
computer         244.640000
expenditure     5826.156572
income            28.277010
english            4.126526
read             686.290000
math             684.074001
dtype: float64

In [38]:
df.columns

Index(['rownames', 'district', 'school', 'county', 'grades', 'students',
       'teachers', 'calworks', 'lunch', 'computer', 'expenditure', 'income',
       'english', 'read', 'math'],
      dtype='object')

In [39]:
df['rownames'].describe()

count    420.000000
mean     210.500000
std      121.387808
min        1.000000
25%      105.750000
50%      210.500000
75%      315.250000
max      420.000000
Name: rownames, dtype: float64

In [40]:
df['district'].describe()

count      420.000000
mean     67472.809524
std       3466.994655
min      61382.000000
25%      64307.750000
50%      67760.500000
75%      70419.000000
max      75440.000000
Name: district, dtype: float64

In [41]:
df['school']

0                   Sunol Glen Unified
1                 Manzanita Elementary
2          Thermalito Union Elementary
3      Golden Feather Union Elementary
4             Palermo Union Elementary
                    ...
415             Las Lomitas Elementary
416               Los Altos Elementary
417             Somis Union Elementary
418                  Plumas Elementary
419               Wheatland Elementary
Name: school, Length: 420, dtype: object

In [42]:
df['computer'].count()

np.int64(420)

In [43]:
df['expenditure'].count()

np.int64(420)

In [44]:
df['district'].mean()

np.float64(67472.80952380953)

In [45]:
df['rownames'].mean()

np.float64(210.5)

In [46]:
df[10:20]

,rownames,district,school,county,grades,students,teachers,calworks,lunch,computer,expenditure,income,english,read,math
10,11,65722,Le Grand Union Elementary,Merced,KK-08,446,21.000000,18.609900,85.874397,86,4547.692383,8.931,52.914799,612.799988,618.700012
11,12,62174,West Fresno Elementary,Fresno,KK-08,987,47.000000,71.713097,98.605598,56,5447.345215,7.385,54.609932,616.599976,616.000000
12,13,71795,Allensworth Elementary,Tulare,KK-08,103,5.000000,22.429899,98.130798,25,6567.149414,5.335,42.718445,612.799988,619.799988
13,14,72181,Sunnyside Union Elementary,Tulare,KK-08,487,24.340000,24.609400,77.148399,0,4818.612793,8.279,20.533880,610.000000,622.599976
14,15,72298,Woodville Elementary,Tulare,KK-08,649,36.000000,14.637900,76.271202,31,5621.456055,9.630,80.123260,611.900024,621.000000
15,16,72041,Pixley Union Elementary,Tulare,KK-08,852,42.070000,24.214199,94.295700,80,6026.359863,7.454,49.413143,614.799988,619.900024
16,17,63594,Lost Hills Union Elementary,Kern,KK-08,491,28.920000,11.201600,97.759697,100,6723.237793,6.216,85.539719,611.700012,624.400024
17,18,63370,Buttonwillow Union Elementary,Kern,KK-08,421,25.500000,8.551100,77.909698,50,5589.885254,7.764,58.907364,614.900024,621.700012
18,19,64709,Lennox Elementary,Los Angeles,KK-08,6880,303.029999,21.282400,94.971199,960,5064.615723,7.022,77.005814,619.099976,620.500000
19,20,63560,Lamont Elementary,Kern,KK-08,2688,135.000000,23.437500,93.229202,139,5433.593262,5.699,49.813988,621.299988,619.299988

In [47]:
df[10:30]

,rownames,district,school,county,grades,students,teachers,calworks,lunch,computer,expenditure,income,english,read,math
10,11,65722,Le Grand Union Elementary,Merced,KK-08,446,21.000000,18.609900,85.874397,86,4547.692383,8.931000,52.914799,612.799988,618.700012
11,12,62174,West Fresno Elementary,Fresno,KK-08,987,47.000000,71.713097,98.605598,56,5447.345215,7.385000,54.609932,616.599976,616.000000
12,13,71795,Allensworth Elementary,Tulare,KK-08,103,5.000000,22.429899,98.130798,25,6567.149414,5.335000,42.718445,612.799988,619.799988
13,14,72181,Sunnyside Union Elementary,Tulare,KK-08,487,24.340000,24.609400,77.148399,0,4818.612793,8.279000,20.533880,610.000000,622.599976
14,15,72298,Woodville Elementary,Tulare,KK-08,649,36.000000,14.637900,76.271202,31,5621.456055,9.630000,80.123260,611.900024,621.000000
15,16,72041,Pixley Union Elementary,Tulare,KK-08,852,42.070000,24.214199,94.295700,80,6026.359863,7.454000,49.413143,614.799988,619.900024
16,17,63594,Lost Hills Union Elementary,Kern,KK-08,491,28.920000,11.201600,97.759697,100,6723.237793,6.216000,85.539719,611.700012,624.400024
17,18,63370,Buttonwillow Union Elementary,Kern,KK-08,421,25.500000,8.551100,77.909698,50,5589.885254,7.764000,58.907364,614.900024,621.700012
18,19,64709,Lennox Elementary,Los Angeles,KK-08,6880,303.029999,21.282400,94.971199,960,5064.615723,7.022000,77.005814,619.099976,620.500000
19,20,63560,Lamont Elementary,Kern,KK-08,2688,135.000000,23.437500,93.229202,139,5433.593262,5.699000,49.813988,621.299988,619.299988
20,21,63230,Westmorland Union Elementary,Imperial,KK-08,440,24.000000,34.772701,100.000000,69,5725.563477,7.941000,40.681820,615.599976,625.400024
21,22,72058,Pleasant View Elementary,Tulare,KK-08,475,21.000000,21.649500,91.546402,53,4542.104980,9.630000,16.210526,619.900024,622.900024
22,23,63842,Wasco Union Elementary,Kern,KK-08,2538,130.500000,18.911100,70.816704,169,5107.086426,7.405000,45.074863,622.900024,620.599976
23,24,71811,Alta Vista Elementary,Tulare,KK-08,476,19.000000,43.855900,100.000000,0,4659.661621,9.630000,39.075630,620.700012,623.400024
24,25,65748,Livingston Union Elementary,Merced,KK-08,2357,114.000000,16.801001,90.623703,216,4555.464355,8.019000,76.665253,619.500000,625.700012
25,26,72272,Woodlake Union Elementary,Tulare,KK-08,1588,85.000000,22.407200,85.147202,198,5415.152832,8.523000,40.491184,625.000000,621.200012
26,27,65961,Alisal Union Elementary,Monterey,KK-06,7306,319.799988,17.001499,88.034897,742,4997.871582,7.983181,73.720230,620.400024,626.000000
27,28,63313,Arvin Union Elementary,Kern,KK-08,2601,135.000000,15.071100,92.195297,269,5223.912109,7.305000,70.011536,616.500000,630.400024
28,29,72199,Terra Bella Union Elementary,Tulare,KK-08,847,44.000000,16.292801,90.200699,67,5139.164551,8.934000,55.962215,620.099976,627.099976
29,30,72215,Tipton Elementary,Tulare,KK-08,452,22.000000,14.498900,81.023499,55,4614.251953,8.554000,11.061947,627.900024,620.400024

In [48]:
df.loc[10:20,['rownames', 'district', 'school', 'county']]

    rownames  district                         school       county
10        11     65722      Le Grand Union Elementary       Merced
11        12     62174         West Fresno Elementary       Fresno
12        13     71795         Allensworth Elementary       Tulare
13        14     72181     Sunnyside Union Elementary       Tulare
14        15     72298           Woodville Elementary       Tulare
15        16     72041        Pixley Union Elementary       Tulare
16        17     63594    Lost Hills Union Elementary         Kern
17        18     63370  Buttonwillow Union Elementary         Kern
18        19     64709              Lennox Elementary  Los Angeles
19        20     63560              Lamont Elementary         Kern
20        21     63230   Westmorland Union Elementary     Imperial

In [49]:
df.loc[10:20,['grades', 'students','teachers', 'calworks']]

   grades  students    teachers   calworks
10  KK-08       446   21.000000  18.609900
11  KK-08       987   47.000000  71.713097
12  KK-08       103    5.000000  22.429899
13  KK-08       487   24.340000  24.609400
14  KK-08       649   36.000000  14.637900
15  KK-08       852   42.070000  24.214199
16  KK-08       491   28.920000  11.201600
17  KK-08       421   25.500000   8.551100
18  KK-08      6880  303.029999  21.282400
19  KK-08      2688  135.000000  23.437500
20  KK-08       440   24.000000  34.772701

In [50]:
#MISSING VALUE
df.dropna(how='all')

,rownames,district,school,county,grades,students,teachers,calworks,lunch,computer,expenditure,income,english,read,math
0,1,75119,Sunol Glen Unified,Alameda,KK-08,195,10.900000,0.510200,2.040800,67,6384.911133,22.690001,0.000000,691.599976,690.000000
1,2,61499,Manzanita Elementary,Butte,KK-08,240,11.150000,15.416700,47.916698,101,5099.380859,9.824000,4.583333,660.500000,661.900024
2,3,61549,Thermalito Union Elementary,Butte,KK-08,1550,82.900002,55.032299,76.322601,169,5501.954590,8.978000,30.000002,636.299988,650.900024
3,4,61457,Golden Feather Union Elementary,Butte,KK-08,243,14.000000,36.475399,77.049202,85,7101.831055,8.978000,0.000000,651.900024,643.500000
4,5,61523,Palermo Union Elementary,Butte,KK-08,1335,71.500000,33.108601,78.427002,171,5235.987793,9.080333,13.857677,641.799988,639.900024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415,416,68957,Las Lomitas Elementary,San Mateo,KK-08,984,59.730000,0.101600,3.556900,195,7290.338867,28.716999,5.995935,700.900024,707.700012
416,417,69518,Los Altos Elementary,Santa Clara,KK-08,3724,208.479996,1.074100,1.503800,721,5741.462891,41.734108,4.726101,704.000000,709.500000
417,418,72611,Somis Union Elementary,Ventura,KK-08,441,20.150000,3.563500,37.193802,45,4402.831543,23.733000,24.263039,648.299988,641.700012
418,419,72744,Plumas Elementary,Yuba,KK-08,101,5.000000,11.881200,59.405899,14,4776.336426,9.952000,2.970297,667.900024,676.500000
419,420,72751,Wheatland Elementary,Yuba,KK-08,1778,93.400002,6.923500,47.571201,313,5993.392578,12.502000,5.005624,660.500000,651.000000

In [51]:
df.dropna(axis=1, how='all')

,rownames,district,school,county,grades,students,teachers,calworks,lunch,computer,expenditure,income,english,read,math
0,1,75119,Sunol Glen Unified,Alameda,KK-08,195,10.900000,0.510200,2.040800,67,6384.911133,22.690001,0.000000,691.599976,690.000000
1,2,61499,Manzanita Elementary,Butte,KK-08,240,11.150000,15.416700,47.916698,101,5099.380859,9.824000,4.583333,660.500000,661.900024
2,3,61549,Thermalito Union Elementary,Butte,KK-08,1550,82.900002,55.032299,76.322601,169,5501.954590,8.978000,30.000002,636.299988,650.900024
3,4,61457,Golden Feather Union Elementary,Butte,KK-08,243,14.000000,36.475399,77.049202,85,7101.831055,8.978000,0.000000,651.900024,643.500000
4,5,61523,Palermo Union Elementary,Butte,KK-08,1335,71.500000,33.108601,78.427002,171,5235.987793,9.080333,13.857677,641.799988,639.900024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415,416,68957,Las Lomitas Elementary,San Mateo,KK-08,984,59.730000,0.101600,3.556900,195,7290.338867,28.716999,5.995935,700.900024,707.700012
416,417,69518,Los Altos Elementary,Santa Clara,KK-08,3724,208.479996,1.074100,1.503800,721,5741.462891,41.734108,4.726101,704.000000,709.500000
417,418,72611,Somis Union Elementary,Ventura,KK-08,441,20.150000,3.563500,37.193802,45,4402.831543,23.733000,24.263039,648.299988,641.700012
418,419,72744,Plumas Elementary,Yuba,KK-08,101,5.000000,11.881200,59.405899,14,4776.336426,9.952000,2.970297,667.900024,676.500000
419,420,72751,Wheatland Elementary,Yuba,KK-08,1778,93.400002,6.923500,47.571201,313,5993.392578,12.502000,5.005624,660.500000,651.000000

In [52]:
df.min()

rownames                         1
district                     61382
school         Ackerman Elementary
county                     Alameda
grades                       KK-06
students                        81
teachers                      4.85
calworks                       0.0
lunch                          0.0
computer                         0
expenditure             3926.06958
income                       5.335
english                        0.0
read                         604.5
math                    605.400024
dtype: object

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 420 entries, 0 to 419
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   rownames     420 non-null    int64
 1   district     420 non-null    int64
 2   school       420 non-null    object
 3   county       420 non-null    object
 4   grades       420 non-null    object
 5   students     420 non-null    int64
 6   teachers     420 non-null    float64
 7   calworks     420 non-null    float64
 8   lunch        420 non-null    float64
 9   computer     420 non-null    int64
 10  expenditure  420 non-null    float64
 11  income       420 non-null    float64
 12  english      420 non-null    float64
 13  read         420 non-null    float64
 14  math         420 non-null    float64
dtypes: float64(8), int64(4), object(3)
memory usage: 49.3+ KB