In [1]:
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib as mpl
import seaborn as sns
df =pd.read_csv("/content/catholic.csv")

In [4]:
df.head()

,rownames,id,read12,math12,female,asian,hispan,black,motheduc,fatheduc,lfaminc,hsgrad,cathhs,parcath
0,1,124902,61.41,49.77,0,0,0,0,14.0,12.0,10.30895,1.0,0,1
1,2,124915,58.34,59.84,0,0,0,0,14.0,14.0,10.30895,1.0,0,1
2,3,124916,59.33,50.38,1,0,0,0,14.0,11.0,10.30895,1.0,0,1
3,4,124932,49.59,45.03,1,0,0,0,12.0,14.0,10.30895,1.0,0,1
4,5,124944,57.62,54.26,1,0,0,0,12.0,12.0,10.65726,1.0,0,1

In [5]:
df.head(10)

,rownames,id,read12,math12,female,asian,hispan,black,motheduc,fatheduc,lfaminc,hsgrad,cathhs,parcath
0,1,124902,61.41,49.77,0,0,0,0,14.0,12.0,10.308950,1.0,0,1
1,2,124915,58.34,59.84,0,0,0,0,14.0,14.0,10.308950,1.0,0,1
2,3,124916,59.33,50.38,1,0,0,0,14.0,11.0,10.308950,1.0,0,1
3,4,124932,49.59,45.03,1,0,0,0,12.0,14.0,10.308950,1.0,0,1
4,5,124944,57.62,54.26,1,0,0,0,12.0,12.0,10.657260,1.0,0,1
5,6,124947,52.53,56.73,1,0,0,0,12.0,11.0,11.042920,1.0,0,1
6,7,124966,60.12,55.37,1,0,0,0,14.0,14.0,9.433484,1.0,0,1
7,8,124968,64.69,65.07,0,0,0,0,14.0,14.0,10.308950,1.0,0,1
8,9,124972,42.09,53.98,0,0,0,0,14.0,14.0,10.308950,1.0,0,1
9,10,124974,60.23,62.72,0,0,0,0,14.0,12.0,9.769957,1.0,0,1

In [6]:
df.head(20)

,rownames,id,read12,math12,female,asian,hispan,black,motheduc,fatheduc,lfaminc,hsgrad,cathhs,parcath
0,1,124902,61.41,49.77,0,0,0,0,14.0,12.0,10.308950,1.0,0,1
1,2,124915,58.34,59.84,0,0,0,0,14.0,14.0,10.308950,1.0,0,1
2,3,124916,59.33,50.38,1,0,0,0,14.0,11.0,10.308950,1.0,0,1
3,4,124932,49.59,45.03,1,0,0,0,12.0,14.0,10.308950,1.0,0,1
4,5,124944,57.62,54.26,1,0,0,0,12.0,12.0,10.657260,1.0,0,1
5,6,124947,52.53,56.73,1,0,0,0,12.0,11.0,11.042920,1.0,0,1
6,7,124966,60.12,55.37,1,0,0,0,14.0,14.0,9.433484,1.0,0,1
7,8,124968,64.69,65.07,0,0,0,0,14.0,14.0,10.308950,1.0,0,1
8,9,124972,42.09,53.98,0,0,0,0,14.0,14.0,10.308950,1.0,0,1
9,10,124974,60.23,62.72,0,0,0,0,14.0,12.0,9.769957,1.0,0,1
10,11,124981,53.03,46.86,0,0,0,0,12.0,14.0,10.308950,1.0,0,1
11,12,124985,58.25,52.05,1,0,0,0,12.0,11.5,10.657260,1.0,0,1
12,13,124990,63.95,63.86,1,0,0,0,14.0,12.0,10.308950,1.0,0,1
13,14,124992,38.51,61.41,1,0,0,0,14.0,11.0,9.076809,1.0,0,1
14,15,124998,43.15,45.54,1,0,0,0,12.0,12.0,9.769957,1.0,0,1
15,16,175585,60.28,62.50,1,0,0,0,16.0,14.0,10.308950,1.0,0,1
16,17,180607,63.57,58.77,0,0,0,0,12.0,12.0,9.769957,1.0,1,1
17,18,180608,61.73,59.25,0,0,0,0,14.0,16.0,10.308950,1.0,1,0
18,19,180610,55.40,63.43,0,0,0,0,12.0,16.0,10.657260,1.0,1,0
19,20,180625,45.79,51.51,0,0,0,0,12.0,14.0,10.657260,1.0,1,1

In [7]:
df.tail()

,rownames,id,read12,math12,female,asian,hispan,black,motheduc,fatheduc,lfaminc,hsgrad,cathhs,parcath
7425,7426,7957692,42.06,56.60,0,0,1,0,16.0,16.0,10.65726,1.0,1,1
7426,7427,7979017,56.44,56.29,1,0,0,1,14.0,16.0,11.04292,1.0,0,1
7427,7428,7979029,56.02,58.16,1,0,0,0,17.0,16.0,10.65726,1.0,0,0
7428,7429,7979082,65.60,61.14,1,0,0,0,12.0,14.0,10.65726,1.0,0,1
7429,7430,7979086,62.80,63.57,0,0,0,0,14.0,16.0,11.04292,1.0,1,1

In [8]:
df.tail(6)

,rownames,id,read12,math12,female,asian,hispan,black,motheduc,fatheduc,lfaminc,hsgrad,cathhs,parcath
7424,7425,7957688,42.02,47.87,1,0,0,0,12.0,14.0,6.214608,1.0,1,0
7425,7426,7957692,42.06,56.60,0,0,1,0,16.0,16.0,10.657260,1.0,1,1
7426,7427,7979017,56.44,56.29,1,0,0,1,14.0,16.0,11.042920,1.0,0,1
7427,7428,7979029,56.02,58.16,1,0,0,0,17.0,16.0,10.657260,1.0,0,0
7428,7429,7979082,65.60,61.14,1,0,0,0,12.0,14.0,10.657260,1.0,0,1
7429,7430,7979086,62.80,63.57,0,0,0,0,14.0,16.0,11.042920,1.0,1,1

In [9]:
df.min(numeric_only=True)

rownames         1.000000
id          124902.000000
read12          29.150000
math12          29.500000
female           0.000000
asian            0.000000
hispan           0.000000
black            0.000000
motheduc         8.000000
fatheduc         8.000000
lfaminc          6.214608
hsgrad           0.000000
cathhs           0.000000
parcath          0.000000
dtype: float64

In [10]:
df.max(numeric_only=True)

rownames    7.430000e+03
id          7.979086e+06
read12      6.809000e+01
math12      7.137000e+01
female      1.000000e+00
asian       1.000000e+00
hispan      1.000000e+00
black       1.000000e+00
motheduc    1.800000e+01
fatheduc    1.800000e+01
lfaminc     1.234583e+01
hsgrad      1.000000e+00
cathhs      1.000000e+00
parcath     1.000000e+00
dtype: float64

In [11]:
df.dtypes

rownames      int64
id            int64
read12      float64
math12      float64
female        int64
asian         int64
hispan        int64
black         int64
motheduc    float64
fatheduc    float64
lfaminc     float64
hsgrad      float64
cathhs        int64
parcath       int64
dtype: object

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7430 entries, 0 to 7429
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   rownames  7430 non-null   int64
 1   id        7430 non-null   int64
 2   read12    7430 non-null   float64
 3   math12    7430 non-null   float64
 4   female    7430 non-null   int64
 5   asian     7430 non-null   int64
 6   hispan    7430 non-null   int64
 7   black     7430 non-null   int64
 8   motheduc  7430 non-null   float64
 9   fatheduc  7430 non-null   float64
 10  lfaminc   7430 non-null   float64
 11  hsgrad    5970 non-null   float64
 12  cathhs    7430 non-null   int64
 13  parcath   7430 non-null   int64
dtypes: float64(6), int64(8)
memory usage: 812.8 KB

In [13]:
df['female'].dtypes

dtype('int64')

In [14]:
df['read12'].dtypes

dtype('float64')

In [15]:
print(df.axes)

[RangeIndex(start=0, stop=7430, step=1), Index(['rownames', 'id', 'read12', 'math12', 'female', 'asian', 'hispan',
       'black', 'motheduc', 'fatheduc', 'lfaminc', 'hsgrad', 'cathhs',
       'parcath'],
      dtype='object')]

In [16]:
print(df.ndim)

2

In [17]:
print(df.size)

104020

In [18]:
print(df.shape)

(7430, 14)

In [19]:
print(df.values)

[[1.000000e+00 1.249020e+05 6.141000e+01 ... 1.000000e+00 0.000000e+00
  1.000000e+00]
 [2.000000e+00 1.249150e+05 5.834000e+01 ... 1.000000e+00 0.000000e+00
  1.000000e+00]
 [3.000000e+00 1.249160e+05 5.933000e+01 ... 1.000000e+00 0.000000e+00
  1.000000e+00]
 ...
 [7.428000e+03 7.979029e+06 5.602000e+01 ... 1.000000e+00 0.000000e+00
  0.000000e+00]
 [7.429000e+03 7.979082e+06 6.560000e+01 ... 1.000000e+00 0.000000e+00
  1.000000e+00]
 [7.430000e+03 7.979086e+06 6.280000e+01 ... 1.000000e+00 1.000000e+00
  1.000000e+00]]

In [20]:
print("Number of records:", len(df))

Number of records: 7430

In [21]:
print("Number of records:", df.shape[0])

Number of records: 7430

In [22]:
print("Number of elements:", df.size)

Number of elements: 104020

In [23]:
print("Column Names:")
print(df.columns)

Column Names:
Index(['rownames', 'id', 'read12', 'math12', 'female', 'asian', 'hispan',
       'black', 'motheduc', 'fatheduc', 'lfaminc', 'hsgrad', 'cathhs',
       'parcath'],
      dtype='object')

In [24]:
print("Column Data Types:")
print(df.dtypes)

Column Data Types:
rownames      int64
id            int64
read12      float64
math12      float64
female        int64
asian         int64
hispan        int64
black         int64
motheduc    float64
fatheduc    float64
lfaminc     float64
hsgrad      float64
cathhs        int64
parcath       int64
dtype: object

In [25]:
df.describe()

,rownames,id,read12,math12,female,asian,hispan,black,motheduc,fatheduc,lfaminc,hsgrad,cathhs,parcath
count,7430.000000,7.430000e+03,7430.000000,7430.000000,7430.000000,7430.000000,7430.000000,7430.000000,7430.000000,7430.000000,7430.000000,5970.000000,7430.000000,7430.000000
mean,3715.500000,4.589838e+06,51.772402,52.133623,0.517362,0.051682,0.103499,0.070659,13.356864,13.674159,10.353323,0.930318,0.060834,0.345895
std,2145.000583,2.744467e+06,9.407761,9.459117,0.499732,0.221400,0.304630,0.256272,2.005982,2.267797,0.794519,0.254631,0.239042,0.475691
min,1.000000,1.249020e+05,29.150000,29.500000,0.000000,0.000000,0.000000,0.000000,8.000000,8.000000,6.214608,0.000000,0.000000,0.000000
25%,1858.250000,2.424049e+06,44.525000,45.020000,0.000000,0.000000,0.000000,0.000000,12.000000,12.000000,10.021270,1.000000,0.000000,0.000000
50%,3715.500000,4.592442e+06,53.080000,52.530000,1.000000,0.000000,0.000000,0.000000,14.000000,14.000000,10.308950,1.000000,0.000000,0.000000
75%,5572.750000,7.241106e+06,59.470000,59.857500,1.000000,0.000000,0.000000,0.000000,14.000000,16.000000,10.657260,1.000000,0.000000,1.000000
max,7430.000000,7.979086e+06,68.090000,71.370000,1.000000,1.000000,1.000000,1.000000,18.000000,18.000000,12.345830,1.000000,1.000000,1.000000

In [26]:
df.median(numeric_only=True)

rownames    3.715500e+03
id          4.592442e+06
read12      5.308000e+01
math12      5.253000e+01
female      1.000000e+00
asian       0.000000e+00
hispan      0.000000e+00
black       0.000000e+00
motheduc    1.400000e+01
fatheduc    1.400000e+01
lfaminc     1.030895e+01
hsgrad      1.000000e+00
cathhs      0.000000e+00
parcath     0.000000e+00
dtype: float64

In [27]:
df.mean(numeric_only=True)

rownames    3.715500e+03
id          4.589838e+06
read12      5.177240e+01
math12      5.213362e+01
female      5.173620e-01
asian       5.168237e-02
hispan      1.034993e-01
black       7.065949e-02
motheduc    1.335686e+01
fatheduc    1.367416e+01
lfaminc     1.035332e+01
hsgrad      9.303183e-01
cathhs      6.083445e-02
parcath     3.458950e-01
dtype: float64

In [28]:
df.mode(numeric_only=True)

,rownames,id,read12,math12,female,asian,hispan,black,motheduc,fatheduc,lfaminc,hsgrad,cathhs,parcath
0,1,124902,68.09,50.73,1.0,0.0,0.0,0.0,14.0,14.0,10.65726,1.0,0.0,0.0
1,2,124915,NaN,56.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,124916,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,124932,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,124944,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7425,7426,7957692,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7426,7427,7979017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7427,7428,7979029,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7428,7429,7979082,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7429,7430,7979086,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
df.std(numeric_only=True)

rownames    2.145001e+03
id          2.744467e+06
read12      9.407761e+00
math12      9.459117e+00
female      4.997321e-01
asian       2.213999e-01
hispan      3.046304e-01
black       2.562724e-01
motheduc    2.005982e+00
fatheduc    2.267797e+00
lfaminc     7.945188e-01
hsgrad      2.546312e-01
cathhs      2.390425e-01
parcath     4.756912e-01
dtype: float64

In [30]:
df.sample(5)

,rownames,id,read12,math12,female,asian,hispan,black,motheduc,fatheduc,lfaminc,hsgrad,cathhs,parcath
5131,5132,7206528,39.05,47.60,0,0,0,0,12.0,12.0,10.308950,1.0,0,1
5968,5969,7278575,56.92,61.84,0,0,0,0,14.0,14.0,11.042920,1.0,0,1
1756,1757,2413994,38.93,40.35,0,0,0,0,12.0,16.0,10.308950,NaN,0,0
3042,3043,2599037,47.10,41.84,0,0,0,0,14.0,14.0,10.657260,1.0,0,0
4242,4243,6818580,59.15,52.81,0,0,0,0,14.0,11.0,9.433484,0.0,0,0

In [31]:
df.sample(20)

,rownames,id,read12,math12,female,asian,hispan,black,motheduc,fatheduc,lfaminc,hsgrad,cathhs,parcath
1765,1766,2416384,52.86,60.31,0,0,0,0,11.0,12.0,10.021270,1.0,0,0
2037,2038,2477233,47.33,45.23,0,0,0,0,12.0,14.0,9.076809,NaN,0,0
3486,3487,4555548,55.36,56.31,0,0,0,0,14.0,17.0,10.308950,1.0,0,0
7308,7309,7895604,42.25,50.60,0,0,0,0,16.0,12.0,9.076809,1.0,0,0
6740,6741,7810165,66.33,64.11,1,0,0,0,14.0,14.0,10.657260,1.0,0,1
4215,4216,6816021,50.65,54.24,0,0,0,0,14.0,14.0,11.042920,1.0,0,0
6410,6411,7745684,58.12,65.09,1,0,1,0,14.0,14.0,8.294049,1.0,0,0
6877,6878,7821360,51.28,62.79,0,1,0,0,8.0,14.0,10.308950,1.0,0,1
226,227,711781,48.36,37.22,0,0,0,0,14.0,16.0,10.657260,1.0,0,0
2944,2945,2582598,57.10,50.05,1,0,0,0,11.5,16.0,10.308950,NaN,0,0
898,899,758635,42.67,51.14,0,0,0,0,14.0,11.0,9.769957,1.0,0,0
785,786,747526,57.17,54.99,0,0,0,0,14.0,14.0,10.308950,1.0,0,0
3916,3917,4674831,32.07,48.34,1,0,0,0,14.0,14.0,9.769957,1.0,1,1
5649,5650,7248737,58.69,61.86,0,0,0,0,14.0,17.0,10.308950,1.0,0,0
4636,4637,6857717,42.55,37.53,1,0,0,0,16.0,16.0,10.657260,1.0,0,0
3567,3568,4571957,33.90,37.47,1,0,0,0,14.0,16.0,9.433484,1.0,0,0
1642,1643,1481358,60.36,47.27,1,0,0,0,12.0,14.0,10.657260,1.0,0,1
6708,6709,7807796,62.51,63.34,1,0,0,0,17.0,14.0,11.042920,NaN,0,0
851,852,754710,48.43,41.18,1,0,0,0,12.0,12.0,10.308950,NaN,0,1
4384,4385,6835232,35.35,46.34,0,0,0,0,12.0,14.0,10.657260,1.0,0,0

In [32]:
df.dropna()

,rownames,id,read12,math12,female,asian,hispan,black,motheduc,fatheduc,lfaminc,hsgrad,cathhs,parcath
0,1,124902,61.41,49.77,0,0,0,0,14.0,12.0,10.30895,1.0,0,1
1,2,124915,58.34,59.84,0,0,0,0,14.0,14.0,10.30895,1.0,0,1
2,3,124916,59.33,50.38,1,0,0,0,14.0,11.0,10.30895,1.0,0,1
3,4,124932,49.59,45.03,1,0,0,0,12.0,14.0,10.30895,1.0,0,1
4,5,124944,57.62,54.26,1,0,0,0,12.0,12.0,10.65726,1.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7425,7426,7957692,42.06,56.60,0,0,1,0,16.0,16.0,10.65726,1.0,1,1
7426,7427,7979017,56.44,56.29,1,0,0,1,14.0,16.0,11.04292,1.0,0,1
7427,7428,7979029,56.02,58.16,1,0,0,0,17.0,16.0,10.65726,1.0,0,0
7428,7429,7979082,65.60,61.14,1,0,0,0,12.0,14.0,10.65726,1.0,0,1
7429,7430,7979086,62.80,63.57,0,0,0,0,14.0,16.0,11.04292,1.0,1,1

In [33]:
# List all attributes and methods of the DataFrame
dir(df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_arith_method_with_reindex',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_create_data_for_split_and_tight_to_dict',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_nocopy',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'applymap',
 'asfreq',
 'asian',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'black',
 'bool',
 'boxplot',
 'cathhs',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'fatheduc',
 'female',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hispan',
 'hist',
 'hsgrad',
 'iat',
 'id',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'lfaminc',
 'loc',
 'lt',
 'map',
 'mask',
 'math12',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'motheduc',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'parcath',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'read12',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rownames',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [34]:
print("Mean values of the first 50 records:")
print(df.head(50).mean(numeric_only=True))

Mean values of the first 50 records:
rownames        25.500000
id          372598.960000
read12          53.231000
math12          54.248600
female           0.400000
asian            0.020000
hispan           0.040000
black            0.080000
motheduc        13.560000
fatheduc        14.110000
lfaminc         10.365353
hsgrad           0.976190
cathhs           0.280000
parcath          0.620000
dtype: float64

In [35]:
print("Mean values of the last 50 records:")
print(df.tail(50).mean(numeric_only=True))

Mean values of the last 50 records:
rownames    7.405500e+03
id          7.945227e+06
read12      5.210200e+01
math12      5.418300e+01
female      4.000000e-01
asian       2.000000e-02
hispan      2.800000e-01
black       8.000000e-02
motheduc    1.353000e+01
fatheduc    1.441000e+01
lfaminc     1.050385e+01
hsgrad      1.000000e+00
cathhs      8.600000e-01
parcath     8.800000e-01
dtype: float64

In [36]:
df.columns

Index(['rownames', 'id', 'read12', 'math12', 'female', 'asian', 'hispan',
       'black', 'motheduc', 'fatheduc', 'lfaminc', 'hsgrad', 'cathhs',
       'parcath'],
      dtype='object')

In [37]:
df['rownames']

0          1
1          2
2          3
3          4
4          5
        ...
7425    7426
7426    7427
7427    7428
7428    7429
7429    7430
Name: rownames, Length: 7430, dtype: int64

In [38]:
df['read12'].describe()

count    7430.000000
mean       51.772402
std         9.407761
min        29.150000
25%        44.525000
50%        53.080000
75%        59.470000
max        68.090000
Name: read12, dtype: float64

In [39]:
df['motheduc'].describe()

count    7430.000000
mean       13.356864
std         2.005982
min         8.000000
25%        12.000000
50%        14.000000
75%        14.000000
max        18.000000
Name: motheduc, dtype: float64

In [40]:
df['fatheduc'].count()

np.int64(7430)

In [41]:
df['cathhs'].count()

np.int64(7430)

In [42]:
df['hispan'].mean()

np.float64(0.1034993270524899)

In [43]:
df['id'].mean()

np.float64(4589838.270390309)

In [44]:
df[10:20]

,rownames,id,read12,math12,female,asian,hispan,black,motheduc,fatheduc,lfaminc,hsgrad,cathhs,parcath
10,11,124981,53.03,46.86,0,0,0,0,12.0,14.0,10.308950,1.0,0,1
11,12,124985,58.25,52.05,1,0,0,0,12.0,11.5,10.657260,1.0,0,1
12,13,124990,63.95,63.86,1,0,0,0,14.0,12.0,10.308950,1.0,0,1
13,14,124992,38.51,61.41,1,0,0,0,14.0,11.0,9.076809,1.0,0,1
14,15,124998,43.15,45.54,1,0,0,0,12.0,12.0,9.769957,1.0,0,1
15,16,175585,60.28,62.50,1,0,0,0,16.0,14.0,10.308950,1.0,0,1
16,17,180607,63.57,58.77,0,0,0,0,12.0,12.0,9.769957,1.0,1,1
17,18,180608,61.73,59.25,0,0,0,0,14.0,16.0,10.308950,1.0,1,0
18,19,180610,55.40,63.43,0,0,0,0,12.0,16.0,10.657260,1.0,1,0
19,20,180625,45.79,51.51,0,0,0,0,12.0,14.0,10.657260,1.0,1,1

In [45]:
df[10:40]

,rownames,id,read12,math12,female,asian,hispan,black,motheduc,fatheduc,lfaminc,hsgrad,cathhs,parcath
10,11,124981,53.03,46.86,0,0,0,0,12.0,14.0,10.308950,1.0,0,1
11,12,124985,58.25,52.05,1,0,0,0,12.0,11.5,10.657260,1.0,0,1
12,13,124990,63.95,63.86,1,0,0,0,14.0,12.0,10.308950,1.0,0,1
13,14,124992,38.51,61.41,1,0,0,0,14.0,11.0,9.076809,1.0,0,1
14,15,124998,43.15,45.54,1,0,0,0,12.0,12.0,9.769957,1.0,0,1
15,16,175585,60.28,62.50,1,0,0,0,16.0,14.0,10.308950,1.0,0,1
16,17,180607,63.57,58.77,0,0,0,0,12.0,12.0,9.769957,1.0,1,1
17,18,180608,61.73,59.25,0,0,0,0,14.0,16.0,10.308950,1.0,1,0
18,19,180610,55.40,63.43,0,0,0,0,12.0,16.0,10.657260,1.0,1,0
19,20,180625,45.79,51.51,0,0,0,0,12.0,14.0,10.657260,1.0,1,1
20,21,180655,55.56,56.55,0,0,0,0,11.0,14.0,11.042920,1.0,1,1
21,22,180660,52.56,59.69,0,0,0,0,14.0,16.0,10.308950,1.0,1,1
22,23,180672,58.20,50.02,1,0,0,0,14.0,16.0,10.657260,1.0,1,0
23,24,180681,59.28,64.14,0,0,0,0,16.0,17.0,10.657260,1.0,1,1
24,25,180690,63.31,63.50,0,0,0,0,17.0,18.0,10.308950,1.0,1,1
25,26,184603,59.31,48.76,0,0,0,0,12.0,12.0,11.042920,1.0,1,1
26,27,184615,34.19,35.51,0,0,0,0,12.0,12.0,10.021270,NaN,1,1
27,28,184626,54.86,40.68,0,0,0,0,12.0,14.0,10.308950,1.0,1,1
28,29,184670,44.45,45.65,1,0,0,0,14.0,14.0,10.308950,1.0,1,1
29,30,184690,56.92,50.88,0,0,0,0,12.0,12.0,10.657260,1.0,1,1
30,31,700096,48.47,41.75,0,0,1,0,14.0,14.0,8.294049,NaN,0,0
31,32,701120,61.30,63.23,1,0,0,0,12.0,17.0,10.657260,1.0,0,0
32,33,701125,52.52,48.15,1,0,0,0,16.0,17.0,11.042920,NaN,0,0
33,34,701131,42.07,43.12,1,0,0,0,12.0,16.0,8.740336,1.0,0,0
34,35,701158,33.87,42.06,1,0,0,1,12.0,17.0,9.433484,NaN,0,0
35,36,701163,44.17,37.06,1,0,0,0,14.0,14.0,11.042920,1.0,0,0
36,37,701173,48.08,56.52,0,0,0,0,12.0,11.0,9.433484,1.0,0,0
37,38,701178,56.80,64.11,1,0,0,0,14.0,16.0,10.657260,1.0,0,0
38,39,701185,53.04,50.10,0,0,0,0,16.0,16.0,10.308950,NaN,0,0
39,40,701612,62.62,66.26,0,0,0,0,14.0,11.0,10.657260,1.0,0,0

In [46]:
df.loc[10:20,['id', 'read12', 'math12', 'female']]

        id  read12  math12  female
10  124981   53.03   46.86       0
11  124985   58.25   52.05       1
12  124990   63.95   63.86       1
13  124992   38.51   61.41       1
14  124998   43.15   45.54       1
15  175585   60.28   62.50       1
16  180607   63.57   58.77       0
17  180608   61.73   59.25       0
18  180610   55.40   63.43       0
19  180625   45.79   51.51       0
20  180655   55.56   56.55       0

In [47]:
df.loc[10:15,['black', 'motheduc', 'fatheduc']]

    black  motheduc  fatheduc
10      0      12.0      14.0
11      0      12.0      11.5
12      0      14.0      12.0
13      0      14.0      11.0
14      0      12.0      12.0
15      0      16.0      14.0

In [48]:
#MISSING VALUE
df.dropna(how='all')

,rownames,id,read12,math12,female,asian,hispan,black,motheduc,fatheduc,lfaminc,hsgrad,cathhs,parcath
0,1,124902,61.41,49.77,0,0,0,0,14.0,12.0,10.30895,1.0,0,1
1,2,124915,58.34,59.84,0,0,0,0,14.0,14.0,10.30895,1.0,0,1
2,3,124916,59.33,50.38,1,0,0,0,14.0,11.0,10.30895,1.0,0,1
3,4,124932,49.59,45.03,1,0,0,0,12.0,14.0,10.30895,1.0,0,1
4,5,124944,57.62,54.26,1,0,0,0,12.0,12.0,10.65726,1.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7425,7426,7957692,42.06,56.60,0,0,1,0,16.0,16.0,10.65726,1.0,1,1
7426,7427,7979017,56.44,56.29,1,0,0,1,14.0,16.0,11.04292,1.0,0,1
7427,7428,7979029,56.02,58.16,1,0,0,0,17.0,16.0,10.65726,1.0,0,0
7428,7429,7979082,65.60,61.14,1,0,0,0,12.0,14.0,10.65726,1.0,0,1
7429,7430,7979086,62.80,63.57,0,0,0,0,14.0,16.0,11.04292,1.0,1,1

In [49]:
df.dropna(axis=1, how='all')

,rownames,id,read12,math12,female,asian,hispan,black,motheduc,fatheduc,lfaminc,hsgrad,cathhs,parcath
0,1,124902,61.41,49.77,0,0,0,0,14.0,12.0,10.30895,1.0,0,1
1,2,124915,58.34,59.84,0,0,0,0,14.0,14.0,10.30895,1.0,0,1
2,3,124916,59.33,50.38,1,0,0,0,14.0,11.0,10.30895,1.0,0,1
3,4,124932,49.59,45.03,1,0,0,0,12.0,14.0,10.30895,1.0,0,1
4,5,124944,57.62,54.26,1,0,0,0,12.0,12.0,10.65726,1.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7425,7426,7957692,42.06,56.60,0,0,1,0,16.0,16.0,10.65726,1.0,1,1
7426,7427,7979017,56.44,56.29,1,0,0,1,14.0,16.0,11.04292,1.0,0,1
7427,7428,7979029,56.02,58.16,1,0,0,0,17.0,16.0,10.65726,1.0,0,0
7428,7429,7979082,65.60,61.14,1,0,0,0,12.0,14.0,10.65726,1.0,0,1
7429,7430,7979086,62.80,63.57,0,0,0,0,14.0,16.0,11.04292,1.0,1,1

In [50]:
df.min()

rownames         1.000000
id          124902.000000
read12          29.150000
math12          29.500000
female           0.000000
asian            0.000000
hispan           0.000000
black            0.000000
motheduc         8.000000
fatheduc         8.000000
lfaminc          6.214608
hsgrad           0.000000
cathhs           0.000000
parcath          0.000000
dtype: float64

In [51]:
df.max()

rownames    7.430000e+03
id          7.979086e+06
read12      6.809000e+01
math12      7.137000e+01
female      1.000000e+00
asian       1.000000e+00
hispan      1.000000e+00
black       1.000000e+00
motheduc    1.800000e+01
fatheduc    1.800000e+01
lfaminc     1.234583e+01
hsgrad      1.000000e+00
cathhs      1.000000e+00
parcath     1.000000e+00
dtype: float64

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7430 entries, 0 to 7429
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   rownames  7430 non-null   int64
 1   id        7430 non-null   int64
 2   read12    7430 non-null   float64
 3   math12    7430 non-null   float64
 4   female    7430 non-null   int64
 5   asian     7430 non-null   int64
 6   hispan    7430 non-null   int64
 7   black     7430 non-null   int64
 8   motheduc  7430 non-null   float64
 9   fatheduc  7430 non-null   float64
 10  lfaminc   7430 non-null   float64
 11  hsgrad    5970 non-null   float64
 12  cathhs    7430 non-null   int64
 13  parcath   7430 non-null   int64
dtypes: float64(6), int64(8)
memory usage: 812.8 KB