In [1]:
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib as mpl
import seaborn as sns
df =pd.read_csv("/content/countymurders.csv")

In [4]:
df.head()

,rownames,arrests,countyid,density,popul,perc1019,perc2029,percblack,percmale,rpcincmaint,...,rpcunemins,year,murders,murdrate,arrestrate,statefips,countyfips,execs,lpopul,execrate
0,1,2.0,1001,54.05,32216,20.63,15.28,22.33,40.25,167.67,...,29.16,1980,2,0.620810,0.620810,1,1,0,10.38022,0.0
1,2,3.0,1001,53.66,31984,20.19,15.55,22.07,40.36,167.99,...,43.92,1981,1,0.312656,0.937969,1,1,0,10.37299,0.0
2,3,2.0,1001,53.75,32036,19.66,15.73,21.80,40.42,166.63,...,71.41,1982,3,0.936446,0.624298,1,1,0,10.37462,0.0
3,4,7.0,1001,53.78,32056,19.10,15.88,21.53,40.47,176.53,...,72.22,1983,7,2.183679,2.183679,1,1,0,10.37524,0.0
4,5,3.0,1001,53.91,32128,18.54,15.92,21.26,40.51,166.25,...,40.36,1984,2,0.622510,0.933765,1,1,0,10.37748,0.0

In [5]:
df.head(23)

,rownames,arrests,countyid,density,popul,perc1019,perc2029,percblack,percmale,rpcincmaint,...,rpcunemins,year,murders,murdrate,arrestrate,statefips,countyfips,execs,lpopul,execrate
0,1,2.0,1001,54.05000,32216,20.63000,15.28000,22.33000,40.25000,167.670,...,29.160,1980,2,0.620810,0.620810,1,1,0,10.38022,0.0
1,2,3.0,1001,53.66000,31984,20.19000,15.55000,22.07000,40.36000,167.990,...,43.920,1981,1,0.312656,0.937969,1,1,0,10.37299,0.0
2,3,2.0,1001,53.75000,32036,19.66000,15.73000,21.80000,40.42000,166.630,...,71.410,1982,3,0.936446,0.624298,1,1,0,10.37462,0.0
3,4,7.0,1001,53.78000,32056,19.10000,15.88000,21.53000,40.47000,176.530,...,72.220,1983,7,2.183679,2.183679,1,1,0,10.37524,0.0
4,5,3.0,1001,53.91000,32128,18.54000,15.92000,21.26000,40.51000,166.250,...,40.360,1984,2,0.622510,0.933765,1,1,0,10.37748,0.0
5,6,1.0,1001,54.11000,32248,18.06000,15.87000,20.96000,40.45000,153.120,...,44.540,1985,2,0.620193,0.310097,1,1,0,10.38121,0.0
6,7,1.0,1001,55.18000,32888,17.68000,15.66000,20.72000,40.41000,151.560,...,38.350,1986,4,1.216249,0.304062,1,1,0,10.40086,0.0
7,8,2.0,1001,55.81000,33264,17.40000,15.33000,20.49000,40.43000,141.680,...,35.200,1987,1,0.300625,0.601251,1,1,0,10.41223,0.0
8,9,0.0,1001,56.43000,33632,17.25000,14.93000,20.31000,40.42000,148.900,...,27.070,1988,0,0.000000,0.000000,1,1,0,10.42323,0.0
9,10,5.0,1001,57.03000,33992,17.02000,14.55000,20.12000,40.46000,156.560,...,34.700,1989,3,0.882561,1.470934,1,1,0,10.43388,0.0
10,11,0.0,1001,57.91000,34512,16.76000,14.34000,20.19000,40.46000,171.580,...,39.830,1990,1,0.289754,0.000000,1,1,0,10.44906,0.0
11,12,1.0,1001,58.76000,35024,16.51000,14.14000,20.27000,40.48000,176.160,...,44.040,1991,1,0.285519,0.285519,1,1,0,10.46379,0.0
12,13,5.0,1001,59.66000,35560,16.26000,13.96000,20.34000,40.51000,200.350,...,49.910,1992,1,0.281215,1.406074,1,1,0,10.47898,0.0
13,14,3.0,1001,62.12483,37027,16.09366,13.76023,20.48505,48.68339,202.756,...,41.520,1993,1,0.270073,0.810220,1,1,0,10.51940,0.0
14,15,4.0,1001,63.80266,38027,16.02809,13.51934,20.64849,48.71013,199.125,...,27.675,1994,1,0.262971,1.051884,1,1,0,10.54605,0.0
15,16,5.0,1001,65.36304,38957,15.96889,13.33522,20.87686,48.72552,197.456,...,31.488,1995,5,1.283466,1.283466,1,1,0,10.57021,0.0
16,17,8.0,1001,67.21535,40061,15.89077,13.17491,20.97551,48.70073,192.038,...,26.796,1996,7,1.747335,1.996955,1,1,0,10.59816,0.0
17,18,4.0,1003,49.45000,78944,17.98000,14.95000,15.22000,40.55000,132.430,...,25.510,1980,4,0.506688,0.506688,1,3,0,11.27649,0.0
18,19,9.0,1003,50.29000,80288,17.53000,15.02000,14.93000,40.71000,121.880,...,20.860,1981,6,0.747310,1.120965,1,3,0,11.29338,0.0
19,20,8.0,1003,51.56000,82320,17.03000,15.03000,14.63000,40.84000,107.640,...,30.010,1982,7,0.850340,0.971817,1,3,0,11.31837,0.0
20,21,5.0,1003,52.59000,83968,16.56000,14.98000,14.33000,40.99000,108.320,...,32.100,1983,4,0.476372,0.595465,1,3,0,11.33819,0.0
21,22,3.0,1003,54.34000,86752,16.06000,14.86000,14.06000,41.03000,102.830,...,24.020,1984,8,0.922169,0.345813,1,3,0,11.37081,0.0
22,23,2.0,1003,55.99000,89392,15.67000,14.67000,13.81000,41.07000,97.440,...,37.120,1985,7,0.783068,0.223734,1,3,0,11.40079,0.0

In [6]:
df.head(12)

,rownames,arrests,countyid,density,popul,perc1019,perc2029,percblack,percmale,rpcincmaint,...,rpcunemins,year,murders,murdrate,arrestrate,statefips,countyfips,execs,lpopul,execrate
0,1,2.0,1001,54.05,32216,20.63,15.28,22.33,40.25,167.67,...,29.16,1980,2,0.620810,0.620810,1,1,0,10.38022,0.0
1,2,3.0,1001,53.66,31984,20.19,15.55,22.07,40.36,167.99,...,43.92,1981,1,0.312656,0.937969,1,1,0,10.37299,0.0
2,3,2.0,1001,53.75,32036,19.66,15.73,21.80,40.42,166.63,...,71.41,1982,3,0.936446,0.624298,1,1,0,10.37462,0.0
3,4,7.0,1001,53.78,32056,19.10,15.88,21.53,40.47,176.53,...,72.22,1983,7,2.183679,2.183679,1,1,0,10.37524,0.0
4,5,3.0,1001,53.91,32128,18.54,15.92,21.26,40.51,166.25,...,40.36,1984,2,0.622510,0.933765,1,1,0,10.37748,0.0
5,6,1.0,1001,54.11,32248,18.06,15.87,20.96,40.45,153.12,...,44.54,1985,2,0.620193,0.310097,1,1,0,10.38121,0.0
6,7,1.0,1001,55.18,32888,17.68,15.66,20.72,40.41,151.56,...,38.35,1986,4,1.216249,0.304062,1,1,0,10.40086,0.0
7,8,2.0,1001,55.81,33264,17.40,15.33,20.49,40.43,141.68,...,35.20,1987,1,0.300625,0.601251,1,1,0,10.41223,0.0
8,9,0.0,1001,56.43,33632,17.25,14.93,20.31,40.42,148.90,...,27.07,1988,0,0.000000,0.000000,1,1,0,10.42323,0.0
9,10,5.0,1001,57.03,33992,17.02,14.55,20.12,40.46,156.56,...,34.70,1989,3,0.882561,1.470934,1,1,0,10.43388,0.0
10,11,0.0,1001,57.91,34512,16.76,14.34,20.19,40.46,171.58,...,39.83,1990,1,0.289754,0.000000,1,1,0,10.44906,0.0
11,12,1.0,1001,58.76,35024,16.51,14.14,20.27,40.48,176.16,...,44.04,1991,1,0.285519,0.285519,1,1,0,10.46379,0.0

In [7]:
df.tail()

,rownames,arrests,countyid,density,popul,perc1019,perc2029,percblack,percmale,rpcincmaint,...,rpcunemins,year,murders,murdrate,arrestrate,statefips,countyfips,execs,lpopul,execrate
37344,37345,0.0,56045,2.680000,6430,16.35000,10.260000,0.060000,42.67000,95.540,...,54.190,1992,0,0.0,0.00000,56,45,0,8.768730,0.0
37345,37346,1.0,56045,2.708031,6493,16.67950,9.610350,0.077006,50.13091,107.260,...,42.904,1993,0,0.0,1.54012,56,45,0,8.778480,0.0
37346,37347,0.0,56045,2.736391,6561,16.79622,9.510745,0.030483,50.16004,98.550,...,39.150,1994,0,0.0,0.00000,56,45,0,8.788898,0.0
37347,37348,0.0,56045,2.730135,6546,17.01803,9.563092,0.076383,50.18332,106.928,...,38.048,1995,0,0.0,0.00000,56,45,0,8.786610,0.0
37348,37349,0.0,56045,2.733472,6554,16.90571,9.642966,0.076289,50.13732,116.116,...,40.194,1996,0,0.0,0.00000,56,45,0,8.787830,0.0

In [8]:
df.tail(43)

,rownames,arrests,countyid,density,popul,perc1019,perc2029,percblack,percmale,rpcincmaint,...,rpcunemins,year,murders,murdrate,arrestrate,statefips,countyfips,execs,lpopul,execrate
37306,37307,0.0,56041,9.410000,19592,19.12000,12.870000,0.130000,39.25000,63.450,...,60.910,1988,2,1.020825,0.000000,56,41,0,9.882876,0.000000
37307,37308,0.0,56041,9.230000,19212,19.78000,12.330000,0.140000,39.50000,65.370,...,57.300,1989,1,0.520508,0.000000,56,41,0,9.863291,0.000000
37308,37309,0.0,56041,9.260000,19264,20.23000,12.160000,0.130000,39.85000,75.830,...,42.900,1990,0,0.000000,0.000000,56,41,0,9.865993,0.000000
37309,37310,1.0,56041,9.280000,19312,20.70000,11.960000,0.130000,40.19000,87.350,...,52.850,1991,1,0.517813,0.517813,56,41,0,9.868482,0.000000
37310,37311,0.0,56041,9.310000,19384,21.15000,11.780000,0.130000,40.53000,94.120,...,80.570,1992,0,0.000000,0.000000,56,41,1,9.872203,0.515889
37311,37312,0.0,56041,9.494265,19762,21.66279,11.066690,0.197348,51.11831,112.104,...,76.120,1993,1,0.506022,0.000000,56,41,0,9.891516,0.000000
37312,37313,3.0,56041,9.691241,20172,21.90660,11.049970,0.193337,51.15507,122.175,...,56.025,1994,3,1.487210,1.487210,56,41,0,9.912051,0.000000
37313,37314,0.0,56041,9.688358,20166,22.11147,11.152430,0.208271,51.14053,113.488,...,51.824,1995,0,0.000000,0.000000,56,41,0,9.911754,0.000000
37314,37315,0.0,56041,9.731116,20255,22.14268,11.335470,0.192545,51.12812,115.478,...,56.782,1996,0,0.000000,0.000000,56,41,0,9.916157,0.000000
37315,37316,0.0,56043,4.280000,9590,18.34000,17.070000,0.100000,42.16000,78.970,...,24.300,1980,0,0.000000,0.000000,56,43,0,9.168476,0.000000
37316,37317,1.0,56043,4.430000,9926,17.89000,16.530000,0.100000,41.96000,68.080,...,29.650,1981,1,1.007455,1.007455,56,43,0,9.202913,0.000000
37317,37318,1.0,56043,4.530000,10138,17.40000,15.930000,0.110000,41.84000,69.340,...,67.270,1982,2,1.972776,0.986388,56,43,0,9.224046,0.000000
37318,37319,0.0,56043,4.470000,10008,17.13000,15.020000,0.100000,41.50000,89.270,...,128.380,1983,0,0.000000,0.000000,56,43,0,9.211140,0.000000
37319,37320,0.0,56043,4.470000,10004,16.80000,14.200000,0.100000,41.41000,90.330,...,32.670,1984,0,0.000000,0.000000,56,43,0,9.210740,0.000000
37320,37321,0.0,56043,4.360000,9758,16.57000,13.380000,0.150000,41.42000,86.300,...,54.750,1985,0,0.000000,0.000000,56,43,0,9.185843,0.000000
37321,37322,0.0,56043,4.310000,9660,16.55000,12.420000,0.160000,41.39000,73.040,...,111.390,1986,0,0.000000,0.000000,56,43,0,9.175749,0.000000
37322,37323,0.0,56043,4.080000,9140,16.59000,11.540000,0.160000,41.47000,78.320,...,81.840,1987,0,0.000000,0.000000,56,43,0,9.120416,0.000000
37323,37324,0.0,56043,3.950000,8856,16.55000,10.820000,0.160000,41.69000,89.680,...,48.220,1988,0,0.000000,0.000000,56,43,0,9.088850,0.000000
37324,37325,0.0,56043,3.800000,8502,16.66000,10.250000,0.180000,42.02000,82.310,...,46.810,1989,0,0.000000,0.000000,56,43,0,9.048057,0.000000
37325,37326,0.0,56043,3.750000,8398,16.89000,10.040000,0.180000,42.34000,87.320,...,36.000,1990,0,0.000000,0.000000,56,43,0,9.035748,0.000000
37326,37327,0.0,56043,3.700000,8296,17.11000,9.820000,0.180000,42.67000,102.760,...,39.640,1991,0,0.000000,0.000000,56,43,0,9.023529,0.000000
37327,37328,0.0,56043,3.660000,8204,17.31000,9.620000,0.180000,42.99000,116.220,...,65.600,1992,0,0.000000,0.000000,56,43,0,9.012377,0.000000
37328,37329,0.0,56043,3.797506,8507,17.53850,8.875044,0.188080,50.46432,114.872,...,69.200,1993,0,0.000000,0.000000,56,43,0,9.048645,0.000000
37329,37330,0.0,56043,3.819826,8557,17.52951,8.928363,0.233727,50.55510,107.325,...,49.950,1994,0,0.000000,0.000000,56,43,0,9.054505,0.000000
37330,37331,1.0,56043,3.842592,8608,17.66961,9.072955,0.232342,50.53439,118.080,...,59.696,1995,1,1.161710,1.161710,56,43,0,9.060448,0.000000
37331,37332,0.0,56043,3.846610,8617,17.70918,9.121504,0.243704,50.76012,125.048,...,52.316,1996,0,0.000000,0.000000,56,43,0,9.061492,0.000000
37332,37333,1.0,56045,3.000000,7193,16.96000,18.530000,0.080000,41.43000,49.810,...,32.800,1980,1,1.390241,1.390241,56,45,0,8.880863,0.000000
37333,37334,1.0,56045,3.130000,7508,16.59000,17.900000,0.080000,41.29000,43.920,...,39.530,1981,1,1.331913,1.331913,56,45,0,8.923724,0.000000
37334,37335,1.0,56045,3.250000,7789,16.16000,17.130000,0.080000,41.23000,43.470,...,96.250,1982,1,1.283862,1.283862,56,45,0,8.960467,0.000000
37335,37336,0.0,56045,3.260000,7807,15.98000,16.170000,0.060000,40.93000,54.160,...,175.520,1983,0,0.000000,0.000000,56,45,0,8.962776,0.000000
37336,37337,0.0,56045,3.270000,7852,15.68000,15.250000,0.060000,40.83000,52.850,...,49.970,1984,0,0.000000,0.000000,56,45,0,8.968524,0.000000
37337,37338,0.0,56045,3.240000,7777,15.48000,14.350000,0.060000,40.98000,51.970,...,52.900,1985,0,0.000000,0.000000,56,45,0,8.958926,0.000000
37338,37339,0.0,56045,3.170000,7594,15.45000,13.330000,0.070000,40.93000,59.340,...,100.430,1986,0,0.000000,0.000000,56,45,0,8.935114,0.000000
37339,37340,0.0,56045,3.030000,7254,15.56000,12.310000,0.070000,41.01000,73.040,...,66.880,1987,0,0.000000,0.000000,56,45,0,8.889308,0.000000
37340,37341,0.0,56045,2.850000,6842,15.54000,11.590000,0.060000,41.26000,82.910,...,44.840,1988,0,0.000000,0.000000,56,45,0,8.830835,0.000000
37341,37342,0.0,56045,2.780000,6676,15.69000,10.950000,0.060000,41.65000,83.120,...,42.770,1989,0,0.000000,0.000000,56,45,0,8.806274,0.000000
37342,37343,0.0,56045,2.750000,6591,15.93000,10.730000,0.060000,42.01000,76.600,...,34.470,1990,0,0.000000,0.000000,56,45,0,8.793460,0.000000
37343,37344,0.0,56045,2.710000,6507,16.15000,10.480000,0.060000,42.35000,86.610,...,41.100,1991,0,0.000000,0.000000,56,45,0,8.780634,0.000000
37344,37345,0.0,56045,2.680000,6430,16.35000,10.260000,0.060000,42.67000,95.540,...,54.190,1992,0,0.000000,0.000000,56,45,0,8.768730,0.000000
37345,37346,1.0,56045,2.708031,6493,16.67950,9.610350,0.077006,50.13091,107.260,...,42.904,1993,0,0.000000,1.540120,56,45,0,8.778480,0.000000
37346,37347,0.0,56045,2.736391,6561,16.79622,9.510745,0.030483,50.16004,98.550,...,39.150,1994,0,0.000000,0.000000,56,45,0,8.788898,0.000000
37347,37348,0.0,56045,2.730135,6546,17.01803,9.563092,0.076383,50.18332,106.928,...,38.048,1995,0,0.000000,0.000000,56,45,0,8.786610,0.000000
37348,37349,0.0,56045,2.733472,6554,16.90571,9.642966,0.076289,50.13732,116.116,...,40.194,1996,0,0.000000,0.000000,56,45,0,8.787830,0.000000

In [9]:
df.min(numeric_only=True)

rownames          1.000000
arrests           0.000000
countyid       1001.000000
density           0.050000
popul            85.000000
perc1019          7.080000
perc2029          5.617244
percblack         0.000000
percmale         35.150000
rpcincmaint       5.490000
rpcpersinc     3477.760000
rpcunemins        0.000000
year           1980.000000
murders           0.000000
murdrate          0.000000
arrestrate        0.000000
statefips         1.000000
countyfips        1.000000
execs             0.000000
lpopul            4.442651
execrate          0.000000
dtype: float64

In [10]:
df.max(numeric_only=True)

rownames       3.734900e+04
arrests        2.391000e+03
countyid       5.604500e+04
density        5.405877e+04
popul          9.127751e+06
perc1019       3.048458e+01
perc2029       4.052000e+01
percblack      8.627934e+01
percmale       7.804000e+01
rpcincmaint    1.306496e+03
rpcpersinc     4.109422e+04
rpcunemins     6.427300e+02
year           1.996000e+03
murders        1.944000e+03
murdrate       3.984064e+01
arrestrate     1.486584e+02
statefips      5.600000e+01
countyfips     8.400000e+02
execs          7.000000e+00
lpopul         1.602683e+01
execrate       2.388916e+00
dtype: float64

In [11]:
df.dtypes

rownames         int64
arrests        float64
countyid         int64
density        float64
popul            int64
perc1019       float64
perc2029       float64
percblack      float64
percmale       float64
rpcincmaint    float64
rpcpersinc     float64
rpcunemins     float64
year             int64
murders          int64
murdrate       float64
arrestrate     float64
statefips        int64
countyfips       int64
execs            int64
lpopul         float64
execrate       float64
dtype: object

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37349 entries, 0 to 37348
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   rownames     37349 non-null  int64
 1   arrests      36845 non-null  float64
 2   countyid     37349 non-null  int64
 3   density      37349 non-null  float64
 4   popul        37349 non-null  int64
 5   perc1019     37349 non-null  float64
 6   perc2029     37349 non-null  float64
 7   percblack    37349 non-null  float64
 8   percmale     37349 non-null  float64
 9   rpcincmaint  37346 non-null  float64
 10  rpcpersinc   37346 non-null  float64
 11  rpcunemins   37346 non-null  float64
 12  year         37349 non-null  int64
 13  murders      37349 non-null  int64
 14  murdrate     37349 non-null  float64
 15  arrestrate   36845 non-null  float64
 16  statefips    37349 non-null  int64
 17  countyfips   37349 non-null  int64
 18  execs        37349 non-null  int64
 19  lpopul       37349 non-null  float64
 20  execrate     37349 non-null  float64
dtypes: float64(13), int64(8)
memory usage: 6.0 MB

In [13]:
df['rownames'].dtypes

dtype('int64')

In [14]:
df['density'].dtypes

dtype('float64')

In [15]:
print(df.axes)

[RangeIndex(start=0, stop=37349, step=1), Index(['rownames', 'arrests', 'countyid', 'density', 'popul', 'perc1019',
       'perc2029', 'percblack', 'percmale', 'rpcincmaint', 'rpcpersinc',
       'rpcunemins', 'year', 'murders', 'murdrate', 'arrestrate', 'statefips',
       'countyfips', 'execs', 'lpopul', 'execrate'],
      dtype='object')]

In [16]:
print(df.ndim)

2

In [17]:
print(df.size)

784329

In [18]:
print(df.shape)

(37349, 21)

In [19]:
print(df.values)

[[1.000000e+00 2.000000e+00 1.001000e+03 ... 0.000000e+00 1.038022e+01
  0.000000e+00]
 [2.000000e+00 3.000000e+00 1.001000e+03 ... 0.000000e+00 1.037299e+01
  0.000000e+00]
 [3.000000e+00 2.000000e+00 1.001000e+03 ... 0.000000e+00 1.037462e+01
  0.000000e+00]
 ...
 [3.734700e+04 0.000000e+00 5.604500e+04 ... 0.000000e+00 8.788898e+00
  0.000000e+00]
 [3.734800e+04 0.000000e+00 5.604500e+04 ... 0.000000e+00 8.786610e+00
  0.000000e+00]
 [3.734900e+04 0.000000e+00 5.604500e+04 ... 0.000000e+00 8.787830e+00
  0.000000e+00]]

In [20]:
print("Number of records:", len(df))

Number of records: 37349

In [21]:
print("Number of records:", df.shape[0])

Number of records: 37349

In [22]:
print("Number of elements:", df.size)

Number of elements: 784329

In [23]:
print("Column Names:")
print(df.columns)

Column Names:
Index(['rownames', 'arrests', 'countyid', 'density', 'popul', 'perc1019',
       'perc2029', 'percblack', 'percmale', 'rpcincmaint', 'rpcpersinc',
       'rpcunemins', 'year', 'murders', 'murdrate', 'arrestrate', 'statefips',
       'countyfips', 'execs', 'lpopul', 'execrate'],
      dtype='object')

In [24]:
print("Column Data Types:")
print(df.dtypes)

Column Data Types:
rownames         int64
arrests        float64
countyid         int64
density        float64
popul            int64
perc1019       float64
perc2029       float64
percblack      float64
percmale       float64
rpcincmaint    float64
rpcpersinc     float64
rpcunemins     float64
year             int64
murders          int64
murdrate       float64
arrestrate     float64
statefips        int64
countyfips       int64
execs            int64
lpopul         float64
execrate       float64
dtype: object

In [25]:
df.describe()

,rownames,arrests,countyid,density,popul,perc1019,perc2029,percblack,percmale,rpcincmaint,...,rpcunemins,year,murders,murdrate,arrestrate,statefips,countyfips,execs,lpopul,execrate
count,37349.000000,36845.000000,37349.000000,37349.000000,3.734900e+04,37349.000000,37349.000000,37349.000000,37349.000000,37346.000000,...,37346.000000,37349.000000,37349.000000,37349.000000,36845.000000,37349.000000,37349.000000,37349.000000,37349.000000,37349.000000
mean,18675.000000,6.782250,32921.927173,252.241067,8.934354e+04,15.582640,14.584615,7.823194,43.350958,165.450844,...,70.557953,1988.000000,7.286915,0.508202,0.511486,32.821575,100.352299,0.006854,10.347289,0.001042
std,10781.871939,50.128657,15528.352966,1663.768484,2.718545e+05,1.973399,3.696407,13.287067,3.717612,97.488961,...,52.909393,4.899045,47.217586,0.851044,1.232562,15.503684,107.942699,0.112448,1.327145,0.029068
min,1.000000,0.000000,1001.000000,0.050000,8.500000e+01,7.080000,5.617244,0.000000,35.150000,5.490000,...,0.000000,1980.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,4.442651,0.000000
25%,9338.000000,0.000000,20105.000000,17.681580,1.314400e+04,14.320000,12.301700,0.200000,40.900000,96.250000,...,35.200000,1984.000000,0.000000,0.000000,0.000000,20.000000,33.000000,0.000000,9.483721,0.000000
50%,18675.000000,1.000000,36065.000000,44.240000,2.879200e+04,15.420000,14.270000,1.450000,41.810000,145.147500,...,57.100000,1988.000000,1.000000,0.241044,0.163677,36.000000,75.000000,0.000000,10.267850,0.000000
75%,28012.000000,3.000000,48049.000000,106.600000,6.648000e+04,16.730000,16.200000,8.740000,45.870000,209.880000,...,89.958000,1992.000000,3.000000,0.735294,0.701715,48.000000,127.000000,0.000000,11.104660,0.000000
max,37349.000000,2391.000000,56045.000000,54058.770000,9.127751e+06,30.484580,40.520000,86.279340,78.040000,1306.496000,...,642.730000,1996.000000,1944.000000,39.840640,148.658400,56.000000,840.000000,7.000000,16.026830,2.388916

In [26]:
df.median(numeric_only=True)

rownames       18675.000000
arrests            1.000000
countyid       36065.000000
density           44.240000
popul          28792.000000
perc1019          15.420000
perc2029          14.270000
percblack          1.450000
percmale          41.810000
rpcincmaint      145.147500
rpcpersinc     10907.500000
rpcunemins        57.100000
year            1988.000000
murders            1.000000
murdrate           0.241044
arrestrate         0.163677
statefips         36.000000
countyfips        75.000000
execs              0.000000
lpopul            10.267850
execrate           0.000000
dtype: float64

In [27]:
df.mean(numeric_only=True)

rownames       18675.000000
arrests            6.782250
countyid       32921.927173
density          252.241067
popul          89343.541219
perc1019          15.582640
perc2029          14.584615
percblack          7.823194
percmale          43.350958
rpcincmaint      165.450844
rpcpersinc     11272.291175
rpcunemins        70.557953
year            1988.000000
murders            7.286915
murdrate           0.508202
arrestrate         0.511486
statefips         32.821575
countyfips       100.352299
execs              0.006854
lpopul            10.347289
execrate           0.001042
dtype: float64

In [28]:
df.mode(numeric_only=True)

,rownames,arrests,countyid,density,popul,perc1019,perc2029,percblack,percmale,rpcincmaint,...,rpcunemins,year,murders,murdrate,arrestrate,statefips,countyfips,execs,lpopul,execrate
0,1,0.0,1001.0,1.76,35000.0,15.0,14.58,0.04,41.04,97.29,...,51.04,1980.0,0.0,0.0,0.0,48.0,1.0,0.0,10.4631,0.0
1,2,NaN,1003.0,NaN,NaN,NaN,14.69,NaN,NaN,NaN,...,NaN,1981.0,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN
2,3,NaN,1005.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1982.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,NaN,1009.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1983.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,NaN,1011.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1984.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37344,37345,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37345,37346,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37346,37347,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37347,37348,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37348,37349,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
df.std(numeric_only=True)

rownames        10781.871939
arrests            50.128657
countyid        15528.352966
density          1663.768484
popul          271854.498963
perc1019            1.973399
perc2029            3.696407
percblack          13.287067
percmale            3.717612
rpcincmaint        97.488961
rpcpersinc       2680.746508
rpcunemins         52.909393
year                4.899045
murders            47.217586
murdrate            0.851044
arrestrate          1.232562
statefips          15.503684
countyfips        107.942699
execs               0.112448
lpopul              1.327145
execrate            0.029068
dtype: float64

In [30]:
df.sample(5)

,rownames,arrests,countyid,density,popul,perc1019,perc2029,percblack,percmale,rpcincmaint,...,rpcunemins,year,murders,murdrate,arrestrate,statefips,countyfips,execs,lpopul,execrate
20519,20520,3.0,37169,73.53,33224,17.96,16.15,7.11,41.28,103.27,...,59.53,1980,3,0.902962,0.902962,37,169,0,10.411030,0.0
23461,23462,0.0,40151,8.52,10958,15.53,17.31,0.51,42.89,58.19,...,10.98,1981,0,0.000000,0.000000,40,151,0,9.301826,0.0
15793,15794,2.0,30049,12.51,43296,17.64,18.65,0.13,41.05,105.70,...,71.68,1980,2,0.461936,0.461936,30,49,0,10.675820,0.0
27699,27700,11.0,48013,23.88,29424,18.17,14.25,0.50,40.36,163.43,...,52.04,1986,2,0.679717,3.738445,48,13,0,10.289570,0.0
35981,35982,1.0,55021,58.20,45040,14.17,13.27,0.51,42.18,101.68,...,71.02,1989,2,0.444050,0.222025,55,21,0,10.715310,0.0

In [31]:
df.sample(13)

,rownames,arrests,countyid,density,popul,perc1019,perc2029,percblack,percmale,rpcincmaint,...,rpcunemins,year,murders,murdrate,arrestrate,statefips,countyfips,execs,lpopul,execrate
21629,21630,0.0,39089,181.19000,124384,16.10000,16.030000,1.700000,41.08000,147.550,...,62.180,1985,0,0.000000,0.000000,39,89,0,11.731130,0.0
10769,10770,3.0,23001,220.18000,103552,14.72000,16.760000,0.430000,40.67000,175.970,...,53.300,1988,5,0.482849,0.289710,23,1,0,11.547830,0.0
35902,35903,13.0,55009,398.52050,210685,15.54643,14.797920,0.600897,48.94606,127.920,...,55.104,1995,4,0.189857,0.617035,55,9,0,12.258120,0.0
4039,4040,1.0,8087,17.32000,22268,14.88000,12.910000,0.330000,40.51000,147.840,...,34.470,1990,1,0.449075,0.449075,8,87,0,10.010910,0.0
18513,18514,367.0,36047,31646.24000,2231808,16.47000,17.180000,33.880000,38.40000,490.860,...,105.700,1980,572,2.562944,1.644407,36,47,0,14.618320,0.0
29731,29732,2.0,48259,29.20364,19346,13.92019,9.278404,0.413522,48.76460,93.808,...,9.184,1995,0,0.000000,1.033805,48,259,0,9.870241,0.0
2217,2218,2.0,5125,83.55000,60552,15.77000,15.130000,2.240000,41.88000,46.640,...,66.880,1987,1,0.165147,0.330295,5,125,0,11.011260,0.0
11912,11913,0.0,26029,53.41000,22264,13.23000,12.340000,0.080000,41.12000,159.710,...,206.060,1992,0,0.000000,0.000000,26,29,0,10.010730,0.0
27260,27261,0.0,47141,127.39000,51080,15.46000,19.570000,1.700000,42.78000,120.240,...,46.000,1989,0,0.000000,0.000000,47,141,0,10.841150,0.0
13927,13928,0.0,27101,15.54000,10948,16.25000,13.070000,0.030000,42.34000,129.730,...,71.110,1984,0,0.000000,0.000000,27,101,0,9.300912,0.0
9577,9578,0.0,20137,7.14000,6270,12.58000,13.690000,1.500000,44.33000,52.950,...,32.870,1986,0,0.000000,0.000000,20,137,0,8.743531,0.0
33882,33883,7.0,51540,3906.11000,40072,13.80000,32.270000,18.350000,42.08000,102.110,...,23.060,1981,5,1.247754,1.746856,51,540,0,10.598430,0.0
12204,12205,0.0,26063,42.14876,35261,14.56850,10.544230,0.065228,49.21585,184.336,...,87.904,1995,0,0.000000,0.000000,26,63,0,10.470530,0.0

In [32]:
df.dropna()

,rownames,arrests,countyid,density,popul,perc1019,perc2029,percblack,percmale,rpcincmaint,...,rpcunemins,year,murders,murdrate,arrestrate,statefips,countyfips,execs,lpopul,execrate
0,1,2.0,1001,54.050000,32216,20.63000,15.280000,22.330000,40.25000,167.670,...,29.160,1980,2,0.620810,0.620810,1,1,0,10.380220,0.0
1,2,3.0,1001,53.660000,31984,20.19000,15.550000,22.070000,40.36000,167.990,...,43.920,1981,1,0.312656,0.937969,1,1,0,10.372990,0.0
2,3,2.0,1001,53.750000,32036,19.66000,15.730000,21.800000,40.42000,166.630,...,71.410,1982,3,0.936446,0.624298,1,1,0,10.374620,0.0
3,4,7.0,1001,53.780000,32056,19.10000,15.880000,21.530000,40.47000,176.530,...,72.220,1983,7,2.183679,2.183679,1,1,0,10.375240,0.0
4,5,3.0,1001,53.910000,32128,18.54000,15.920000,21.260000,40.51000,166.250,...,40.360,1984,2,0.622510,0.933765,1,1,0,10.377480,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37344,37345,0.0,56045,2.680000,6430,16.35000,10.260000,0.060000,42.67000,95.540,...,54.190,1992,0,0.000000,0.000000,56,45,0,8.768730,0.0
37345,37346,1.0,56045,2.708031,6493,16.67950,9.610350,0.077006,50.13091,107.260,...,42.904,1993,0,0.000000,1.540120,56,45,0,8.778480,0.0
37346,37347,0.0,56045,2.736391,6561,16.79622,9.510745,0.030483,50.16004,98.550,...,39.150,1994,0,0.000000,0.000000,56,45,0,8.788898,0.0
37347,37348,0.0,56045,2.730135,6546,17.01803,9.563092,0.076383,50.18332,106.928,...,38.048,1995,0,0.000000,0.000000,56,45,0,8.786610,0.0
37348,37349,0.0,56045,2.733472,6554,16.90571,9.642966,0.076289,50.13732,116.116,...,40.194,1996,0,0.000000,0.000000,56,45,0,8.787830,0.0

In [33]:
dir(df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_arith_method_with_reindex',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_create_data_for_split_and_tight_to_dict',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_nocopy',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'applymap',
 'arrestrate',
 'arrests',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bigquery',
 'bool',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'countyfips',
 'countyid',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'density',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'execrate',
 'execs',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lpopul',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'murders',
 'murdrate',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'perc1019',
 'perc2029',
 'percblack',
 'percmale',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'popul',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rownames',
 'rpcincmaint',
 'rpcpersinc',
 'rpcunemins',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_geometry',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'statefips',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs',
 'year']

In [34]:
print("Mean values of the first 30 records:")
print(df.head(30).mean(numeric_only=True))

Mean values of the first 30 records:
rownames          15.500000
arrests            3.366667
countyid        1001.866667
density           57.466529
popul          58979.066667
perc1019          16.801380
perc2029          14.425323
percblack         17.816530
percmale          41.814659
rpcincmaint      143.210167
rpcpersinc     10408.332000
rpcunemins        36.995300
year            1987.133333
murders            3.766667
murdrate           0.667508
arrestrate         0.682123
statefips          1.000000
countyfips         1.866667
execs              0.000000
lpopul            10.865225
execrate           0.000000
dtype: float64

In [35]:
print("Mean values of the last 10 records:")
print(df.tail(10).mean(numeric_only=True))

Mean values of the last 10 records:
rownames       37344.500000
arrests            0.100000
countyid       56045.000000
density            2.770803
popul           6645.400000
perc1019          16.261946
perc2029          10.464715
percblack          0.063016
percmale          45.156159
rpcincmaint       92.667400
rpcpersinc     13376.873000
rpcunemins        44.454600
year            1991.500000
murders            0.000000
murdrate           0.000000
arrestrate         0.154012
statefips         56.000000
countyfips        45.000000
execs              0.000000
lpopul             8.801106
execrate           0.000000
dtype: float64

In [37]:
df.columns

Index(['rownames', 'arrests', 'countyid', 'density', 'popul', 'perc1019',
       'perc2029', 'percblack', 'percmale', 'rpcincmaint', 'rpcpersinc',
       'rpcunemins', 'year', 'murders', 'murdrate', 'arrestrate', 'statefips',
       'countyfips', 'execs', 'lpopul', 'execrate'],
      dtype='object')

In [38]:
df['rownames']

0            1
1            2
2            3
3            4
4            5
         ...
37344    37345
37345    37346
37346    37347
37347    37348
37348    37349
Name: rownames, Length: 37349, dtype: int64

In [39]:
df['arrests']

0        2.0
1        3.0
2        2.0
3        7.0
4        3.0
        ...
37344    0.0
37345    1.0
37346    0.0
37347    0.0
37348    0.0
Name: arrests, Length: 37349, dtype: float64

In [40]:
df['percmale'].describe()

count    37349.000000
mean        43.350958
std          3.717612
min         35.150000
25%         40.900000
50%         41.810000
75%         45.870000
max         78.040000
Name: percmale, dtype: float64

In [41]:
df['rpcunemins'].describe()

count    37346.000000
mean        70.557953
std         52.909393
min          0.000000
25%         35.200000
50%         57.100000
75%         89.958000
max        642.730000
Name: rpcunemins, dtype: float64

In [42]:
df['execs'].count()

np.int64(37349)

In [43]:
df['perc2029'].count()

np.int64(37349)

In [44]:
df['murders'].mean()

np.float64(7.286915312324292)

In [45]:
df['year'].mean()

np.float64(1988.0)

In [46]:
df[10:20]

,rownames,arrests,countyid,density,popul,perc1019,perc2029,percblack,percmale,rpcincmaint,...,rpcunemins,year,murders,murdrate,arrestrate,statefips,countyfips,execs,lpopul,execrate
10,11,0.0,1001,57.91000,34512,16.76000,14.34000,20.19000,40.46000,171.580,...,39.830,1990,1,0.289754,0.000000,1,1,0,10.44906,0.0
11,12,1.0,1001,58.76000,35024,16.51000,14.14000,20.27000,40.48000,176.160,...,44.040,1991,1,0.285519,0.285519,1,1,0,10.46379,0.0
12,13,5.0,1001,59.66000,35560,16.26000,13.96000,20.34000,40.51000,200.350,...,49.910,1992,1,0.281215,1.406074,1,1,0,10.47898,0.0
13,14,3.0,1001,62.12483,37027,16.09366,13.76023,20.48505,48.68339,202.756,...,41.520,1993,1,0.270073,0.810220,1,1,0,10.51940,0.0
14,15,4.0,1001,63.80266,38027,16.02809,13.51934,20.64849,48.71013,199.125,...,27.675,1994,1,0.262971,1.051884,1,1,0,10.54605,0.0
15,16,5.0,1001,65.36304,38957,15.96889,13.33522,20.87686,48.72552,197.456,...,31.488,1995,5,1.283466,1.283466,1,1,0,10.57021,0.0
16,17,8.0,1001,67.21535,40061,15.89077,13.17491,20.97551,48.70073,192.038,...,26.796,1996,7,1.747335,1.996955,1,1,0,10.59816,0.0
17,18,4.0,1003,49.45000,78944,17.98000,14.95000,15.22000,40.55000,132.430,...,25.510,1980,4,0.506688,0.506688,1,3,0,11.27649,0.0
18,19,9.0,1003,50.29000,80288,17.53000,15.02000,14.93000,40.71000,121.880,...,20.860,1981,6,0.747310,1.120965,1,3,0,11.29338,0.0
19,20,8.0,1003,51.56000,82320,17.03000,15.03000,14.63000,40.84000,107.640,...,30.010,1982,7,0.850340,0.971817,1,3,0,11.31837,0.0

In [47]:
df[40:68]

,rownames,arrests,countyid,density,popul,perc1019,perc2029,percblack,percmale,rpcincmaint,...,rpcunemins,year,murders,murdrate,arrestrate,statefips,countyfips,execs,lpopul,execrate
40,41,0.0,1005,28.18000,24940,16.97000,14.87000,43.930000,39.10000,272.070,...,46.560,1986,0,0.000000,0.000000,1,5,0,10.12423,0.0
41,42,2.0,1005,28.37000,25104,16.80000,14.63000,43.900000,39.22000,257.840,...,40.480,1987,3,1.195029,0.796686,1,5,0,10.13078,0.0
42,43,5.0,1005,28.51000,25228,16.70000,14.31000,43.920000,39.27000,267.340,...,34.690,1988,2,0.792770,1.981925,1,5,0,10.13571,0.0
43,44,5.0,1005,28.63000,25336,16.59000,13.94000,43.980000,39.34000,278.410,...,36.310,1989,2,0.789391,1.973476,1,5,0,10.13998,0.0
44,45,3.0,1005,28.85000,25532,16.39000,13.81000,44.220000,39.38000,293.380,...,45.960,1990,4,1.566661,1.174996,1,5,0,10.14769,0.0
45,46,5.0,1005,29.07000,25728,16.18000,13.67000,44.440000,39.43000,303.140,...,52.110,1991,4,1.554726,1.943408,1,5,0,10.15534,0.0
46,47,1.0,1005,29.30000,25932,15.95000,13.53000,44.670000,39.44000,376.460,...,70.590,1992,0,0.000000,0.385624,1,5,0,10.16323,0.0
47,48,2.0,1005,29.89966,26461,15.37735,13.99418,45.289300,48.74721,366.068,...,57.436,1993,3,1.133744,0.755829,1,5,0,10.18343,0.0
48,49,1.0,1005,29.88158,26445,15.19758,13.93836,45.702400,49.01115,370.575,...,35.100,1994,3,1.134430,0.378143,1,5,0,10.18282,0.0
49,50,1.0,1005,29.75954,26337,15.09284,13.82086,46.003720,49.12860,396.224,...,44.608,1995,3,1.139082,0.379694,1,5,0,10.17873,0.0
50,51,1.0,1005,29.91548,26475,15.06327,13.69972,46.190750,49.15203,405.768,...,63.162,1996,1,0.377715,0.377715,1,5,0,10.18396,0.0
51,52,2.0,1009,56.59000,36536,17.88000,14.94000,1.640000,41.83000,145.800,...,48.600,1980,4,1.094811,0.547405,1,9,0,10.50605,0.0
52,53,4.0,1009,56.75000,36640,17.53000,15.26000,1.620000,41.90000,141.640,...,47.210,1981,2,0.545852,1.091703,1,9,0,10.50890,0.0
53,54,1.0,1009,56.30000,36352,17.09000,15.49000,1.570000,41.97000,146.970,...,75.550,1982,0,0.000000,0.275088,1,9,0,10.50100,0.0
54,55,1.0,1009,56.41000,36424,16.65000,15.65000,1.520000,42.01000,153.460,...,69.210,1983,0,0.000000,0.274544,1,9,0,10.50298,0.0
55,56,2.0,1009,56.97000,36784,16.22000,15.74000,1.510000,42.04000,143.190,...,41.320,1984,1,0.271857,0.543715,1,9,0,10.51282,0.0
56,57,2.0,1009,57.95000,37416,15.86000,15.73000,1.490000,41.97000,134.560,...,35.260,1985,3,0.801796,0.534531,1,9,0,10.52985,0.0
57,58,4.0,1009,58.84000,37992,15.59000,15.59000,1.450000,41.94000,116.860,...,40.170,1986,3,0.789640,1.052853,1,9,0,10.54513,0.0
58,59,0.0,1009,58.88000,38016,15.45000,15.31000,1.440000,41.98000,102.960,...,35.200,1987,0,0.000000,0.000000,1,9,0,10.54576,0.0
59,60,1.0,1009,59.24000,38248,15.37000,14.97000,1.390000,41.95000,108.290,...,28.760,1988,1,0.261452,0.261452,1,9,0,10.55185,0.0
60,61,3.0,1009,60.04000,38768,15.26000,14.64000,1.370000,41.96000,113.790,...,23.400,1989,2,0.515889,0.773834,1,9,0,10.56535,0.0
61,62,2.0,1009,60.85000,39288,15.02000,14.47000,1.360000,42.00000,120.260,...,39.830,1990,1,0.254531,0.509061,1,9,0,10.57867,0.0
62,63,0.0,1009,61.67000,39816,14.78000,14.32000,1.360000,42.03000,135.790,...,36.700,1991,0,0.000000,0.000000,1,9,0,10.59202,0.0
63,64,1.0,1009,62.51000,40360,14.54000,14.15000,1.350000,42.06000,162.560,...,46.340,1992,0,0.000000,0.247770,1,9,0,10.60559,0.0
64,65,2.0,1009,63.66562,41107,14.31143,13.82003,1.367164,48.84813,167.464,...,34.600,1993,2,0.486535,0.486535,1,9,0,10.62393,0.0
65,66,2.0,1009,63.86541,41236,14.26181,13.50519,1.382287,48.89175,180.900,...,22.950,1994,1,0.242507,0.485013,1,9,0,10.62707,0.0
66,67,0.0,1009,65.82152,42499,14.20269,13.22384,1.397680,48.94468,177.776,...,23.616,1995,0,0.000000,0.000000,1,9,0,10.65724,0.0
67,68,0.0,1009,67.20457,43392,14.17542,12.99318,1.415007,48.97446,184.382,...,21.692,1996,2,0.460915,0.000000,1,9,0,10.67803,0.0

In [48]:
df.loc[10:20,['rownames', 'arrests', 'countyid']]

    rownames  arrests  countyid
10        11      0.0      1001
11        12      1.0      1001
12        13      5.0      1001
13        14      3.0      1001
14        15      4.0      1001
15        16      5.0      1001
16        17      8.0      1001
17        18      4.0      1003
18        19      9.0      1003
19        20      8.0      1003
20        21      5.0      1003

In [49]:
df.loc[10:20,['arrestrate', 'statefips']]

    arrestrate  statefips
10    0.000000          1
11    0.285519          1
12    1.406074          1
13    0.810220          1
14    1.051884          1
15    1.283466          1
16    1.996955          1
17    0.506688          1
18    1.120965          1
19    0.971817          1
20    0.595465          1

In [50]:
df.dropna(how='all')

,rownames,arrests,countyid,density,popul,perc1019,perc2029,percblack,percmale,rpcincmaint,...,rpcunemins,year,murders,murdrate,arrestrate,statefips,countyfips,execs,lpopul,execrate
0,1,2.0,1001,54.050000,32216,20.63000,15.280000,22.330000,40.25000,167.670,...,29.160,1980,2,0.620810,0.620810,1,1,0,10.380220,0.0
1,2,3.0,1001,53.660000,31984,20.19000,15.550000,22.070000,40.36000,167.990,...,43.920,1981,1,0.312656,0.937969,1,1,0,10.372990,0.0
2,3,2.0,1001,53.750000,32036,19.66000,15.730000,21.800000,40.42000,166.630,...,71.410,1982,3,0.936446,0.624298,1,1,0,10.374620,0.0
3,4,7.0,1001,53.780000,32056,19.10000,15.880000,21.530000,40.47000,176.530,...,72.220,1983,7,2.183679,2.183679,1,1,0,10.375240,0.0
4,5,3.0,1001,53.910000,32128,18.54000,15.920000,21.260000,40.51000,166.250,...,40.360,1984,2,0.622510,0.933765,1,1,0,10.377480,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37344,37345,0.0,56045,2.680000,6430,16.35000,10.260000,0.060000,42.67000,95.540,...,54.190,1992,0,0.000000,0.000000,56,45,0,8.768730,0.0
37345,37346,1.0,56045,2.708031,6493,16.67950,9.610350,0.077006,50.13091,107.260,...,42.904,1993,0,0.000000,1.540120,56,45,0,8.778480,0.0
37346,37347,0.0,56045,2.736391,6561,16.79622,9.510745,0.030483,50.16004,98.550,...,39.150,1994,0,0.000000,0.000000,56,45,0,8.788898,0.0
37347,37348,0.0,56045,2.730135,6546,17.01803,9.563092,0.076383,50.18332,106.928,...,38.048,1995,0,0.000000,0.000000,56,45,0,8.786610,0.0
37348,37349,0.0,56045,2.733472,6554,16.90571,9.642966,0.076289,50.13732,116.116,...,40.194,1996,0,0.000000,0.000000,56,45,0,8.787830,0.0

In [51]:
df.dropna(axis=1, how='all')

,rownames,arrests,countyid,density,popul,perc1019,perc2029,percblack,percmale,rpcincmaint,...,rpcunemins,year,murders,murdrate,arrestrate,statefips,countyfips,execs,lpopul,execrate
0,1,2.0,1001,54.050000,32216,20.63000,15.280000,22.330000,40.25000,167.670,...,29.160,1980,2,0.620810,0.620810,1,1,0,10.380220,0.0
1,2,3.0,1001,53.660000,31984,20.19000,15.550000,22.070000,40.36000,167.990,...,43.920,1981,1,0.312656,0.937969,1,1,0,10.372990,0.0
2,3,2.0,1001,53.750000,32036,19.66000,15.730000,21.800000,40.42000,166.630,...,71.410,1982,3,0.936446,0.624298,1,1,0,10.374620,0.0
3,4,7.0,1001,53.780000,32056,19.10000,15.880000,21.530000,40.47000,176.530,...,72.220,1983,7,2.183679,2.183679,1,1,0,10.375240,0.0
4,5,3.0,1001,53.910000,32128,18.54000,15.920000,21.260000,40.51000,166.250,...,40.360,1984,2,0.622510,0.933765,1,1,0,10.377480,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37344,37345,0.0,56045,2.680000,6430,16.35000,10.260000,0.060000,42.67000,95.540,...,54.190,1992,0,0.000000,0.000000,56,45,0,8.768730,0.0
37345,37346,1.0,56045,2.708031,6493,16.67950,9.610350,0.077006,50.13091,107.260,...,42.904,1993,0,0.000000,1.540120,56,45,0,8.778480,0.0
37346,37347,0.0,56045,2.736391,6561,16.79622,9.510745,0.030483,50.16004,98.550,...,39.150,1994,0,0.000000,0.000000,56,45,0,8.788898,0.0
37347,37348,0.0,56045,2.730135,6546,17.01803,9.563092,0.076383,50.18332,106.928,...,38.048,1995,0,0.000000,0.000000,56,45,0,8.786610,0.0
37348,37349,0.0,56045,2.733472,6554,16.90571,9.642966,0.076289,50.13732,116.116,...,40.194,1996,0,0.000000,0.000000,56,45,0,8.787830,0.0

In [52]:
df.min()

rownames          1.000000
arrests           0.000000
countyid       1001.000000
density           0.050000
popul            85.000000
perc1019          7.080000
perc2029          5.617244
percblack         0.000000
percmale         35.150000
rpcincmaint       5.490000
rpcpersinc     3477.760000
rpcunemins        0.000000
year           1980.000000
murders           0.000000
murdrate          0.000000
arrestrate        0.000000
statefips         1.000000
countyfips        1.000000
execs             0.000000
lpopul            4.442651
execrate          0.000000
dtype: float64

In [53]:
df.max()

rownames       3.734900e+04
arrests        2.391000e+03
countyid       5.604500e+04
density        5.405877e+04
popul          9.127751e+06
perc1019       3.048458e+01
perc2029       4.052000e+01
percblack      8.627934e+01
percmale       7.804000e+01
rpcincmaint    1.306496e+03
rpcpersinc     4.109422e+04
rpcunemins     6.427300e+02
year           1.996000e+03
murders        1.944000e+03
murdrate       3.984064e+01
arrestrate     1.486584e+02
statefips      5.600000e+01
countyfips     8.400000e+02
execs          7.000000e+00
lpopul         1.602683e+01
execrate       2.388916e+00
dtype: float64

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37349 entries, 0 to 37348
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   rownames     37349 non-null  int64
 1   arrests      36845 non-null  float64
 2   countyid     37349 non-null  int64
 3   density      37349 non-null  float64
 4   popul        37349 non-null  int64
 5   perc1019     37349 non-null  float64
 6   perc2029     37349 non-null  float64
 7   percblack    37349 non-null  float64
 8   percmale     37349 non-null  float64
 9   rpcincmaint  37346 non-null  float64
 10  rpcpersinc   37346 non-null  float64
 11  rpcunemins   37346 non-null  float64
 12  year         37349 non-null  int64
 13  murders      37349 non-null  int64
 14  murdrate     37349 non-null  float64
 15  arrestrate   36845 non-null  float64
 16  statefips    37349 non-null  int64
 17  countyfips   37349 non-null  int64
 18  execs        37349 non-null  int64
 19  lpopul       37349 non-null  float64
 20  execrate     37349 non-null  float64
dtypes: float64(13), int64(8)
memory usage: 6.0 MB