In [1]:
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib as mpl
import seaborn as sns
df =pd.read_csv("/content/chess_games.csv")

In [2]:
df.head()

,game_id,rated,turns,victory_status,winner,time_increment,white_id,white_rating,black_id,black_rating,moves,opening_code,opening_moves,opening_fullname,opening_shortname,opening_response,opening_variation
0,1,False,13,Out of Time,White,15+2,bourgris,1500,a-00,1191,d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...,D10,5,Slav Defense: Exchange Variation,Slav Defense,NaN,Exchange Variation
1,2,True,16,Resign,Black,5+10,a-00,1322,skinnerua,1261,d4 Nc6 e4 e5 f4 f6 dxe5 fxe5 fxe5 Nxe5 Qd4 Nc6...,B00,4,Nimzowitsch Defense: Kennedy Variation,Nimzowitsch Defense,NaN,Kennedy Variation
2,3,True,61,Mate,White,5+10,ischia,1496,a-00,1500,e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...,C20,3,King's Pawn Game: Leonardis Variation,King's Pawn Game,NaN,Leonardis Variation
3,4,True,61,Mate,White,20+0,daniamurashov,1439,adivanov2009,1454,d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...,D02,3,Queen's Pawn Game: Zukertort Variation,Queen's Pawn Game,NaN,Zukertort Variation
4,5,True,95,Mate,White,30+3,nik221107,1523,adivanov2009,1469,e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...,C41,5,Philidor Defense,Philidor Defense,NaN,NaN

In [3]:
df.head(10)

,game_id,rated,turns,victory_status,winner,time_increment,white_id,white_rating,black_id,black_rating,moves,opening_code,opening_moves,opening_fullname,opening_shortname,opening_response,opening_variation
0,1,False,13,Out of Time,White,15+2,bourgris,1500,a-00,1191,d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...,D10,5,Slav Defense: Exchange Variation,Slav Defense,NaN,Exchange Variation
1,2,True,16,Resign,Black,5+10,a-00,1322,skinnerua,1261,d4 Nc6 e4 e5 f4 f6 dxe5 fxe5 fxe5 Nxe5 Qd4 Nc6...,B00,4,Nimzowitsch Defense: Kennedy Variation,Nimzowitsch Defense,NaN,Kennedy Variation
2,3,True,61,Mate,White,5+10,ischia,1496,a-00,1500,e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...,C20,3,King's Pawn Game: Leonardis Variation,King's Pawn Game,NaN,Leonardis Variation
3,4,True,61,Mate,White,20+0,daniamurashov,1439,adivanov2009,1454,d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...,D02,3,Queen's Pawn Game: Zukertort Variation,Queen's Pawn Game,NaN,Zukertort Variation
4,5,True,95,Mate,White,30+3,nik221107,1523,adivanov2009,1469,e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...,C41,5,Philidor Defense,Philidor Defense,NaN,NaN
5,6,False,5,Draw,Draw,10+0,trelynn17,1250,franklin14532,1002,e4 c5 Nf3 Qa5 a3,B27,4,Sicilian Defense: Mongoose Variation,Sicilian Defense,NaN,Mongoose Variation
6,7,True,33,Resign,White,10+0,capa_jr,1520,daniel_likes_chess,1423,d4 d5 e4 dxe4 Nc3 Nf6 f3 exf3 Nxf3 Nc6 Bb5 a6 ...,D00,10,Blackmar-Diemer Gambit: Pietrowsky Defense,Blackmar-Diemer Gambit,NaN,Pietrowsky Defense
7,8,False,9,Resign,Black,15+30,daniel_likes_chess,1413,soultego,2108,e4 Nc6 d4 e5 d5 Nce7 c3 Ng6 b4,B00,5,Nimzowitsch Defense: Kennedy Variation | Link...,Nimzowitsch Defense,NaN,Kennedy Variation
8,9,True,66,Resign,Black,15+0,ehabfanri,1439,daniel_likes_chess,1392,e4 e5 Bc4 Nc6 Nf3 Nd4 d3 Nxf3+ Qxf3 Nf6 h3 Bc5...,C50,6,Italian Game: Schilling-Kostic Gambit,Italian Game,NaN,Schilling-Kostic Gambit
9,10,True,119,Mate,White,10+0,daniel_likes_chess,1381,mirco25,1209,e4 d5 exd5 Qxd5 Nc3 Qe5+ Be2 Na6 d4 Qf5 Bxa6 b...,B01,4,Scandinavian Defense: Mieses-Kotroc Variation,Scandinavian Defense,NaN,Mieses-Kotroc Variation

In [4]:
df.head(20)

,game_id,rated,turns,victory_status,winner,time_increment,white_id,white_rating,black_id,black_rating,moves,opening_code,opening_moves,opening_fullname,opening_shortname,opening_response,opening_variation
0,1,False,13,Out of Time,White,15+2,bourgris,1500,a-00,1191,d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...,D10,5,Slav Defense: Exchange Variation,Slav Defense,NaN,Exchange Variation
1,2,True,16,Resign,Black,5+10,a-00,1322,skinnerua,1261,d4 Nc6 e4 e5 f4 f6 dxe5 fxe5 fxe5 Nxe5 Qd4 Nc6...,B00,4,Nimzowitsch Defense: Kennedy Variation,Nimzowitsch Defense,NaN,Kennedy Variation
2,3,True,61,Mate,White,5+10,ischia,1496,a-00,1500,e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...,C20,3,King's Pawn Game: Leonardis Variation,King's Pawn Game,NaN,Leonardis Variation
3,4,True,61,Mate,White,20+0,daniamurashov,1439,adivanov2009,1454,d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...,D02,3,Queen's Pawn Game: Zukertort Variation,Queen's Pawn Game,NaN,Zukertort Variation
4,5,True,95,Mate,White,30+3,nik221107,1523,adivanov2009,1469,e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...,C41,5,Philidor Defense,Philidor Defense,NaN,NaN
5,6,False,5,Draw,Draw,10+0,trelynn17,1250,franklin14532,1002,e4 c5 Nf3 Qa5 a3,B27,4,Sicilian Defense: Mongoose Variation,Sicilian Defense,NaN,Mongoose Variation
6,7,True,33,Resign,White,10+0,capa_jr,1520,daniel_likes_chess,1423,d4 d5 e4 dxe4 Nc3 Nf6 f3 exf3 Nxf3 Nc6 Bb5 a6 ...,D00,10,Blackmar-Diemer Gambit: Pietrowsky Defense,Blackmar-Diemer Gambit,NaN,Pietrowsky Defense
7,8,False,9,Resign,Black,15+30,daniel_likes_chess,1413,soultego,2108,e4 Nc6 d4 e5 d5 Nce7 c3 Ng6 b4,B00,5,Nimzowitsch Defense: Kennedy Variation | Link...,Nimzowitsch Defense,NaN,Kennedy Variation
8,9,True,66,Resign,Black,15+0,ehabfanri,1439,daniel_likes_chess,1392,e4 e5 Bc4 Nc6 Nf3 Nd4 d3 Nxf3+ Qxf3 Nf6 h3 Bc5...,C50,6,Italian Game: Schilling-Kostic Gambit,Italian Game,NaN,Schilling-Kostic Gambit
9,10,True,119,Mate,White,10+0,daniel_likes_chess,1381,mirco25,1209,e4 d5 exd5 Qxd5 Nc3 Qe5+ Be2 Na6 d4 Qf5 Bxa6 b...,B01,4,Scandinavian Defense: Mieses-Kotroc Variation,Scandinavian Defense,NaN,Mieses-Kotroc Variation
10,11,False,39,Mate,White,20+60,daniel_likes_chess,1381,anaissac,1272,e3 e6 d4 d6 Bd3 c6 Nf3 Be7 Nc3 Nf6 Bd2 Bd7 Qe2...,A00,1,Van't Kruijs Opening,Van't Kruijs Opening,NaN,NaN
11,12,False,38,Resign,Black,20+60,daniel_likes_chess,1381,subham777,1867,e4 e6 d4 d5 e5 c5 c3 Nc6 Nf3 Qb6 Be3 Qxb2 Nbd2...,C02,9,French Defense: Advance Variation | Paulsen A...,French Defense,NaN,Advance Variation
12,13,False,60,Resign,Black,5+40,daniel_likes_chess,1381,roman12342005,1936,e4 e6 Nf3 d5 exd5 exd5 Qe2+ Be7 Nc3 Nf6 d4 O-O...,C00,3,French Defense: Knight Variation,French Defense,NaN,Knight Variation
13,14,False,31,Resign,Black,8+0,daniel_likes_chess,1381,alkhan,1607,e4 e6 Qh5 g6 Qe5 Nf6 d4 d6 Qb5+ Bd7 Qxb7 Bc6 Q...,C00,2,French Defense #2,French Defense,NaN,#2
14,15,False,31,Mate,White,15+15,shivangithegenius,1094,sureka_akshat,1141,e4 e5 Nf3 Nc6 Bc4 Nf6 Nc3 Bc5 O-O O-O d3 Ne8 B...,C50,8,Four Knights Game: Italian Variation,Four Knights Game,NaN,Italian Variation
15,16,False,43,Resign,Black,15+15,sureka_akshat,1141,shivangithegenius,1094,e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 Qe7 O-O Nxe4 Nxe4 h6...,C57,7,Italian Game: Two Knights Defense | Knight At...,Italian Game,NaN,Two Knights Defense
16,17,False,52,Resign,Black,15+15,shivangithegenius,1094,sureka_akshat,1141,e4 e5 Nf3 Nc6 Bc4 Nf6 Nc3 Bc5 O-O O-O Ne1 d6 d...,C50,8,Four Knights Game: Italian Variation,Four Knights Game,NaN,Italian Variation
17,18,False,66,Mate,Black,15+16,sureka_akshat,1141,shivangithegenius,1094,e4 e5 Nf3 Nc6 Bc4 Nf6 Nc3 Bc5 O-O O-O Ne1 Ne8 ...,C50,8,Four Knights Game: Italian Variation,Four Knights Game,NaN,Italian Variation
18,19,False,101,Resign,Black,15+15,shivangithegenius,1094,slam_ment,1300,e4 e5 Nf3 d6 Bc4 Be6 d3 Bxc4 dxc4 c5 O-O h6 Nc...,C41,5,Philidor Defense #3,Philidor Defense,NaN,#3
19,20,False,25,Resign,White,11+0,g-ios,1500,shivangithegenius,1094,d4 d5 h3 Nc6 Nf3 Nf6 Bg5 h6 Bxf6 exf6 e3 Bb4+ ...,D00,2,Queen's Pawn Game,Queen's Pawn Game,NaN,NaN

In [5]:
df.tail()

,game_id,rated,turns,victory_status,winner,time_increment,white_id,white_rating,black_id,black_rating,moves,opening_code,opening_moves,opening_fullname,opening_shortname,opening_response,opening_variation
20053,20054,True,24,Resign,White,10+10,belcolt,1691,jamboger,1220,d4 f5 e3 e6 Nf3 Nf6 Nc3 b6 Be2 Bb7 O-O Be7 Ne5...,A80,2,Dutch Defense,Dutch Defense,NaN,NaN
20054,20055,True,82,Mate,Black,10+0,jamboger,1233,farrukhasomiddinov,1196,d4 d6 Bf4 e5 Bg3 Nf6 e3 exd4 exd4 d5 c3 Bd6 Bd...,A41,2,Queen's Pawn,Queen's Pawn,NaN,NaN
20055,20056,True,35,Mate,White,10+0,jamboger,1219,schaaksmurf3,1286,d4 d5 Bf4 Nc6 e3 Nf6 c3 e6 Nf3 Be7 Bd3 O-O Nbd...,D00,3,Queen's Pawn Game: Mason Attack,Queen's Pawn Game,NaN,Mason Attack
20056,20057,True,109,Resign,White,10+0,marcodisogno,1360,jamboger,1227,e4 d6 d4 Nf6 e5 dxe5 dxe5 Qxd1+ Kxd1 Nd5 c4 Nb...,B07,4,Pirc Defense,Pirc Defense,NaN,NaN
20057,20058,True,78,Mate,Black,10+0,jamboger,1235,ffbob,1339,d4 d5 Bf4 Na6 e3 e6 c3 Nf6 Nf3 Bd7 Nbd2 b5 Bd3...,D00,3,Queen's Pawn Game: Mason Attack,Queen's Pawn Game,NaN,Mason Attack

In [6]:
df.tail(12)

,game_id,rated,turns,victory_status,winner,time_increment,white_id,white_rating,black_id,black_rating,moves,opening_code,opening_moves,opening_fullname,opening_shortname,opening_response,opening_variation
20046,20047,True,36,Mate,Black,10+10,mateuslichess,1250,jamboger,1235,e4 d6 d4 Nf6 e5 dxe5 Be2 exd4 Nf3 Nc6 O-O e5 B...,B07,4,Pirc Defense,Pirc Defense,NaN,NaN
20047,20048,True,73,Mate,White,10+10,jamboger,1222,mateuslichess,1262,c4 d5 e3 dxc4 Bxc4 Nc6 a3 Ne5 d4 Nxc4 Nc3 e5 N...,A10,2,English Opening: Anglo-Scandinavian Defense,English Opening,NaN,Anglo-Scandinavian Defense
20048,20049,True,25,Resign,White,10+10,mateuslichess,1252,jamboger,1233,e4 e6 d4 d5 exd5 Qxd5 Nc3 Bb4 a3 Bxc3+ bxc3 Ne...,C01,5,French Defense: Exchange Variation,French Defense,NaN,Exchange Variation
20049,20050,True,43,Mate,White,10+0,jkubb29,1328,jamboger,1252,e4 e6 Nf3 d5 Nc3 Bb4 exd5 exd5 d4 Bg4 a3 Bxc3+...,C00,5,French Defense: Two Knights Variation,French Defense,NaN,Two Knights Variation
20050,20051,True,9,Out of Time,White,10+0,jamboger,1243,yamaguchipolgar,1142,c4 e5 d4 exd4 Qxd4 Nf6 Bg5 Be7 e4,A20,2,English Opening: King's English Variation,English Opening,NaN,King's English Variation
20051,20052,True,58,Mate,Black,10+10,samael88,1237,jamboger,1231,e4 e6 Nf3 d5 Bb5+ Bd7 c4 c6 Ba4 Qa5 b3 b5 cxb5...,C00,3,French Defense: Knight Variation,French Defense,NaN,Knight Variation
20052,20053,True,37,Resign,White,10+10,jamboger,1219,samael88,1250,c4 e6 d4 b6 Nc3 Bb7 Nf3 g6 h4 Bg7 Bg5 f6 Bf4 d...,A40,4,English Defense,English Defense,NaN,NaN
20053,20054,True,24,Resign,White,10+10,belcolt,1691,jamboger,1220,d4 f5 e3 e6 Nf3 Nf6 Nc3 b6 Be2 Bb7 O-O Be7 Ne5...,A80,2,Dutch Defense,Dutch Defense,NaN,NaN
20054,20055,True,82,Mate,Black,10+0,jamboger,1233,farrukhasomiddinov,1196,d4 d6 Bf4 e5 Bg3 Nf6 e3 exd4 exd4 d5 c3 Bd6 Bd...,A41,2,Queen's Pawn,Queen's Pawn,NaN,NaN
20055,20056,True,35,Mate,White,10+0,jamboger,1219,schaaksmurf3,1286,d4 d5 Bf4 Nc6 e3 Nf6 c3 e6 Nf3 Be7 Bd3 O-O Nbd...,D00,3,Queen's Pawn Game: Mason Attack,Queen's Pawn Game,NaN,Mason Attack
20056,20057,True,109,Resign,White,10+0,marcodisogno,1360,jamboger,1227,e4 d6 d4 Nf6 e5 dxe5 dxe5 Qxd1+ Kxd1 Nd5 c4 Nb...,B07,4,Pirc Defense,Pirc Defense,NaN,NaN
20057,20058,True,78,Mate,Black,10+0,jamboger,1235,ffbob,1339,d4 d5 Bf4 Na6 e3 e6 c3 Nf6 Nf3 Bd7 Nbd2 b5 Bd3...,D00,3,Queen's Pawn Game: Mason Attack,Queen's Pawn Game,NaN,Mason Attack

In [7]:
df.min(numeric_only=True)

game_id              1
rated            False
turns                1
white_rating       784
black_rating       789
opening_moves        1
dtype: object

In [8]:
df.max(numeric_only=True)

game_id          20058
rated             True
turns              349
white_rating      2700
black_rating      2723
opening_moves       28
dtype: object

In [9]:
df.dtypes

game_id               int64
rated                  bool
turns                 int64
victory_status       object
winner               object
time_increment       object
white_id             object
white_rating          int64
black_id             object
black_rating          int64
moves                object
opening_code         object
opening_moves         int64
opening_fullname     object
opening_shortname    object
opening_response     object
opening_variation    object
dtype: object

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20058 entries, 0 to 20057
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   game_id            20058 non-null  int64
 1   rated              20058 non-null  bool
 2   turns              20058 non-null  int64
 3   victory_status     20058 non-null  object
 4   winner             20058 non-null  object
 5   time_increment     20058 non-null  object
 6   white_id           20058 non-null  object
 7   white_rating       20058 non-null  int64
 8   black_id           20058 non-null  object
 9   black_rating       20058 non-null  int64
 10  moves              20058 non-null  object
 11  opening_code       20058 non-null  object
 12  opening_moves      20058 non-null  int64
 13  opening_fullname   20058 non-null  object
 14  opening_shortname  20058 non-null  object
 15  opening_response   1207 non-null   object
 16  opening_variation  14398 non-null  object
dtypes: bool(1), int64(5), object(11)
memory usage: 2.5+ MB

In [11]:
df['turns'].dtypes

dtype('int64')

In [12]:
df['rated'].dtypes

dtype('bool')

In [13]:
print(df.axes)

[RangeIndex(start=0, stop=20058, step=1), Index(['game_id', 'rated', 'turns', 'victory_status', 'winner',
       'time_increment', 'white_id', 'white_rating', 'black_id',
       'black_rating', 'moves', 'opening_code', 'opening_moves',
       'opening_fullname', 'opening_shortname', 'opening_response',
       'opening_variation'],
      dtype='object')]

In [14]:
print(df.ndim)

2

In [15]:
print(df.size)

340986

In [16]:
print(df.shape)

(20058, 17)

In [17]:
print(df.values)

[[1 False 13 ... 'Slav Defense' nan 'Exchange Variation']
 [2 True 16 ... 'Nimzowitsch Defense' nan 'Kennedy Variation']
 [3 True 61 ... "King's Pawn Game" nan 'Leonardis Variation']
 ...
 [20056 True 35 ... "Queen's Pawn Game" nan 'Mason Attack']
 [20057 True 109 ... 'Pirc Defense' nan nan]
 [20058 True 78 ... "Queen's Pawn Game" nan 'Mason Attack']]

In [18]:
print("Number of records:", len(df))

Number of records: 20058

In [19]:
print("Number of records:", df.shape[0])

Number of records: 20058

In [20]:
print("Number of elements:", df.size)

Number of elements: 340986

In [21]:
print("Column Data Types:")
print(df.dtypes)

Column Data Types:
game_id               int64
rated                  bool
turns                 int64
victory_status       object
winner               object
time_increment       object
white_id             object
white_rating          int64
black_id             object
black_rating          int64
moves                object
opening_code         object
opening_moves         int64
opening_fullname     object
opening_shortname    object
opening_response     object
opening_variation    object
dtype: object

In [22]:
print("Column Names:")
print(df.columns)

Column Names:
Index(['game_id', 'rated', 'turns', 'victory_status', 'winner',
       'time_increment', 'white_id', 'white_rating', 'black_id',
       'black_rating', 'moves', 'opening_code', 'opening_moves',
       'opening_fullname', 'opening_shortname', 'opening_response',
       'opening_variation'],
      dtype='object')

In [23]:
df.describe()

            game_id         turns  white_rating  black_rating  opening_moves
count  20058.000000  20058.000000  20058.000000  20058.000000   20058.000000
mean   10029.500000     60.465999   1596.631868   1588.831987       4.816981
std     5790.390185     33.570585    291.253376    291.036126       2.797152
min        1.000000      1.000000    784.000000    789.000000       1.000000
25%     5015.250000     37.000000   1398.000000   1391.000000       3.000000
50%    10029.500000     55.000000   1567.000000   1562.000000       4.000000
75%    15043.750000     79.000000   1793.000000   1784.000000       6.000000
max    20058.000000    349.000000   2700.000000   2723.000000      28.000000

In [24]:
df.median(numeric_only=True)

game_id          10029.5
rated                1.0
turns               55.0
white_rating      1567.0
black_rating      1562.0
opening_moves        4.0
dtype: float64

In [25]:
df.mean(numeric_only=True)

game_id          10029.500000
rated                0.805414
turns               60.465999
white_rating      1596.631868
black_rating      1588.831987
opening_moves        4.816981
dtype: float64

In [26]:
df.mode(numeric_only=True)

       game_id rated  turns  white_rating  black_rating  opening_moves
0            1  True   53.0        1500.0        1500.0            3.0
1            2   NaN    NaN           NaN           NaN            NaN
2            3   NaN    NaN           NaN           NaN            NaN
3            4   NaN    NaN           NaN           NaN            NaN
4            5   NaN    NaN           NaN           NaN            NaN
...        ...   ...    ...           ...           ...            ...
20053    20054   NaN    NaN           NaN           NaN            NaN
20054    20055   NaN    NaN           NaN           NaN            NaN
20055    20056   NaN    NaN           NaN           NaN            NaN
20056    20057   NaN    NaN           NaN           NaN            NaN
20057    20058   NaN    NaN           NaN           NaN            NaN

[20058 rows x 6 columns]

In [27]:
df.std(numeric_only=True)

game_id          5790.390185
rated               0.395891
turns              33.570585
white_rating      291.253376
black_rating      291.036126
opening_moves       2.797152
dtype: float64

In [28]:
df.sample(5)

,game_id,rated,turns,victory_status,winner,time_increment,white_id,white_rating,black_id,black_rating,moves,opening_code,opening_moves,opening_fullname,opening_shortname,opening_response,opening_variation
4433,4434,True,83,Resign,White,10+0,kerboodle,2331,sorcel,2336,d4 Nf6 c4 c5 d5 b5 Nd2 Bb7 Qb3 Qb6 e4 bxc4 Qc2...,A57,7,Benko Gambit Declined | Quiet Line,Benko Gambit,Declined,NaN
15660,15661,False,23,Mate,White,15+0,julien63000,1500,josephelbouhessaini,1317,e4 e5 d4 Nc6 d5 Na5 a3 Nc4 Bxc4 Nf6 Nc3 Nxe4 N...,B00,5,Nimzowitsch Defense: Kennedy Variation | Link...,Nimzowitsch Defense,NaN,Kennedy Variation
16481,16482,True,200,Out of Time,Black,10+0,resiliente,1910,elvispy65,1827,Nf3 Nf6 d4 b6 Bf4 Bb7 e3 g6 h3 d6 Be2 Bg7 c4 O...,A47,4,Queen's Indian Defense,Queen's Indian Defense,NaN,NaN
9172,9173,True,53,Mate,White,4+6,alkhane,1190,theking1234,949,f4 e5 fxe5 Qh4+ g3 Qd8 d4 Bb4+ Nc3 Bf8 Nf3 Nc6...,A02,2,Bird Opening: From's Gambit,Bird Opening,NaN,From's Gambit
14032,14033,True,66,Mate,Black,10+5,sdmabunda,1489,yahya-qasem,1604,e4 d5 exd5 Nf6 Nc3 e6 dxe6 Bxe6 Nf3 Bc5 d4 Bb4...,B01,4,Scandinavian Defense: Modern Variation #2,Scandinavian Defense,NaN,Modern Variation #2

In [29]:
df.sample(20)

,game_id,rated,turns,victory_status,winner,time_increment,white_id,white_rating,black_id,black_rating,moves,opening_code,opening_moves,opening_fullname,opening_shortname,opening_response,opening_variation
777,778,True,68,Resign,Black,10+0,chessgoals,1437,alex_smite,1476,e4 e5 Nf3 Nc6 Bb5 d6 d4 a6 Ba4 b5 Bb3 exd4 Nxd...,C62,6,Ruy Lopez: Steinitz Defense,Ruy Lopez,NaN,Steinitz Defense
8982,8983,True,85,Resign,White,10+0,nullbyte,1707,yasutora,1637,d4 d5 c4 c6 Nc3 Nf6 Bf4 Bf5 Nf3 Nbd7 e3 e6 Bd3...,D10,5,Slav Defense #2,Slav Defense,NaN,#2
7978,7979,True,29,Resign,White,10+0,mastercaique,1373,hd_aslani,1445,e4 e5 Nf3 Nc6 Bb5 d6 d4 exd4 Nxd4 Bd7 Nc3 Nxd4...,C62,6,Ruy Lopez: Steinitz Defense,Ruy Lopez,NaN,Steinitz Defense
12988,12989,True,81,Mate,White,10+0,jtsae,1535,youredeadmeat,1455,b3 d5 Bb2 Nf6 Nf3 e6 e3 b6 d4 Bb7 Bd3 Be7 O-O ...,A01,2,Nimzo-Larsen Attack: Classical Variation,Nimzo-Larsen Attack,NaN,Classical Variation
3762,3763,True,22,Resign,Black,20+15,amaozinhadotemer,1234,misfox,1096,Nh3 e5 e4 Nc6 d3 Bd6 Nc3 f6 Nd5 Nge7 Nb4 Nxb4 ...,E00,1,Amar Opening,Amar Opening,NaN,NaN
18368,18369,True,39,Resign,White,14+2,stutberidze,1076,pedrovenanci,1440,e4 e5 Bc4 h6 Qf3 Nf6 Nh3 d6 d3 Nc6 Nc3 Na5 Bb5...,C23,3,Bishop's Opening,Bishop's Opening,NaN,NaN
11281,11282,True,113,Resign,White,15+0,bageryan,1508,vladimir-kramnik-1,1586,d4 d5 Bg5 Nc6 h3 f6 Bh4 e5 c3 Nge7 e3 Ng6 Bg3 ...,D00,3,Queen's Pawn Game: Levitsky Attack,Queen's Pawn Game,NaN,Levitsky Attack
18550,18551,True,83,Resign,White,5+8,maforma,1822,sagansaxo,1629,e4 e5 f4 Nc6 Nf3 exf4 Bc4 d6 O-O a6 a3 Nf6 d3 ...,C34,6,King's Gambit Accepted | MacLeod Defense,King's Gambit,Accepted,NaN
14745,14746,True,41,Mate,White,10+0,horst36,1417,sergeiv011988,1407,c4 Nf6 d4 g6 d5 e6 a3 Bg7 Nc3 O-O Nf3 c6 Bg5 c...,E60,5,Indian Game: Anti-Gruenfeld | Advance Variation,Indian Game,NaN,Anti-Gruenfeld
8464,8465,True,40,Resign,Black,10+0,smail94,943,seanngo53,1013,d4 d5 Nc3 e6 e4 Nc6 exd5 Nxd4 dxe6 Nxe6 Bb5+ c...,C10,7,French Defense: Classical Variation | Svenoni...,French Defense,NaN,Classical Variation
7407,7408,True,24,Resign,White,5+8,gosette,1433,thatguythatistr,1509,d4 g6 c4 Bg7 Nc3 e6 Bf4 Ne7 Nb5 d6 c5 Na6 cxd6...,A40,2,Modern Defense,Modern Defense,NaN,NaN
3332,3333,True,99,Out of Time,White,10+0,ri_chess,1532,martinlutherking,1472,e4 e6 d4 c6 Nf3 Nf6 Nc3 Bb4 Bg5 h6 Bh4 g5 Nxg5...,C00,3,French Defense: Normal Variation,French Defense,NaN,Normal Variation
19427,19428,False,48,Mate,Black,30+0,amaljohn090,1500,lbringer,1715,e4 c5 Nf3 d6 Bc4 Nc6 Ng5 e6 Qf3 Qxg5 d3 Nd4 Qd...,B50,4,Sicilian Defense,Sicilian Defense,NaN,NaN
12356,12357,True,5,Resign,White,10+3,dfdghgh,1482,angelmedina,1403,d4 d5 Bf4 e5 Bxe5,D00,3,Queen's Pawn Game: Mason Attack,Queen's Pawn Game,NaN,Mason Attack
1026,1027,False,55,Resign,White,8+3,samuelwise,1452,soprotheygowhoa,1343,e4 e5 f4 exf4 Nf3 d6 d4 Bg4 Bxf4 Bxf3 Qxf3 Nf6...,C34,6,King's Gambit Accepted | Fischer Defense,King's Gambit,Accepted,NaN
2988,2989,True,19,Resign,White,10+0,fandm-lancaster,1302,aorik,1236,c3 e5 e4 Bc5 Qe2 d5 Nf3 dxe4 Nxe5 Nh6 c4 Na6 N...,C20,3,King's Pawn Game: Macleod Attack,King's Pawn Game,NaN,Macleod Attack
17889,17890,True,61,Out of Time,White,10+0,bosspotato,2305,tal-capa,2311,d4 d5 Nf3 c6 Bf4 Nf6 Nbd2 e6 e3 Bd6 Ne5 Qe7 Bd...,D02,3,Queen's Pawn Game: Zukertort Variation,Queen's Pawn Game,NaN,Zukertort Variation
1932,1933,True,67,Mate,White,10+0,acustic,1550,brorael357,1321,e4 d5 e5 d4 Qf3 Be6 c3 dxc3 bxc3 g6 d4 Bg7 Qxb...,B01,2,Scandinavian Defense,Scandinavian Defense,NaN,NaN
9152,9153,True,63,Resign,White,8+0,otco,1340,woodham,1235,e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 Nxd4 Qxd4 d6 Bd3 e5...,B32,7,Sicilian Defense: Open #3,Sicilian Defense,NaN,Open #3
9286,9287,True,3,Out of Time,White,6+8,dmka,1362,arfhan,1265,e4 d5 e5,B01,2,Scandinavian Defense,Scandinavian Defense,NaN,NaN

In [30]:
# Remove rows with missing values
df.dropna()

,game_id,rated,turns,victory_status,winner,time_increment,white_id,white_rating,black_id,black_rating,moves,opening_code,opening_moves,opening_fullname,opening_shortname,opening_response,opening_variation
29,30,True,66,Mate,Black,10+10,shivangithegenius,1077,chinmaysharma,1148,d4 d5 c4 Nf6 Nc3 Nc6 Nf3 e6 e3 Bd6 Bd3 Ne4 Bxe...,D06,4,Queen's Gambit Refused: Marshall Defense,Queen's Gambit,Refused,Marshall Defense
33,34,False,21,Resign,Black,15+3,shivangithegenius,1019,shamlanaseer,1500,d4 d5 c4 dxc4 e4 b5 Na3 a6 Qf3 f6 e5 fxe5 Qxa8...,D20,6,Queen's Gambit Accepted: Central Variation | ...,Queen's Gambit,Accepted,Central Variation
98,99,True,113,Draw,Draw,15+0,avelez8,1745,anonymous1705,1714,d4 d5 c4 Nf6 Nc3 Bf5 Bf4 a6 Nf3 e6 a3 Nc6 e3 B...,D06,4,Queen's Gambit Refused: Marshall Defense,Queen's Gambit,Refused,Marshall Defense
99,100,True,62,Resign,White,15+0,avelez8,1734,ars01,1748,d4 d5 c4 Nf6 Nc3 dxc4 e3 Be6 Nf3 a6 b3 cxb3 ax...,D06,4,Queen's Gambit Refused: Marshall Defense,Queen's Gambit,Refused,Marshall Defense
107,108,True,91,Resign,White,10+0,totoymate,1721,avelez8,1750,d4 d5 c4 e6 Nf3 Nf6 Bg5 Be7 e3 c6 Bd3 dxc4 Bxc...,D30,7,Queen's Gambit Declined: Traditional Variation,Queen's Gambit,Declined,Traditional Variation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19980,19981,True,71,Resign,White,30+30,rb52,2057,ed84,1782,d4 d5 c4 e6 Nc3 Nf6 Bg5 Be7 e3 h6 Bh4 O-O Nf3 ...,D55,13,Queen's Gambit Declined: Neo-Orthodox Variatio...,Queen's Gambit,Declined,Neo-Orthodox Variation
19988,19989,True,57,Resign,White,15+5,rb52,2058,aa2000,1833,d4 d5 c4 e5 dxe5 d4 Nf3 Nc6 a3 Bg4 Bf4 Bc5 b4 ...,D08,7,Queen's Gambit Refused: Albin Countergambit | ...,Queen's Gambit,Refused,Albin Countergambit
19989,19990,True,45,Resign,White,10+2,rb52,2050,bezadisa,1894,d4 d5 c4 dxc4 e3 c5 Bxc4 cxd4 exd4 Nf6 Nf3 Bg4...,D20,5,Queen's Gambit Accepted: Old Variation,Queen's Gambit,Accepted,Old Variation
19993,19994,True,119,Draw,Draw,15+5,rb52,2049,denci,1895,d4 d5 c4 e6 Nc3 dxc4 e4 g6 Bxc4 Bg7 Nf3 c6 O-O...,D31,5,Queen's Gambit Declined: Queen's Knight Variation,Queen's Gambit,Declined,Queen's Knight Variation
20000,20001,True,29,Resign,White,7+2,rb52,1989,farshid_ghasemi,1653,d4 d5 c4 c6 Nc3 dxc4 a4 Bf5 e3 e6 Bxc4 Nf6 Nf3...,D19,15,Queen's Gambit Declined: Slav | Dutch Variation,Queen's Gambit,Declined,Slav

In [31]:
# List all attributes and methods of the DataFrame
dir(df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_arith_method_with_reindex',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_create_data_for_split_and_tight_to_dict',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_nocopy',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'black_id',
 'black_rating',
 'bool',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'game_id',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'moves',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'opening_code',
 'opening_fullname',
 'opening_moves',
 'opening_response',
 'opening_shortname',
 'opening_variation',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rated',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'time_increment',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'turns',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'victory_status',
 'where',
 'white_id',
 'white_rating',
 'winner',
 'xs']

In [32]:
print("Mean values of the first 50 records:")
print(df.head(50).mean(numeric_only=True))

Mean values of the first 50 records:
game_id            25.50
rated               0.38
turns              41.22
white_rating     1392.02
black_rating     1233.24
opening_moves       5.32
dtype: float64

In [33]:
print("Mean values of the last 50 records:")
print(df.tail(50).mean(numeric_only=True))

Mean values of the last 50 records:
game_id          20033.50
rated                0.96
turns               59.02
white_rating      1606.56
black_rating      1633.98
opening_moves        5.68
dtype: float64

In [34]:
df.columns

Index(['game_id', 'rated', 'turns', 'victory_status', 'winner',
       'time_increment', 'white_id', 'white_rating', 'black_id',
       'black_rating', 'moves', 'opening_code', 'opening_moves',
       'opening_fullname', 'opening_shortname', 'opening_response',
       'opening_variation'],
      dtype='object')

In [35]:
df['rated']

0        False
1         True
2         True
3         True
4         True
         ...
20053     True
20054     True
20055     True
20056     True
20057     True
Name: rated, Length: 20058, dtype: bool

In [36]:
df['victory_status'].describe()

count      20058
unique         4
top       Resign
freq       11147
Name: victory_status, dtype: object

In [37]:
df['winner'].describe()

count     20058
unique        3
top       White
freq      10001
Name: winner, dtype: object

In [38]:
df['moves'].count()

np.int64(20058)

In [39]:
df['opening_shortname'].count()

np.int64(20058)

In [40]:
df['rated'].mean()

np.float64(0.8054142985342507)

In [41]:
df['game_id'].mean()

np.float64(10029.5)

In [42]:
df[10:20]

,game_id,rated,turns,victory_status,winner,time_increment,white_id,white_rating,black_id,black_rating,moves,opening_code,opening_moves,opening_fullname,opening_shortname,opening_response,opening_variation
10,11,False,39,Mate,White,20+60,daniel_likes_chess,1381,anaissac,1272,e3 e6 d4 d6 Bd3 c6 Nf3 Be7 Nc3 Nf6 Bd2 Bd7 Qe2...,A00,1,Van't Kruijs Opening,Van't Kruijs Opening,NaN,NaN
11,12,False,38,Resign,Black,20+60,daniel_likes_chess,1381,subham777,1867,e4 e6 d4 d5 e5 c5 c3 Nc6 Nf3 Qb6 Be3 Qxb2 Nbd2...,C02,9,French Defense: Advance Variation | Paulsen A...,French Defense,NaN,Advance Variation
12,13,False,60,Resign,Black,5+40,daniel_likes_chess,1381,roman12342005,1936,e4 e6 Nf3 d5 exd5 exd5 Qe2+ Be7 Nc3 Nf6 d4 O-O...,C00,3,French Defense: Knight Variation,French Defense,NaN,Knight Variation
13,14,False,31,Resign,Black,8+0,daniel_likes_chess,1381,alkhan,1607,e4 e6 Qh5 g6 Qe5 Nf6 d4 d6 Qb5+ Bd7 Qxb7 Bc6 Q...,C00,2,French Defense #2,French Defense,NaN,#2
14,15,False,31,Mate,White,15+15,shivangithegenius,1094,sureka_akshat,1141,e4 e5 Nf3 Nc6 Bc4 Nf6 Nc3 Bc5 O-O O-O d3 Ne8 B...,C50,8,Four Knights Game: Italian Variation,Four Knights Game,NaN,Italian Variation
15,16,False,43,Resign,Black,15+15,sureka_akshat,1141,shivangithegenius,1094,e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 Qe7 O-O Nxe4 Nxe4 h6...,C57,7,Italian Game: Two Knights Defense | Knight At...,Italian Game,NaN,Two Knights Defense
16,17,False,52,Resign,Black,15+15,shivangithegenius,1094,sureka_akshat,1141,e4 e5 Nf3 Nc6 Bc4 Nf6 Nc3 Bc5 O-O O-O Ne1 d6 d...,C50,8,Four Knights Game: Italian Variation,Four Knights Game,NaN,Italian Variation
17,18,False,66,Mate,Black,15+16,sureka_akshat,1141,shivangithegenius,1094,e4 e5 Nf3 Nc6 Bc4 Nf6 Nc3 Bc5 O-O O-O Ne1 Ne8 ...,C50,8,Four Knights Game: Italian Variation,Four Knights Game,NaN,Italian Variation
18,19,False,101,Resign,Black,15+15,shivangithegenius,1094,slam_ment,1300,e4 e5 Nf3 d6 Bc4 Be6 d3 Bxc4 dxc4 c5 O-O h6 Nc...,C41,5,Philidor Defense #3,Philidor Defense,NaN,#3
19,20,False,25,Resign,White,11+0,g-ios,1500,shivangithegenius,1094,d4 d5 h3 Nc6 Nf3 Nf6 Bg5 h6 Bxf6 exf6 e3 Bb4+ ...,D00,2,Queen's Pawn Game,Queen's Pawn Game,NaN,NaN

In [43]:
df[10:30]

,game_id,rated,turns,victory_status,winner,time_increment,white_id,white_rating,black_id,black_rating,moves,opening_code,opening_moves,opening_fullname,opening_shortname,opening_response,opening_variation
10,11,False,39,Mate,White,20+60,daniel_likes_chess,1381,anaissac,1272,e3 e6 d4 d6 Bd3 c6 Nf3 Be7 Nc3 Nf6 Bd2 Bd7 Qe2...,A00,1,Van't Kruijs Opening,Van't Kruijs Opening,NaN,NaN
11,12,False,38,Resign,Black,20+60,daniel_likes_chess,1381,subham777,1867,e4 e6 d4 d5 e5 c5 c3 Nc6 Nf3 Qb6 Be3 Qxb2 Nbd2...,C02,9,French Defense: Advance Variation | Paulsen A...,French Defense,NaN,Advance Variation
12,13,False,60,Resign,Black,5+40,daniel_likes_chess,1381,roman12342005,1936,e4 e6 Nf3 d5 exd5 exd5 Qe2+ Be7 Nc3 Nf6 d4 O-O...,C00,3,French Defense: Knight Variation,French Defense,NaN,Knight Variation
13,14,False,31,Resign,Black,8+0,daniel_likes_chess,1381,alkhan,1607,e4 e6 Qh5 g6 Qe5 Nf6 d4 d6 Qb5+ Bd7 Qxb7 Bc6 Q...,C00,2,French Defense #2,French Defense,NaN,#2
14,15,False,31,Mate,White,15+15,shivangithegenius,1094,sureka_akshat,1141,e4 e5 Nf3 Nc6 Bc4 Nf6 Nc3 Bc5 O-O O-O d3 Ne8 B...,C50,8,Four Knights Game: Italian Variation,Four Knights Game,NaN,Italian Variation
15,16,False,43,Resign,Black,15+15,sureka_akshat,1141,shivangithegenius,1094,e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 Qe7 O-O Nxe4 Nxe4 h6...,C57,7,Italian Game: Two Knights Defense | Knight At...,Italian Game,NaN,Two Knights Defense
16,17,False,52,Resign,Black,15+15,shivangithegenius,1094,sureka_akshat,1141,e4 e5 Nf3 Nc6 Bc4 Nf6 Nc3 Bc5 O-O O-O Ne1 d6 d...,C50,8,Four Knights Game: Italian Variation,Four Knights Game,NaN,Italian Variation
17,18,False,66,Mate,Black,15+16,sureka_akshat,1141,shivangithegenius,1094,e4 e5 Nf3 Nc6 Bc4 Nf6 Nc3 Bc5 O-O O-O Ne1 Ne8 ...,C50,8,Four Knights Game: Italian Variation,Four Knights Game,NaN,Italian Variation
18,19,False,101,Resign,Black,15+15,shivangithegenius,1094,slam_ment,1300,e4 e5 Nf3 d6 Bc4 Be6 d3 Bxc4 dxc4 c5 O-O h6 Nc...,C41,5,Philidor Defense #3,Philidor Defense,NaN,#3
19,20,False,25,Resign,White,11+0,g-ios,1500,shivangithegenius,1094,d4 d5 h3 Nc6 Nf3 Nf6 Bg5 h6 Bxf6 exf6 e3 Bb4+ ...,D00,2,Queen's Pawn Game,Queen's Pawn Game,NaN,NaN
20,21,False,14,Resign,Black,15+15,shivangithegenius,1094,lex_v1,1676,e4 e5 Nf3 Nc6 Bc4 h6 O-O Bc5 d3 Nf6 Nc3 Ng4 h3...,C55,6,Italian Game: Anti-Fried Liver Defense,Italian Game,NaN,Anti-Fried Liver Defense
21,22,False,3,Resign,White,30+60,shivangithegenius,1094,themannichreaction,1068,d4 e6 Nc3,A40,2,Horwitz Defense,Horwitz Defense,NaN,NaN
22,23,False,17,Resign,White,15+5,storm28rus,1500,shivangithegenius,1094,e4 c5 Bc4 Nf6 Nc3 d6 Nf3 g6 Ng5 e6 d3 Bg7 O-O ...,B20,3,Sicilian Defense: Bowdler Attack,Sicilian Defense,NaN,Bowdler Attack
23,24,True,36,Resign,White,10+0,robotsmoke,1307,shivangithegenius,1106,c4 Nc6 Nc3 e5 g3 Bc5 Bg2 Nge7 e3 b6 a3 Bb7 b4 ...,A25,4,English Opening: King's English Variation | R...,English Opening,NaN,King's English Variation
24,25,True,13,Resign,Black,10+0,shivangithegenius,1113,ivangonzalez123,1423,e4 c5 d4 cxd4 Qxd4 Nc6 Qa4 e5 Be3 Nf6 Nf3 h6 Nc3,B21,3,Sicilian Defense: Smith-Morra Gambit #2,Sicilian Defense,NaN,Smith-Morra Gambit #2
25,26,True,69,Mate,White,10+10,shivangithegenius,1078,sureka_akshat,1219,d4 d5 Nc3 Nf6 Bf4 Bf5 Nf3 e6 e3 Be7 Bb5+ c6 Bd...,D01,4,Queen's Pawn Game: Chigorin Variation,Queen's Pawn Game,NaN,Chigorin Variation
26,27,True,43,Resign,White,10+10,gmcarlsen403,1825,shivangithegenius,1079,e4 e5 Nf3 Nc6 d4 exd4 Bc4 Bc5 c3 dxc3 Bxf7+ Kx...,C45,8,Scotch Game: Haxo Gambit,Scotch Game,NaN,Haxo Gambit
27,28,True,54,Mate,Black,10+10,mannat1,1328,shivangithegenius,1038,d4 d5 Nc3 Nf6 Nf3 Nc6 e3 Bf5 h4 e6 g3 Bb4 a3 B...,D01,4,Queen's Pawn Game: Chigorin Variation,Queen's Pawn Game,NaN,Chigorin Variation
28,29,True,53,Resign,Black,10+10,shivangithegenius,1056,biyanivedant01,1156,d4 d5 c4 c6 e3 dxc4 Bxc4 Nf6 Nc3 e6 e4 e5 d5 c...,D10,4,Slav Defense,Slav Defense,NaN,NaN
29,30,True,66,Mate,Black,10+10,shivangithegenius,1077,chinmaysharma,1148,d4 d5 c4 Nf6 Nc3 Nc6 Nf3 e6 e3 Bd6 Bd3 Ne4 Bxe...,D06,4,Queen's Gambit Refused: Marshall Defense,Queen's Gambit,Refused,Marshall Defense

In [44]:
df.loc[10:20,['game_id', 'rated', 'turns', 'victory_status']]

    game_id  rated  turns victory_status
10       11  False     39           Mate
11       12  False     38         Resign
12       13  False     60         Resign
13       14  False     31         Resign
14       15  False     31           Mate
15       16  False     43         Resign
16       17  False     52         Resign
17       18  False     66           Mate
18       19  False    101         Resign
19       20  False     25         Resign
20       21  False     14         Resign

In [45]:
df.loc[34:40,['opening_shortname', 'opening_response']]

            opening_shortname opening_response
34           Sicilian Defense              NaN
35  Robatsch (Modern) Defense              NaN
36     Blackmar-Diemer Gambit              NaN
37                Indian Game              NaN
38           Sicilian Defense              NaN
39            English Opening              NaN
40           Sicilian Defense              NaN

In [46]:
#MISSING VALUE
df.dropna(how='all')

,game_id,rated,turns,victory_status,winner,time_increment,white_id,white_rating,black_id,black_rating,moves,opening_code,opening_moves,opening_fullname,opening_shortname,opening_response,opening_variation
0,1,False,13,Out of Time,White,15+2,bourgris,1500,a-00,1191,d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...,D10,5,Slav Defense: Exchange Variation,Slav Defense,NaN,Exchange Variation
1,2,True,16,Resign,Black,5+10,a-00,1322,skinnerua,1261,d4 Nc6 e4 e5 f4 f6 dxe5 fxe5 fxe5 Nxe5 Qd4 Nc6...,B00,4,Nimzowitsch Defense: Kennedy Variation,Nimzowitsch Defense,NaN,Kennedy Variation
2,3,True,61,Mate,White,5+10,ischia,1496,a-00,1500,e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...,C20,3,King's Pawn Game: Leonardis Variation,King's Pawn Game,NaN,Leonardis Variation
3,4,True,61,Mate,White,20+0,daniamurashov,1439,adivanov2009,1454,d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...,D02,3,Queen's Pawn Game: Zukertort Variation,Queen's Pawn Game,NaN,Zukertort Variation
4,5,True,95,Mate,White,30+3,nik221107,1523,adivanov2009,1469,e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...,C41,5,Philidor Defense,Philidor Defense,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20053,20054,True,24,Resign,White,10+10,belcolt,1691,jamboger,1220,d4 f5 e3 e6 Nf3 Nf6 Nc3 b6 Be2 Bb7 O-O Be7 Ne5...,A80,2,Dutch Defense,Dutch Defense,NaN,NaN
20054,20055,True,82,Mate,Black,10+0,jamboger,1233,farrukhasomiddinov,1196,d4 d6 Bf4 e5 Bg3 Nf6 e3 exd4 exd4 d5 c3 Bd6 Bd...,A41,2,Queen's Pawn,Queen's Pawn,NaN,NaN
20055,20056,True,35,Mate,White,10+0,jamboger,1219,schaaksmurf3,1286,d4 d5 Bf4 Nc6 e3 Nf6 c3 e6 Nf3 Be7 Bd3 O-O Nbd...,D00,3,Queen's Pawn Game: Mason Attack,Queen's Pawn Game,NaN,Mason Attack
20056,20057,True,109,Resign,White,10+0,marcodisogno,1360,jamboger,1227,e4 d6 d4 Nf6 e5 dxe5 dxe5 Qxd1+ Kxd1 Nd5 c4 Nb...,B07,4,Pirc Defense,Pirc Defense,NaN,NaN
20057,20058,True,78,Mate,Black,10+0,jamboger,1235,ffbob,1339,d4 d5 Bf4 Na6 e3 e6 c3 Nf6 Nf3 Bd7 Nbd2 b5 Bd3...,D00,3,Queen's Pawn Game: Mason Attack,Queen's Pawn Game,NaN,Mason Attack

In [47]:
df.dropna(axis=1, how='all')

,game_id,rated,turns,victory_status,winner,time_increment,white_id,white_rating,black_id,black_rating,moves,opening_code,opening_moves,opening_fullname,opening_shortname,opening_response,opening_variation
0,1,False,13,Out of Time,White,15+2,bourgris,1500,a-00,1191,d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...,D10,5,Slav Defense: Exchange Variation,Slav Defense,NaN,Exchange Variation
1,2,True,16,Resign,Black,5+10,a-00,1322,skinnerua,1261,d4 Nc6 e4 e5 f4 f6 dxe5 fxe5 fxe5 Nxe5 Qd4 Nc6...,B00,4,Nimzowitsch Defense: Kennedy Variation,Nimzowitsch Defense,NaN,Kennedy Variation
2,3,True,61,Mate,White,5+10,ischia,1496,a-00,1500,e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...,C20,3,King's Pawn Game: Leonardis Variation,King's Pawn Game,NaN,Leonardis Variation
3,4,True,61,Mate,White,20+0,daniamurashov,1439,adivanov2009,1454,d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...,D02,3,Queen's Pawn Game: Zukertort Variation,Queen's Pawn Game,NaN,Zukertort Variation
4,5,True,95,Mate,White,30+3,nik221107,1523,adivanov2009,1469,e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...,C41,5,Philidor Defense,Philidor Defense,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20053,20054,True,24,Resign,White,10+10,belcolt,1691,jamboger,1220,d4 f5 e3 e6 Nf3 Nf6 Nc3 b6 Be2 Bb7 O-O Be7 Ne5...,A80,2,Dutch Defense,Dutch Defense,NaN,NaN
20054,20055,True,82,Mate,Black,10+0,jamboger,1233,farrukhasomiddinov,1196,d4 d6 Bf4 e5 Bg3 Nf6 e3 exd4 exd4 d5 c3 Bd6 Bd...,A41,2,Queen's Pawn,Queen's Pawn,NaN,NaN
20055,20056,True,35,Mate,White,10+0,jamboger,1219,schaaksmurf3,1286,d4 d5 Bf4 Nc6 e3 Nf6 c3 e6 Nf3 Be7 Bd3 O-O Nbd...,D00,3,Queen's Pawn Game: Mason Attack,Queen's Pawn Game,NaN,Mason Attack
20056,20057,True,109,Resign,White,10+0,marcodisogno,1360,jamboger,1227,e4 d6 d4 Nf6 e5 dxe5 dxe5 Qxd1+ Kxd1 Nd5 c4 Nb...,B07,4,Pirc Defense,Pirc Defense,NaN,NaN
20057,20058,True,78,Mate,Black,10+0,jamboger,1235,ffbob,1339,d4 d5 Bf4 Na6 e3 e6 c3 Nf6 Nf3 Bd7 Nbd2 b5 Bd3...,D00,3,Queen's Pawn Game: Mason Attack,Queen's Pawn Game,NaN,Mason Attack

In [49]:
df.min(numeric_only=True)

game_id              1
rated            False
turns                1
white_rating       784
black_rating       789
opening_moves        1
dtype: object

In [51]:
df.max(numeric_only=True)

game_id          20058
rated             True
turns              349
white_rating      2700
black_rating      2723
opening_moves       28
dtype: object

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20058 entries, 0 to 20057
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   game_id            20058 non-null  int64
 1   rated              20058 non-null  bool
 2   turns              20058 non-null  int64
 3   victory_status     20058 non-null  object
 4   winner             20058 non-null  object
 5   time_increment     20058 non-null  object
 6   white_id           20058 non-null  object
 7   white_rating       20058 non-null  int64
 8   black_id           20058 non-null  object
 9   black_rating       20058 non-null  int64
 10  moves              20058 non-null  object
 11  opening_code       20058 non-null  object
 12  opening_moves      20058 non-null  int64
 13  opening_fullname   20058 non-null  object
 14  opening_shortname  20058 non-null  object
 15  opening_response   1207 non-null   object
 16  opening_variation  14398 non-null  object
dtypes: bool(1), int64(5), object(11)
memory usage: 2.5+ MB