In [111]:
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib as mpl
import seaborn as sns
df =pd.read_excel("/content/Coffee Shop Sales.xlsx")

In [112]:
df.head()

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
0,1,2023-01-01,07:06:11,2,5,Lower Manhattan,32,3.0,Coffee,Gourmet brewed coffee,Ethiopia Rg
1,2,2023-01-01,07:08:56,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
2,3,2023-01-01,07:14:04,2,5,Lower Manhattan,59,4.5,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
3,4,2023-01-01,07:20:24,1,5,Lower Manhattan,22,2.0,Coffee,Drip coffee,Our Old Time Diner Blend Sm
4,5,2023-01-01,07:22:41,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg

In [113]:
df.head(10)

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
0,1,2023-01-01,07:06:11,2,5,Lower Manhattan,32,3.00,Coffee,Gourmet brewed coffee,Ethiopia Rg
1,2,2023-01-01,07:08:56,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
2,3,2023-01-01,07:14:04,2,5,Lower Manhattan,59,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
3,4,2023-01-01,07:20:24,1,5,Lower Manhattan,22,2.00,Coffee,Drip coffee,Our Old Time Diner Blend Sm
4,5,2023-01-01,07:22:41,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
5,6,2023-01-01,07:22:41,1,5,Lower Manhattan,77,3.00,Bakery,Scone,Oatmeal Scone
6,7,2023-01-01,07:25:49,1,5,Lower Manhattan,22,2.00,Coffee,Drip coffee,Our Old Time Diner Blend Sm
7,8,2023-01-01,07:33:34,2,5,Lower Manhattan,28,2.00,Coffee,Gourmet brewed coffee,Columbian Medium Roast Sm
8,9,2023-01-01,07:39:13,1,5,Lower Manhattan,39,4.25,Coffee,Barista Espresso,Latte Rg
9,10,2023-01-01,07:39:34,2,5,Lower Manhattan,58,3.50,Drinking Chocolate,Hot chocolate,Dark chocolate Rg

In [114]:
df.head(20)

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
0,1,2023-01-01,07:06:11,2,5,Lower Manhattan,32,3.00,Coffee,Gourmet brewed coffee,Ethiopia Rg
1,2,2023-01-01,07:08:56,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
2,3,2023-01-01,07:14:04,2,5,Lower Manhattan,59,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
3,4,2023-01-01,07:20:24,1,5,Lower Manhattan,22,2.00,Coffee,Drip coffee,Our Old Time Diner Blend Sm
4,5,2023-01-01,07:22:41,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
5,6,2023-01-01,07:22:41,1,5,Lower Manhattan,77,3.00,Bakery,Scone,Oatmeal Scone
6,7,2023-01-01,07:25:49,1,5,Lower Manhattan,22,2.00,Coffee,Drip coffee,Our Old Time Diner Blend Sm
7,8,2023-01-01,07:33:34,2,5,Lower Manhattan,28,2.00,Coffee,Gourmet brewed coffee,Columbian Medium Roast Sm
8,9,2023-01-01,07:39:13,1,5,Lower Manhattan,39,4.25,Coffee,Barista Espresso,Latte Rg
9,10,2023-01-01,07:39:34,2,5,Lower Manhattan,58,3.50,Drinking Chocolate,Hot chocolate,Dark chocolate Rg
10,11,2023-01-01,07:43:05,1,5,Lower Manhattan,56,2.55,Tea,Brewed Chai tea,Spicy Eye Opener Chai Rg
11,12,2023-01-01,07:44:35,2,5,Lower Manhattan,33,3.50,Coffee,Gourmet brewed coffee,Ethiopia Lg
12,13,2023-01-01,07:45:51,1,5,Lower Manhattan,51,3.00,Tea,Brewed Black tea,Earl Grey Lg
13,14,2023-01-01,07:48:19,1,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
14,15,2023-01-01,07:52:36,2,5,Lower Manhattan,87,3.00,Coffee,Barista Espresso,Ouro Brasileiro shot
15,16,2023-01-01,07:59:58,2,5,Lower Manhattan,47,3.00,Tea,Brewed Green tea,Serenity Green Tea Lg
16,17,2023-01-01,07:59:58,1,5,Lower Manhattan,79,3.75,Bakery,Scone,Jumbo Savory Scone
17,18,2023-01-01,08:00:18,1,8,Hell's Kitchen,42,2.50,Tea,Brewed herbal tea,Lemon Grass Rg
18,19,2023-01-01,08:00:39,2,8,Hell's Kitchen,59,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
19,20,2023-01-01,08:11:45,1,8,Hell's Kitchen,61,4.75,Drinking Chocolate,Hot chocolate,Sustainably Grown Organic Lg

In [115]:
df.tail()

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
149111,149452,2023-06-30,20:18:41,2,8,Hell's Kitchen,44,2.50,Tea,Brewed herbal tea,Peppermint Rg
149112,149453,2023-06-30,20:25:10,2,8,Hell's Kitchen,49,3.00,Tea,Brewed Black tea,English Breakfast Lg
149113,149454,2023-06-30,20:31:34,1,8,Hell's Kitchen,45,3.00,Tea,Brewed herbal tea,Peppermint Lg
149114,149455,2023-06-30,20:57:19,1,8,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,Cappuccino
149115,149456,2023-06-30,20:57:19,2,8,Hell's Kitchen,64,0.80,Flavours,Regular syrup,Hazelnut syrup

In [116]:
df.tail(12)

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
149104,149445,2023-06-30,19:52:28,2,3,Astoria,34,2.45,Coffee,Premium brewed coffee,Jamaican Coffee River Sm
149105,149446,2023-06-30,19:53:46,1,3,Astoria,24,3.00,Coffee,Drip coffee,Our Old Time Diner Blend Lg
149106,149447,2023-06-30,19:56:45,1,8,Hell's Kitchen,33,3.50,Coffee,Gourmet brewed coffee,Ethiopia Lg
149107,149448,2023-06-30,19:57:49,2,3,Astoria,54,2.50,Tea,Brewed Chai tea,Morning Sunrise Chai Rg
149108,149449,2023-06-30,19:57:49,1,3,Astoria,70,3.25,Bakery,Scone,Cranberry Scone
149109,149450,2023-06-30,20:08:38,2,8,Hell's Kitchen,55,4.00,Tea,Brewed Chai tea,Morning Sunrise Chai Lg
149110,149451,2023-06-30,20:16:31,2,5,Lower Manhattan,42,2.50,Tea,Brewed herbal tea,Lemon Grass Rg
149111,149452,2023-06-30,20:18:41,2,8,Hell's Kitchen,44,2.50,Tea,Brewed herbal tea,Peppermint Rg
149112,149453,2023-06-30,20:25:10,2,8,Hell's Kitchen,49,3.00,Tea,Brewed Black tea,English Breakfast Lg
149113,149454,2023-06-30,20:31:34,1,8,Hell's Kitchen,45,3.00,Tea,Brewed herbal tea,Peppermint Lg
149114,149455,2023-06-30,20:57:19,1,8,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,Cappuccino
149115,149456,2023-06-30,20:57:19,2,8,Hell's Kitchen,64,0.80,Flavours,Regular syrup,Hazelnut syrup

In [117]:
df.min(numeric_only=True)

transaction_id     1.0
transaction_qty    1.0
store_id           3.0
product_id         1.0
unit_price         0.8
dtype: float64

In [118]:
df.max(numeric_only=True)

transaction_id     149456.0
transaction_qty         8.0
store_id                8.0
product_id             87.0
unit_price             45.0
dtype: float64

In [119]:
df.dtypes

transaction_id               int64
transaction_date    datetime64[ns]
transaction_time            object
transaction_qty              int64
store_id                     int64
store_location              object
product_id                   int64
unit_price                 float64
product_category            object
product_type                object
product_detail              object
dtype: object

In [120]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149116 entries, 0 to 149115
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    149116 non-null  int64
 1   transaction_date  149116 non-null  datetime64[ns]
 2   transaction_time  149116 non-null  object
 3   transaction_qty   149116 non-null  int64
 4   store_id          149116 non-null  int64
 5   store_location    149116 non-null  object
 6   product_id        149116 non-null  int64
 7   unit_price        149116 non-null  float64
 8   product_category  149116 non-null  object
 9   product_type      149116 non-null  object
 10  product_detail    149116 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(4), object(5)
memory usage: 12.5+ MB

In [123]:
df['product_id'].dtypes

dtype('int64')

In [124]:
df['product_type'].dtypes

dtype('O')

In [125]:
print(df.axes)

[RangeIndex(start=0, stop=149116, step=1), Index(['transaction_id', 'transaction_date', 'transaction_time',
       'transaction_qty', 'store_id', 'store_location', 'product_id',
       'unit_price', 'product_category', 'product_type', 'product_detail'],
      dtype='object')]

In [126]:
print(df.ndim)

2

In [127]:
print(df.size)

1640276

In [128]:
print(df.shape)

(149116, 11)

In [129]:
print(df.values)

[[1 Timestamp('2023-01-01 00:00:00') datetime.time(7, 6, 11) ... 'Coffee'
  'Gourmet brewed coffee' 'Ethiopia Rg']
 [2 Timestamp('2023-01-01 00:00:00') datetime.time(7, 8, 56) ... 'Tea'
  'Brewed Chai tea' 'Spicy Eye Opener Chai Lg']
 [3 Timestamp('2023-01-01 00:00:00') datetime.time(7, 14, 4) ...
  'Drinking Chocolate' 'Hot chocolate' 'Dark chocolate Lg']
 ...
 [149454 Timestamp('2023-06-30 00:00:00') datetime.time(20, 31, 34) ...
  'Tea' 'Brewed herbal tea' 'Peppermint Lg']
 [149455 Timestamp('2023-06-30 00:00:00') datetime.time(20, 57, 19) ...
  'Coffee' 'Barista Espresso' 'Cappuccino']
 [149456 Timestamp('2023-06-30 00:00:00') datetime.time(20, 57, 19) ...
  'Flavours' 'Regular syrup' 'Hazelnut syrup']]

In [130]:
print("Number of records:", len(df))

Number of records: 149116

In [131]:
print("Number of records:", df.shape[0])

Number of records: 149116

In [132]:
print("Number of elements:", df.size)

Number of elements: 1640276

In [133]:
print("Column Data Types:")
print(df.dtypes)

Column Data Types:
transaction_id               int64
transaction_date    datetime64[ns]
transaction_time            object
transaction_qty              int64
store_id                     int64
store_location              object
product_id                   int64
unit_price                 float64
product_category            object
product_type                object
product_detail              object
dtype: object

In [134]:
print("Column Names:")
print(df.columns)

Column Names:
Index(['transaction_id', 'transaction_date', 'transaction_time',
       'transaction_qty', 'store_id', 'store_location', 'product_id',
       'unit_price', 'product_category', 'product_type', 'product_detail'],
      dtype='object')

In [135]:
df.describe()

,transaction_id,transaction_date,transaction_qty,store_id,product_id,unit_price
count,149116.000000,149116,149116.000000,149116.000000,149116.000000,149116.000000
mean,74737.371872,2023-04-15 11:50:32.173609984,1.438276,5.342063,47.918607,3.382219
min,1.000000,2023-01-01 00:00:00,1.000000,3.000000,1.000000,0.800000
25%,37335.750000,2023-03-06 00:00:00,1.000000,3.000000,33.000000,2.500000
50%,74727.500000,2023-04-24 00:00:00,1.000000,5.000000,47.000000,3.000000
75%,112094.250000,2023-05-30 00:00:00,2.000000,8.000000,60.000000,3.750000
max,149456.000000,2023-06-30 00:00:00,8.000000,8.000000,87.000000,45.000000
std,43153.600016,NaN,0.542509,2.074241,17.930020,2.658723

In [136]:
df.median(numeric_only=True)

transaction_id     74727.5
transaction_qty        1.0
store_id               5.0
product_id            47.0
unit_price             3.0
dtype: float64

In [137]:
df.mean(numeric_only=True)

transaction_id     74737.371872
transaction_qty        1.438276
store_id               5.342063
product_id            47.918607
unit_price             3.382219
dtype: float64

In [138]:
df.mode(numeric_only=True)

        transaction_id  transaction_qty  store_id  product_id  unit_price
0                    1              1.0       8.0        71.0         3.0
1                    2              NaN       NaN         NaN         NaN
2                    3              NaN       NaN         NaN         NaN
3                    4              NaN       NaN         NaN         NaN
4                    5              NaN       NaN         NaN         NaN
...                ...              ...       ...         ...         ...
149111          149452              NaN       NaN         NaN         NaN
149112          149453              NaN       NaN         NaN         NaN
149113          149454              NaN       NaN         NaN         NaN
149114          149455              NaN       NaN         NaN         NaN
149115          149456              NaN       NaN         NaN         NaN

[149116 rows x 5 columns]

In [139]:
df.std(numeric_only=True)

transaction_id     43153.600016
transaction_qty        0.542509
store_id               2.074241
product_id            17.930020
unit_price             2.658723
dtype: float64

In [140]:
df.sample(5)

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
41609,41716,2023-03-12,14:01:03,2,8,Hell's Kitchen,39,4.25,Coffee,Barista Espresso,Latte Rg
46805,46912,2023-03-19,17:59:38,1,5,Lower Manhattan,42,2.50,Tea,Brewed herbal tea,Lemon Grass Rg
91952,92206,2023-05-11,19:26:08,1,3,Astoria,26,3.00,Coffee,Organic brewed coffee,Brazilian Rg
147347,147684,2023-06-29,11:41:17,2,5,Lower Manhattan,87,2.10,Coffee,Barista Espresso,Ouro Brasileiro shot
40208,40315,2023-03-10,12:57:26,2,8,Hell's Kitchen,49,3.00,Tea,Brewed Black tea,English Breakfast Lg

In [141]:
df.sample(20)

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
144815,145152,2023-06-27,08:20:25,1,3,Astoria,45,3.00,Tea,Brewed herbal tea,Peppermint Lg
11980,12010,2023-01-21,18:17:40,2,3,Astoria,32,3.00,Coffee,Gourmet brewed coffee,Ethiopia Rg
147622,147959,2023-06-29,14:58:36,2,5,Lower Manhattan,29,2.50,Coffee,Gourmet brewed coffee,Columbian Medium Roast Rg
13466,13496,2023-01-24,13:00:19,1,3,Astoria,77,3.00,Bakery,Scone,Oatmeal Scone
85196,85370,2023-05-05,16:36:18,1,3,Astoria,75,3.50,Bakery,Pastry,Croissant
62153,62323,2023-04-09,17:46:14,1,3,Astoria,32,3.00,Coffee,Gourmet brewed coffee,Ethiopia Rg
110527,110781,2023-05-28,15:42:13,2,8,Hell's Kitchen,48,2.50,Tea,Brewed Black tea,English Breakfast Rg
73411,73581,2023-04-22,16:48:24,1,3,Astoria,75,3.50,Bakery,Pastry,Croissant
21834,21891,2023-02-09,07:52:18,1,5,Lower Manhattan,13,8.95,Loose Tea,Black tea,English Breakfast
43271,43378,2023-03-15,07:10:05,2,3,Astoria,36,3.75,Coffee,Premium brewed coffee,Jamaican Coffee River Lg
112180,112438,2023-05-30,09:46:33,2,8,Hell's Kitchen,48,2.50,Tea,Brewed Black tea,English Breakfast Rg
49684,49791,2023-03-24,07:32:54,2,8,Hell's Kitchen,72,3.25,Bakery,Scone,Ginger Scone
144339,144676,2023-06-26,14:45:21,1,3,Astoria,76,3.50,Bakery,Biscotti,Chocolate Chip Biscotti
67759,67929,2023-04-16,08:48:08,1,5,Lower Manhattan,45,3.00,Tea,Brewed herbal tea,Peppermint Lg
14749,14779,2023-01-26,16:25:18,1,8,Hell's Kitchen,74,3.50,Bakery,Biscotti,Ginger Biscotti
137530,137867,2023-06-20,18:24:14,1,3,Astoria,33,3.50,Coffee,Gourmet brewed coffee,Ethiopia Lg
35927,35984,2023-03-04,12:43:46,1,3,Astoria,33,3.50,Coffee,Gourmet brewed coffee,Ethiopia Lg
88514,88768,2023-05-08,17:54:26,1,8,Hell's Kitchen,51,3.00,Tea,Brewed Black tea,Earl Grey Lg
72584,72754,2023-04-21,15:38:12,1,3,Astoria,81,28.00,Branded,Clothing,I Need My Bean! T-shirt
148065,148406,2023-06-30,07:02:42,1,5,Lower Manhattan,20,7.60,Packaged Chocolate,Organic Chocolate,Sustainably Grown Organic

In [142]:
df.sample(2)

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
36806,36863,2023-03-05,16:15:49,2,8,Hell's Kitchen,22,2.0,Coffee,Drip coffee,Our Old Time Diner Blend Sm
18892,18922,2023-02-03,17:16:31,1,3,Astoria,58,3.5,Drinking Chocolate,Hot chocolate,Dark chocolate Rg

In [143]:
df.sample(13)

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
79900,80074,2023-04-30,10:59:43,1,8,Hell's Kitchen,26,3.00,Coffee,Organic brewed coffee,Brazilian Rg
102945,103199,2023-05-21,13:51:52,2,3,Astoria,30,3.00,Coffee,Gourmet brewed coffee,Columbian Medium Roast Lg
90218,90472,2023-05-10,09:35:35,1,8,Hell's Kitchen,30,3.00,Coffee,Gourmet brewed coffee,Columbian Medium Roast Lg
89837,90091,2023-05-10,07:05:20,1,8,Hell's Kitchen,87,3.00,Coffee,Barista Espresso,Ouro Brasileiro shot
60926,61096,2023-04-08,11:17:35,1,8,Hell's Kitchen,24,3.00,Coffee,Drip coffee,Our Old Time Diner Blend Lg
76848,77018,2023-04-26,15:53:53,2,8,Hell's Kitchen,51,3.00,Tea,Brewed Black tea,Earl Grey Lg
69822,69992,2023-04-18,11:23:03,1,8,Hell's Kitchen,35,3.10,Coffee,Premium brewed coffee,Jamaican Coffee River Rg
20393,20423,2023-02-06,14:57:17,1,8,Hell's Kitchen,51,3.00,Tea,Brewed Black tea,Earl Grey Lg
7876,7906,2023-01-15,07:22:05,1,3,Astoria,70,3.25,Bakery,Scone,Cranberry Scone
113658,113920,2023-05-31,17:21:48,2,3,Astoria,46,2.50,Tea,Brewed Green tea,Serenity Green Tea Rg
29584,29641,2023-02-22,06:02:09,3,5,Lower Manhattan,38,3.75,Coffee,Barista Espresso,Latte
19733,19763,2023-02-05,11:12:16,2,3,Astoria,40,3.75,Coffee,Barista Espresso,Cappuccino
30055,30112,2023-02-22,16:30:13,2,3,Astoria,36,3.75,Coffee,Premium brewed coffee,Jamaican Coffee River Lg

In [144]:
# Remove rows with missing values
df.dropna()

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
0,1,2023-01-01,07:06:11,2,5,Lower Manhattan,32,3.00,Coffee,Gourmet brewed coffee,Ethiopia Rg
1,2,2023-01-01,07:08:56,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
2,3,2023-01-01,07:14:04,2,5,Lower Manhattan,59,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
3,4,2023-01-01,07:20:24,1,5,Lower Manhattan,22,2.00,Coffee,Drip coffee,Our Old Time Diner Blend Sm
4,5,2023-01-01,07:22:41,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
...,...,...,...,...,...,...,...,...,...,...,...
149111,149452,2023-06-30,20:18:41,2,8,Hell's Kitchen,44,2.50,Tea,Brewed herbal tea,Peppermint Rg
149112,149453,2023-06-30,20:25:10,2,8,Hell's Kitchen,49,3.00,Tea,Brewed Black tea,English Breakfast Lg
149113,149454,2023-06-30,20:31:34,1,8,Hell's Kitchen,45,3.00,Tea,Brewed herbal tea,Peppermint Lg
149114,149455,2023-06-30,20:57:19,1,8,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,Cappuccino
149115,149456,2023-06-30,20:57:19,2,8,Hell's Kitchen,64,0.80,Flavours,Regular syrup,Hazelnut syrup

In [145]:
# List all attributes and methods of the DataFrame
dir(df)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__dataframe_consortium_standard__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_arith_method_with_reindex',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_create_data_for_split_and_tight_to_dict',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_nocopy',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'product_category',
 'product_detail',
 'product_id',
 'product_type',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'store_id',
 'store_location',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transaction_date',
 'transaction_id',
 'transaction_qty',
 'transaction_time',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unit_price',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [146]:
print("Mean values of the first 50 records:")
print(df.head(50).mean(numeric_only=True))

Mean values of the first 50 records:
transaction_id     25.500
transaction_qty     1.400
store_id            5.900
product_id         48.980
unit_price          3.161
dtype: float64

In [147]:
print("Mean values of the last 30 records:")
print(df.tail(30).mean(numeric_only=True))

Mean values of the last 30 records:
transaction_id     149441.500000
transaction_qty         1.500000
store_id                5.466667
product_id             44.766667
unit_price              3.598333
dtype: float64

In [148]:
df.columns

Index(['transaction_id', 'transaction_date', 'transaction_time',
       'transaction_qty', 'store_id', 'store_location', 'product_id',
       'unit_price', 'product_category', 'product_type', 'product_detail'],
      dtype='object')

In [151]:
df['transaction_date']

0        2023-01-01
1        2023-01-01
2        2023-01-01
3        2023-01-01
4        2023-01-01
            ...
149111   2023-06-30
149112   2023-06-30
149113   2023-06-30
149114   2023-06-30
149115   2023-06-30
Name: transaction_date, Length: 149116, dtype: datetime64[ns]

In [152]:
df['transaction_qty'].describe()

count    149116.000000
mean          1.438276
std           0.542509
min           1.000000
25%           1.000000
50%           1.000000
75%           2.000000
max           8.000000
Name: transaction_qty, dtype: float64

In [153]:
df['unit_price'].describe()

count    149116.000000
mean          3.382219
std           2.658723
min           0.800000
25%           2.500000
50%           3.000000
75%           3.750000
max          45.000000
Name: unit_price, dtype: float64

In [154]:
df['product_category'].count()

np.int64(149116)

In [155]:
df['product_type'].count()

np.int64(149116)

In [156]:
df['transaction_time'].mean()

TypeError: unsupported operand type(s) for +: 'datetime.time' and 'datetime.time'

In [157]:
df['unit_price'].describe()

count    149116.000000
mean          3.382219
std           2.658723
min           0.800000
25%           2.500000
50%           3.000000
75%           3.750000
max          45.000000
Name: unit_price, dtype: float64

In [158]:
df[10:20]

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
10,11,2023-01-01,07:43:05,1,5,Lower Manhattan,56,2.55,Tea,Brewed Chai tea,Spicy Eye Opener Chai Rg
11,12,2023-01-01,07:44:35,2,5,Lower Manhattan,33,3.50,Coffee,Gourmet brewed coffee,Ethiopia Lg
12,13,2023-01-01,07:45:51,1,5,Lower Manhattan,51,3.00,Tea,Brewed Black tea,Earl Grey Lg
13,14,2023-01-01,07:48:19,1,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
14,15,2023-01-01,07:52:36,2,5,Lower Manhattan,87,3.00,Coffee,Barista Espresso,Ouro Brasileiro shot
15,16,2023-01-01,07:59:58,2,5,Lower Manhattan,47,3.00,Tea,Brewed Green tea,Serenity Green Tea Lg
16,17,2023-01-01,07:59:58,1,5,Lower Manhattan,79,3.75,Bakery,Scone,Jumbo Savory Scone
17,18,2023-01-01,08:00:18,1,8,Hell's Kitchen,42,2.50,Tea,Brewed herbal tea,Lemon Grass Rg
18,19,2023-01-01,08:00:39,2,8,Hell's Kitchen,59,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
19,20,2023-01-01,08:11:45,1,8,Hell's Kitchen,61,4.75,Drinking Chocolate,Hot chocolate,Sustainably Grown Organic Lg

In [159]:
df[11:30]

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
11,12,2023-01-01,07:44:35,2,5,Lower Manhattan,33,3.50,Coffee,Gourmet brewed coffee,Ethiopia Lg
12,13,2023-01-01,07:45:51,1,5,Lower Manhattan,51,3.00,Tea,Brewed Black tea,Earl Grey Lg
13,14,2023-01-01,07:48:19,1,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
14,15,2023-01-01,07:52:36,2,5,Lower Manhattan,87,3.00,Coffee,Barista Espresso,Ouro Brasileiro shot
15,16,2023-01-01,07:59:58,2,5,Lower Manhattan,47,3.00,Tea,Brewed Green tea,Serenity Green Tea Lg
16,17,2023-01-01,07:59:58,1,5,Lower Manhattan,79,3.75,Bakery,Scone,Jumbo Savory Scone
17,18,2023-01-01,08:00:18,1,8,Hell's Kitchen,42,2.50,Tea,Brewed herbal tea,Lemon Grass Rg
18,19,2023-01-01,08:00:39,2,8,Hell's Kitchen,59,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
19,20,2023-01-01,08:11:45,1,8,Hell's Kitchen,61,4.75,Drinking Chocolate,Hot chocolate,Sustainably Grown Organic Lg
20,21,2023-01-01,08:17:27,2,8,Hell's Kitchen,33,3.50,Coffee,Gourmet brewed coffee,Ethiopia Lg
21,22,2023-01-01,08:24:26,2,5,Lower Manhattan,56,2.55,Tea,Brewed Chai tea,Spicy Eye Opener Chai Rg
22,23,2023-01-01,08:24:26,1,5,Lower Manhattan,69,3.25,Bakery,Biscotti,Hazelnut Biscotti
23,24,2023-01-01,08:29:38,1,8,Hell's Kitchen,56,2.55,Tea,Brewed Chai tea,Spicy Eye Opener Chai Rg
24,25,2023-01-01,08:31:23,1,8,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,Cappuccino
25,26,2023-01-01,08:33:08,1,5,Lower Manhattan,43,3.00,Tea,Brewed herbal tea,Lemon Grass Lg
26,27,2023-01-01,08:33:08,1,5,Lower Manhattan,76,3.50,Bakery,Biscotti,Chocolate Chip Biscotti
27,28,2023-01-01,08:35:03,2,5,Lower Manhattan,45,3.00,Tea,Brewed herbal tea,Peppermint Lg
28,29,2023-01-01,08:35:03,1,5,Lower Manhattan,71,3.75,Bakery,Pastry,Chocolate Croissant
29,30,2023-01-01,08:41:57,2,8,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,Cappuccino

In [160]:
df.loc[10:20,['transaction_id', 'transaction_date']]

    transaction_id transaction_date
10              11       2023-01-01
11              12       2023-01-01
12              13       2023-01-01
13              14       2023-01-01
14              15       2023-01-01
15              16       2023-01-01
16              17       2023-01-01
17              18       2023-01-01
18              19       2023-01-01
19              20       2023-01-01
20              21       2023-01-01

In [161]:
df.loc[34:40,['unit_price', 'product_category']]

    unit_price product_category
34        2.50              Tea
35        3.00           Coffee
36        4.00              Tea
37        3.75           Coffee
38        3.00              Tea
39        3.00              Tea
40        3.00           Coffee

In [162]:
#MISSING VALUE
df.dropna(how='all')

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
0,1,2023-01-01,07:06:11,2,5,Lower Manhattan,32,3.00,Coffee,Gourmet brewed coffee,Ethiopia Rg
1,2,2023-01-01,07:08:56,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
2,3,2023-01-01,07:14:04,2,5,Lower Manhattan,59,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
3,4,2023-01-01,07:20:24,1,5,Lower Manhattan,22,2.00,Coffee,Drip coffee,Our Old Time Diner Blend Sm
4,5,2023-01-01,07:22:41,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
...,...,...,...,...,...,...,...,...,...,...,...
149111,149452,2023-06-30,20:18:41,2,8,Hell's Kitchen,44,2.50,Tea,Brewed herbal tea,Peppermint Rg
149112,149453,2023-06-30,20:25:10,2,8,Hell's Kitchen,49,3.00,Tea,Brewed Black tea,English Breakfast Lg
149113,149454,2023-06-30,20:31:34,1,8,Hell's Kitchen,45,3.00,Tea,Brewed herbal tea,Peppermint Lg
149114,149455,2023-06-30,20:57:19,1,8,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,Cappuccino
149115,149456,2023-06-30,20:57:19,2,8,Hell's Kitchen,64,0.80,Flavours,Regular syrup,Hazelnut syrup

In [163]:
df.dropna(axis=1, how='all')

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
0,1,2023-01-01,07:06:11,2,5,Lower Manhattan,32,3.00,Coffee,Gourmet brewed coffee,Ethiopia Rg
1,2,2023-01-01,07:08:56,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
2,3,2023-01-01,07:14:04,2,5,Lower Manhattan,59,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
3,4,2023-01-01,07:20:24,1,5,Lower Manhattan,22,2.00,Coffee,Drip coffee,Our Old Time Diner Blend Sm
4,5,2023-01-01,07:22:41,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
...,...,...,...,...,...,...,...,...,...,...,...
149111,149452,2023-06-30,20:18:41,2,8,Hell's Kitchen,44,2.50,Tea,Brewed herbal tea,Peppermint Rg
149112,149453,2023-06-30,20:25:10,2,8,Hell's Kitchen,49,3.00,Tea,Brewed Black tea,English Breakfast Lg
149113,149454,2023-06-30,20:31:34,1,8,Hell's Kitchen,45,3.00,Tea,Brewed herbal tea,Peppermint Lg
149114,149455,2023-06-30,20:57:19,1,8,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,Cappuccino
149115,149456,2023-06-30,20:57:19,2,8,Hell's Kitchen,64,0.80,Flavours,Regular syrup,Hazelnut syrup

In [164]:
df.min(numeric_only=True)

transaction_id     1.0
transaction_qty    1.0
store_id           3.0
product_id         1.0
unit_price         0.8
dtype: float64

In [165]:
df.max(numeric_only=True)

transaction_id     149456.0
transaction_qty         8.0
store_id                8.0
product_id             87.0
unit_price             45.0
dtype: float64

In [166]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149116 entries, 0 to 149115
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    149116 non-null  int64
 1   transaction_date  149116 non-null  datetime64[ns]
 2   transaction_time  149116 non-null  object
 3   transaction_qty   149116 non-null  int64
 4   store_id          149116 non-null  int64
 5   store_location    149116 non-null  object
 6   product_id        149116 non-null  int64
 7   unit_price        149116 non-null  float64
 8   product_category  149116 non-null  object
 9   product_type      149116 non-null  object
 10  product_detail    149116 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(4), object(5)
memory usage: 12.5+ MB