In [1]:
import numpy as np
import pandas as pd

data = np.arange(15, 30).reshape(5, 3)
dfx = pd.DataFrame(
    data,
    index=["apple", "banana", "kiwi", "grapes", "mango"],
    columns=["store1", "store2", "store3"],
)

dfx["store4"] = np.nan
dfx["store5"] = np.nan

dfx.loc["watermelon"] = np.nan
dfx.loc["oranges"] = np.nan
dfx.loc["apple", "store4"] = 20

print(dfx)

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0    20.0     NaN
banana        18.0    19.0    20.0     NaN     NaN
kiwi          21.0    22.0    23.0     NaN     NaN
grapes        24.0    25.0    26.0     NaN     NaN
mango         27.0    28.0    29.0     NaN     NaN
watermelon     NaN     NaN     NaN     NaN     NaN
oranges        NaN     NaN     NaN     NaN     NaN

In [2]:
dfx.isnull()

            store1  store2  store3  store4  store5
apple        False   False   False   False    True
banana       False   False   False    True    True
kiwi         False   False   False    True    True
grapes       False   False   False    True    True
mango        False   False   False    True    True
watermelon    True    True    True    True    True
oranges       True    True    True    True    True

In [3]:
dfx.notnull()

            store1  store2  store3  store4  store5
apple         True    True    True    True   False
banana        True    True    True   False   False
kiwi          True    True    True   False   False
grapes        True    True    True   False   False
mango         True    True    True   False   False
watermelon   False   False   False   False   False
oranges      False   False   False   False   False

In [4]:
dfx.isnull().sum()

store1    2
store2    2
store3    2
store4    6
store5    7
dtype: int64

In [5]:
dfx.isnull().sum().sum()

np.int64(19)

In [6]:
dfx.count()

store1    5
store2    5
store3    5
store4    1
store5    0
dtype: int64

In [7]:
dfx.store4[dfx.store4.notnull()]

apple    20.0
Name: store4, dtype: float64

In [8]:
dfx.store4.dropna()

apple    20.0
Name: store4, dtype: float64

In [9]:
dfx.dropna()

Empty DataFrame
Columns: [store1, store2, store3, store4, store5]
Index: []

In [10]:
dfx.dropna(how='all')

        store1  store2  store3  store4  store5
apple     15.0    16.0    17.0    20.0     NaN
banana    18.0    19.0    20.0     NaN     NaN
kiwi      21.0    22.0    23.0     NaN     NaN
grapes    24.0    25.0    26.0     NaN     NaN
mango     27.0    28.0    29.0     NaN     NaN

In [11]:
dfx.dropna(how='all', axis=1)

            store1  store2  store3  store4
apple         15.0    16.0    17.0    20.0
banana        18.0    19.0    20.0     NaN
kiwi          21.0    22.0    23.0     NaN
grapes        24.0    25.0    26.0     NaN
mango         27.0    28.0    29.0     NaN
watermelon     NaN     NaN     NaN     NaN
oranges        NaN     NaN     NaN     NaN

In [12]:
dfx.dropna(thresh=5, axis=1)

            store1  store2  store3
apple         15.0    16.0    17.0
banana        18.0    19.0    20.0
kiwi          21.0    22.0    23.0
grapes        24.0    25.0    26.0
mango         27.0    28.0    29.0
watermelon     NaN     NaN     NaN
oranges        NaN     NaN     NaN

In [13]:
ar1 = np.array([100, 200, np.nan, 300])
ser1 = pd.Series(ar1)
ar1.mean(), ser1.mean()

(np.float64(nan), np.float64(200.0))

In [14]:
ser2 = dfx.store4
ser2.sum()

np.float64(20.0)

In [15]:
ser2.mean()

np.float64(20.0)

In [16]:
ser2.cumsum()

apple         20.0
banana         NaN
kiwi           NaN
grapes         NaN
mango          NaN
watermelon     NaN
oranges        NaN
Name: store4, dtype: float64

In [17]:
filledDf = dfx.fillna(0)
filledDf

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0    20.0     0.0
banana        18.0    19.0    20.0     0.0     0.0
kiwi          21.0    22.0    23.0     0.0     0.0
grapes        24.0    25.0    26.0     0.0     0.0
mango         27.0    28.0    29.0     0.0     0.0
watermelon     0.0     0.0     0.0     0.0     0.0
oranges        0.0     0.0     0.0     0.0     0.0

In [18]:
dfx.mean()

store1    21.0
store2    22.0
store3    23.0
store4    20.0
store5     NaN
dtype: float64

In [19]:
filledDf.mean()

store1    15.000000
store2    15.714286
store3    16.428571
store4     2.857143
store5     0.000000
dtype: float64

In [20]:
dfx.store4.fillna(method='ffill')

/tmp/ipykernel_801/4057730406.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfx.store4.fillna(method='ffill')

apple         20.0
banana        20.0
kiwi          20.0
grapes        20.0
mango         20.0
watermelon    20.0
oranges       20.0
Name: store4, dtype: float64

In [21]:
dfx.store4.fillna(method='bfill')

/tmp/ipykernel_801/2174360155.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfx.store4.fillna(method='bfill')

apple         20.0
banana         NaN
kiwi           NaN
grapes         NaN
mango          NaN
watermelon     NaN
oranges        NaN
Name: store4, dtype: float64